-- ============================================================
-- MY MOOD — Seed v3 · Batch 6 (100 venue)
-- ============================================================
-- Focus: brunch & colazioni, aperitivo quartieri periferici,
--        LGBTQ+ friendly, street food, musica dal vivo,
--        yoga & wellness, locali notturni emergenti
-- ============================================================
-- NOTA: tutti website_url = NULL (verifica manuale in futuro)
-- ============================================================
-- Supabase → SQL Editor → incolla tutto → Run
-- ============================================================

INSERT INTO venues (name, address, type, price_range, compatible_moods, description, tips, emoji, website_url, neighborhood)
VALUES

-- ══════════════════════════════════════════════════════════════
-- BRUNCH & COLAZIONI (10)
-- ══════════════════════════════════════════════════════════════

('Pavé Brunch',
 'Via Felice Casati 27',
 'bar', 'mid',
 ARRAY['rilassato','foodie','social','coffee_lover'],
 'Il brunch del sabato e domenica di Pavé è un''istituzione: uova benedettine, pancake, brioche salate. Caffè specialty e succhi freschi.',
 'Arriva alle 10 per evitare la coda — il brunch finisce alle 14 e i tavoli volano.',
 '🥞', NULL, 'porta_venezia'),

('Mag Café Brunch',
 'Ripa di Porta Ticinese 43',
 'bar', 'mid',
 ARRAY['rilassato','social','coffee_lover','vintage'],
 'Il brunch domenicale del Mag: uova strapazzate, avocado toast, torte fatte in casa, sul bordo del Naviglio. Atmosfera bohémien.',
 'I tavoli all''aperto sul Naviglio la domenica mattina sono il miglior modo di iniziare la giornata.',
 '☕', NULL, 'navigli'),

('Fiorellino Brera',
 'Via Fiori Chiari 12',
 'bar', 'mid',
 ARRAY['rilassato','elegante','foodie','social'],
 'Caffetteria-bistrot nel cuore di Brera: colazioni francesi, brunch internazionale, pâtisserie artigianale. Interni instagrammabili.',
 'Il croissant ai lamponi caldo appena sfornato è il migliore di Brera — arriva presto.',
 '🥐', NULL, 'brera'),

('Colibrì Brunch Isola',
 'Via Pastrengo 14',
 'bar', 'mid',
 ARRAY['rilassato','coffee_lover','social','creativo'],
 'Caffetteria specialty in Isola con brunch creativo: bowl, eggs benedict, granola fatta in casa. Ambiente minimal nordico.',
 'Il matcha latte con latte d''avena è il drink signature — accompagna con la granola bowl.',
 '🌿', NULL, 'isola'),

('Gattullo Colazione',
 'Piazzale di Porta Lodovica 2',
 'bar', 'low',
 ARRAY['rilassato','vintage','coffee_lover','foodie'],
 'Pasticceria storica dal 1961: cornetti caldi alle 6 del mattino, torte classiche milanesi, caffè al bancone con gli habitué del quartiere.',
 'Il cornetto alla crema pasticcera delle 7 del mattino è un rito — perfetto prima del lavoro.',
 '🧁', NULL, 'porta_romana'),

('Contrasto Caffè',
 'Via Tortona 12',
 'bar', 'mid',
 ARRAY['coffee_lover','creativo','rilassato','social'],
 'Micro-roastery e caffetteria specialty in zona Tortona: single origin, brewing methods alternativi, pastry artigianale.',
 'Chiedi l''espresso del giorno — cambiano origine ogni settimana ed è sempre una scoperta.',
 '☕', NULL, 'navigli'),

('Hana Bistrò',
 'Via Vigevano 35',
 'ristorante', 'mid',
 ARRAY['foodie','rilassato','social','creativo'],
 'Bistrò fusion giapponese-italiano sui Navigli: brunch con onigiri, uova alla giapponese, matcha pancake. La domenica è tutto esaurito.',
 'Il brunch della domenica è il migliore dei Navigli — prenota su Instagram giovedì sera.',
 '🍱', NULL, 'navigli'),

('La Colazione Milano',
 'Via Savona 50',
 'bar', 'mid',
 ARRAY['rilassato','foodie','social','coffee_lover'],
 'Locale dedicato esclusivamente alla colazione e al brunch: pancake tower, french toast, eggs in purgatory. Aperto solo dalle 8 alle 15.',
 'Il pancake tower con frutti di bosco e sciroppo d''acero è lo showstopper — da condividere in due.',
 '🫐', NULL, 'navigli'),

('Roots Milano',
 'Via Passubio 4',
 'bar', 'mid',
 ARRAY['coffee_lover','rilassato','zen','creativo'],
 'Caffetteria plant-based in zona Isola: latte vegetali fatti in casa, dolci vegani, bowl proteiche. Il caffè è specialty e tostato localmente.',
 'Il golden latte con curcuma fresca è il drink da provare — delicato e perfetto dopo yoga.',
 '🌱', NULL, 'isola'),

('Mamà Bakery',
 'Via Lecco 14',
 'bar', 'low',
 ARRAY['foodie','rilassato','coffee_lover','social'],
 'Panetteria-caffetteria in Porta Venezia: pane a lievitazione naturale, focacce farcite, torte della nonna. Il profumo del pane ti cattura dalla strada.',
 'La focaccia con stracciatella e pomodorini è il pranzo perfetto — take away e vai ai Giardini.',
 '🍞', NULL, 'porta_venezia'),

-- ══════════════════════════════════════════════════════════════
-- APERITIVO & BAR DI QUARTIERE (10)
-- ══════════════════════════════════════════════════════════════

('Santambroeus',
 'Corso Matteotti 7',
 'bar', 'high',
 ARRAY['elegante','aperitivo','social','vintage'],
 'Storico caffè-pasticceria milanese dal 1936: aperitivo classico con stuzzichini d''autore, interni art déco, clientela chic.',
 'Il Negroni Sbagliato è nato qui negli anni ''70 — ordinalo per il fattore storico.',
 '🍹', NULL, 'centro'),

('Bar Luce Wes Anderson',
 'Largo Isarco 2',
 'bar', 'mid',
 ARRAY['creativo','social','aperitivo','rilassato'],
 'Il bar progettato da Wes Anderson dentro Fondazione Prada: colori pastello, formica vintage, jukebox. Aperitivo in un set cinematografico.',
 'Ordinare un bitter è quasi obbligatorio — foto al bancone con il jukebox è d''ordinanza.',
 '🎬', NULL, 'porta_romana'),

('Birrificio di Lambrate — San Babila',
 'Via San Damiano 1',
 'bar', 'mid',
 ARRAY['social','rilassato','aperitivo','godereccio'],
 'La tap room in centro del Birrificio di Lambrate: birre artigianali alla spina, taglieri, atmosfera informale tra i palazzi eleganti di San Babila.',
 'La Ghisa (ambrata) è la birra più equilibrata — perfetta per chi inizia con le craft.',
 '🍺', NULL, 'centro'),

('Bar Magenta',
 'Via Carducci 13',
 'bar', 'mid',
 ARRAY['social','aperitivo','vintage','rilassato'],
 'Storico bar milanese dal 1907: bancone in legno, specchi antichi, aperitivo tradizionale con stuzzichini generosi. Frequentato da universitari e professionisti.',
 'L''aperitivo del venerdì è il più autentico — prezzi onesti e atmosfera vera.',
 '🏛️', NULL, 'sempione'),

('Ginger Cocktail Lab',
 'Via Plinio 19',
 'cocktail_bar', 'mid',
 ARRAY['social','aperitivo','creativo','elegante'],
 'Cocktail bar di ricerca in Città Studi: infusioni fatte in casa, ingredienti botanici, menù che cambia con le stagioni.',
 'Chiedi il cocktail del mese — lo chef bartender sperimenta con ingredienti insoliti come il miso.',
 '🧪', NULL, 'altro'),

('Vivace Spritz Bar',
 'Corso di Porta Ticinese 83',
 'bar', 'low',
 ARRAY['social','aperitivo','festivo','rilassato'],
 'Bar specializzato in spritz e aperitivi a prezzi democratici: 15 varianti di spritz, taglieri, musica dal vivo il giovedì.',
 'Lo spritz al Campari con oliva è il classico — il giovedì sera c''è musica live e costa come un giorno qualsiasi.',
 '🍊', NULL, 'navigli'),

('Bottiglieria di Roberto',
 'Via Sottocorno 17',
 'bar', 'mid',
 ARRAY['aperitivo','vintage','rilassato','social'],
 'Enoteca-bar nascosta in Porta Venezia: vini naturali al bicchiere, taglieri con salumi artigianali, pochi tavoli. Il segreto dei residenti.',
 'Chiedi a Roberto il vino del momento — ha un fiuto infallibile per i piccoli produttori.',
 '🍷', NULL, 'porta_venezia'),

('Fabbrica del Vapore Bar',
 'Via Procaccini 4',
 'bar', 'low',
 ARRAY['social','creativo','alternativo','aperitivo'],
 'Il bar all''interno della Fabbrica del Vapore: spazio culturale con eventi, mostre, DJ set all''aperto. Aperitivo tra arte e rigenerazione urbana.',
 'D''estate l''aperitivo nel cortile con le installazioni è l''esperienza migliore — gratis l''ingresso.',
 '🎨', NULL, 'sempione'),

('Bere Bene Porta Nuova',
 'Via Maroncelli 8',
 'cocktail_bar', 'mid',
 ARRAY['elegante','aperitivo','social','rilassato'],
 'Cocktail bar con filosofia "less is more": pochi ingredienti, drink equilibrati, interni minimal. Il bartender spiega ogni cocktail come un sommelier.',
 'Il Martini classico qui è perfetto — chiedi la versione con vermouth italiano artigianale.',
 '🫒', NULL, 'porta_nuova'),

('Tropico Milano',
 'Via Carmagnola 9',
 'bar', 'mid',
 ARRAY['social','festivo','aperitivo','musicale'],
 'Bar tropicale in Isola: rum cocktail, açaí bowl, musica brasiliana e reggaeton. D''estate il dehors diventa una spiaggia urbana.',
 'La caipirinha con cachaça premium è un livello sopra — perfetta d''estate nel dehors.',
 '🌴', NULL, 'isola'),

-- ══════════════════════════════════════════════════════════════
-- CUCINA INTERNAZIONALE (10)
-- ══════════════════════════════════════════════════════════════

('Pho Milano',
 'Via Paolo Sarpi 42',
 'ristorante', 'low',
 ARRAY['foodie','social','rilassato'],
 'Il miglior pho vietnamita di Milano nella Chinatown milanese: brodo cotto 12 ore, erbe fresche, spring roll fritti. Coda sempre presente.',
 'Il pho bo (manzo) è il piatto da ordinare — aggiungi sriracha e hoisin a piacere.',
 '🍜', NULL, 'sempione'),

('Gyoza Bar Navigli',
 'Via Corsico 12',
 'ristorante', 'low',
 ARRAY['foodie','social','rilassato','creativo'],
 'Gyoza bar minimalista sui Navigli: ravioli giapponesi alla piastra, al vapore, fritti. 12 ripieni diversi, birra giapponese, zero fronzoli.',
 'I gyoza al maiale e erba cipollina alla piastra sono il classico — ordina anche quelli al gambero.',
 '🥟', NULL, 'navigli'),

('Beirut Kitchen',
 'Via Sammartini 21',
 'ristorante', 'low',
 ARRAY['foodie','social','rilassato','avventuroso'],
 'Cucina libanese autentica vicino Stazione Centrale: hummus, falafel, shawarma, tabbouleh. Porzioni generose, prezzi bassi, sapori veri.',
 'Il piatto misto con hummus, falafel e shawarma è il modo migliore per assaggiare tutto — da condividere.',
 '🫓', NULL, 'altro'),

('Taco Luchador',
 'Via Tortona 20',
 'ristorante', 'low',
 ARRAY['foodie','social','festivo','avventuroso'],
 'Taqueria messicana autentica in zona Tortona: tacos al pastor, carnitas, guacamole fatto al momento. Margarita con mezcal.',
 'I tacos al pastor con ananas grigliato sono i migliori — accompagna con una Michelada.',
 '🌮', NULL, 'navigli'),

('Kimchi House',
 'Via Nino Bixio 30',
 'ristorante', 'mid',
 ARRAY['foodie','social','avventuroso','creativo'],
 'Ristorante coreano autentico vicino Porta Venezia: bibimbap, kimchi jjigae, Korean fried chicken. Bancone con griglia a tavola per il BBQ.',
 'Il Korean BBQ per due con il set completo è l''esperienza migliore — la carne la cuoci tu.',
 '🥘', NULL, 'porta_venezia'),

('Ruyi Dumpling Bar',
 'Via Paolo Sarpi 28',
 'ristorante', 'low',
 ARRAY['foodie','social','rilassato'],
 'Specializzato in dumpling cinesi fatti a mano in Chinatown: xiao long bao, shui jiao, guo tie. Cucina a vista, ingredienti freschissimi.',
 'Gli xiao long bao (dumpling con brodo) sono il piatto da non perdere — attento, scottano!',
 '🥢', NULL, 'sempione'),

('Curry Up Milano',
 'Via Tadino 15',
 'ristorante', 'low',
 ARRAY['foodie','social','avventuroso','rilassato'],
 'Street food indiano moderno: butter chicken, biryani, naan al formaggio, lassi alla rosa. Veloce, economico, saporito.',
 'Il butter chicken con naan al formaggio è la combo perfetta — aggiungi un mango lassi.',
 '🍛', NULL, 'porta_venezia'),

('Onda Poké',
 'Via Washington 70',
 'ristorante', 'low',
 ARRAY['foodie','rilassato','zen','social'],
 'Poké bowl hawaiano con ingredienti premium: tonno fresco, salmone, edamame, riso sushi. Tutto personalizzabile.',
 'La bowl signature con tonno, avocado e salsa ponzu è la più equilibrata — aggiungi mango per il twist.',
 '🐟', NULL, 'sempione'),

('Smørrebrød Milano',
 'Via Solferino 11',
 'ristorante', 'mid',
 ARRAY['foodie','creativo','elegante','rilassato'],
 'Cucina danese in Brera: smørrebrød (open sandwich), piatti nordici, design scandinavo. L''unico ristorante danese autentico di Milano.',
 'Lo smørrebrød con salmone affumicato e crema di rafano è il piatto iconico — elegante e leggero.',
 '🇩🇰', NULL, 'brera'),

('La Paella de Miguel',
 'Via Caminadella 7',
 'ristorante', 'mid',
 ARRAY['foodie','social','godereccio','festivo'],
 'Ristorante spagnolo autentico vicino al Duomo: paella valenciana cotta nel padellone, tapas, sangría. Il proprietario Miguel cucina davanti a te.',
 'La paella va ordinata per minimo due persone e ci vogliono 25 minuti — ordinala subito e nel frattempo tapas.',
 '🥘', NULL, 'centro'),

-- ══════════════════════════════════════════════════════════════
-- LOCALI LGBTQ+ FRIENDLY (8)
-- ══════════════════════════════════════════════════════════════

('Mono Bar',
 'Via Lecco 6',
 'bar', 'mid',
 ARRAY['social','alternativo','musicale','nottambulo'],
 'Bar-club LGBTQ+ friendly nel cuore di Porta Venezia: DJ set, drag show, aperitivi, atmosfera inclusiva e accogliente. Uno dei punti di riferimento della comunità.',
 'Il giovedì sera c''è il drag show — arriva presto perché si riempie.',
 '🌈', NULL, 'porta_venezia'),

('Leccomilano',
 'Via Lecco 5',
 'bar', 'mid',
 ARRAY['social','aperitivo','rilassato','alternativo'],
 'Bar storico della scena LGBTQ+ di Porta Venezia: aperitivo rilassato, dehors animato, frequentato da un mix eterogeneo e accogliente.',
 'L''aperitivo del venerdì nel dehors è il rituale della comunità — perfetto per socializzare.',
 '🏳️‍🌈', NULL, 'porta_venezia'),

('Company Club',
 'Via Benadir 14',
 'club', 'mid',
 ARRAY['nottambulo','social','festivo','musicale','alternativo'],
 'Club LGBTQ+ storico di Milano: serate a tema, drag performance, musica pop e dance. Ambiente sicuro, festoso, senza giudizi.',
 'Il sabato sera è la serata principale — dress code libero, vibes inclusive.',
 '💜', NULL, 'altro'),

('Glitter Bar',
 'Via Panfilo Castaldi 20',
 'bar', 'mid',
 ARRAY['social','festivo','alternativo','aperitivo'],
 'Cocktail bar LGBTQ+ friendly in via Castaldi: drink creativi, musica pop, atmosfera glamour e rilassata. Aperto fino a tardi.',
 'I cocktail a tema cambiano ogni mese — chiedi quello del momento al bartender.',
 '✨', NULL, 'porta_venezia'),

('After Line',
 'Via Sammartini 25',
 'club', 'mid',
 ARRAY['nottambulo','musicale','social','festivo'],
 'Club con serate LGBTQ+ e queer party: techno, house, performance art. Spazio industriale, community underground, inclusività totale.',
 'Le serate del sabato sono le più popolari — controlla la programmazione su Instagram.',
 '🔮', NULL, 'altro'),

('Pop Milano',
 'Via Panfilo Castaldi 22',
 'bar', 'mid',
 ARRAY['social','festivo','aperitivo','rilassato'],
 'Bar colorato in Porta Venezia: aperitivi pop, playlist anni ''80-''90, atmosfera camp e divertente. Il posto dove tutti sono benvenuti.',
 'La serata karaoke del mercoledì è esilarante — partecipa anche se non sai cantare.',
 '🎤', NULL, 'porta_venezia'),

('Plastic Fantastic Café',
 'Via Gian Giacomo Mora 3',
 'bar', 'mid',
 ARRAY['creativo','social','alternativo','aperitivo'],
 'Caffè culturale queer-friendly in Colonne di San Lorenzo: mostre, presentazioni di libri, reading, DJ set mellow. Spazio safe per la comunità creativa.',
 'Le serate di reading e poetry slam del martedì sono gratuite e sempre interessanti.',
 '📚', NULL, 'navigli'),

('Rainbow Lounge',
 'Via Castel Morrone 6',
 'lounge', 'mid',
 ARRAY['social','rilassato','elegante','aperitivo'],
 'Lounge bar LGBTQ+ friendly in zona Porta Venezia: cocktail d''autore, divani, luci soffuse. Aperitivo tranquillo e serate chic senza la frenesia dei club.',
 'L''aperitivo del giovedì è il più rilassato della settimana — perfetto per conversare.',
 '🌙', NULL, 'porta_venezia'),

-- ══════════════════════════════════════════════════════════════
-- STREET FOOD & FAST CASUAL (10)
-- ══════════════════════════════════════════════════════════════

('Trippa Panino',
 'Via Giorgio Vasari 1',
 'altro', 'low',
 ARRAY['foodie','godereccio','rilassato','social'],
 'Lo spin-off street food del ristorante Trippa: panini con trippa alla milanese, lampredotto, bollito. Il cibo di strada milanese fatto bene.',
 'Il panino con lampredotto e salsa verde è il must — mangialo in piedi come un vero milanese.',
 '🥪', NULL, 'porta_romana'),

('Ape Cesare',
 'Piazza XXIV Maggio',
 'altro', 'low',
 ARRAY['foodie','social','rilassato','festivo'],
 'Apecar con panini gourmet alle Colonne: pane fatto in casa, ingredienti premium, birra artigianale. Il miglior street food della Darsena.',
 'Il panino con porchetta e salsa di fichi è il bestseller — perfetto con una birra alla spina.',
 '🛺', NULL, 'navigli'),

('Arancini Factory',
 'Via Solferino 20',
 'altro', 'low',
 ARRAY['foodie','social','rilassato'],
 'Specializzato in arancini siciliani fatti al momento: classico al ragù, pistacchio, nduja, burrata. Croccanti fuori, cremosi dentro.',
 'L''arancino al pistacchio di Bronte è il migliore — prendine due, uno non basta.',
 '🟠', NULL, 'brera'),

('Piadineria Romagnola Brera',
 'Via Madonnina 3',
 'altro', 'low',
 ARRAY['foodie','rilassato','social'],
 'Piadineria autentica romagnola nel cuore di Brera: piadina tirata a mano, squacquerone DOP, prosciutto crudo, rucola. Veloce e genuina.',
 'La classica con squacquerone e rucola è perfetta — aggiungi la salsiccia se hai fame.',
 '🫓', NULL, 'brera'),

('Toast Milano',
 'Via Tortona 15',
 'altro', 'low',
 ARRAY['foodie','social','rilassato','creativo'],
 'Tosteria gourmet in zona Tortona: toast creativi con ingredienti premium, da quello con tartufo al classico prosciutto e fontina. Tutto in pane artigianale.',
 'Il toast con burrata e ''nduja è il piatto signature — croccante fuori, cremoso dentro.',
 '🍞', NULL, 'navigli'),

('Empanadas Buenos Aires',
 'Corso Buenos Aires 54',
 'altro', 'low',
 ARRAY['foodie','social','rilassato','avventuroso'],
 'Le migliori empanadas argentine di Milano: carne, pollo, verdure, dolci. Fatte a mano ogni giorno con ricetta della nonna.',
 'Le empanadas de carne sono il classico — prendine almeno tre varietà per assaggiare tutto.',
 '🥟', NULL, 'porta_venezia'),

('Bomba Fritta',
 'Via Vigevano 20',
 'altro', 'low',
 ARRAY['foodie','godereccio','social','festivo'],
 'Street food di fritture gourmet sui Navigli: olive ascolane, supplì, fiori di zucca, crocchette. Tutto fritto al momento, croccante e leggero.',
 'Il cono misto con 5 fritture diverse è il modo migliore per assaggiare tutto — 8€ ben spesi.',
 '💣', NULL, 'navigli'),

('Tigelle & Gnocco',
 'Via Forcella 7',
 'altro', 'low',
 ARRAY['foodie','godereccio','social','vintage'],
 'Gnocco fritto e tigelle come in Emilia: lardo, stracchino, salumi, pesto di mortadella. Lo street food emiliano più comfort che esista.',
 'Il gnocco fritto con lardo e stracchino è il comfort food definitivo — una tira l''altra.',
 '🫓', NULL, 'centro'),

('Kebab Turco Originale',
 'Via Padova 38',
 'altro', 'low',
 ARRAY['foodie','social','rilassato','avventuroso'],
 'Kebab turco autentico su Via Padova: döner fatto in casa, lahmacun, pide, ayran. Il quartiere multietnico di Milano al suo meglio.',
 'Il lahmacun (pizza turca) è sottovalutato — ordinalo con limone e prezzemolo fresco.',
 '🥙', NULL, 'altro'),

('Onigiri Lab',
 'Via Paolo Sarpi 15',
 'altro', 'low',
 ARRAY['foodie','rilassato','social','creativo'],
 'Laboratorio di onigiri giapponesi in Chinatown: riso giapponese, ripieni tradizionali (salmone, umeboshi, tonno mayo), nori croccante.',
 'L''onigiri al salmone è il classico, ma prova quello all''umeboshi — acido e addictive.',
 '🍙', NULL, 'sempione'),

-- ══════════════════════════════════════════════════════════════
-- MUSICA DAL VIVO & CONCERTI (8)
-- ══════════════════════════════════════════════════════════════

('Biko Club',
 'Viale d''Annunzio 15',
 'club', 'low',
 ARRAY['musicale','alternativo','social','creativo'],
 'Circolo ARCI con concerti indie, punk, elettronica. Piccolo palco, grande sound, birra economica. Il cuore della scena underground milanese.',
 'Controlla la programmazione settimanale — i concerti indie del giovedì sono i migliori.',
 '🎸', NULL, 'navigli'),

('Ohibò Live',
 'Via Benaco 1',
 'altro', 'low',
 ARRAY['musicale','social','alternativo','creativo'],
 'Live club in Porta Romana: concerti emergenti, jam session, stand-up comedy. Spazio intimo, acustica ottima, birra artigianale.',
 'Le jam session del lunedì sono gratuite e spesso si uniscono musicisti famosi — sorpresa garantita.',
 '🎵', NULL, 'porta_romana'),

('Circolo Arci Orfeo',
 'Via dell''Orso 18',
 'altro', 'low',
 ARRAY['musicale','alternativo','social','vintage'],
 'Circolo ARCI nel centro storico: jazz, blues, folk dal vivo. Spazio piccolo, atmosfera intima, pubblico appassionato. Tessera ARCI richiesta.',
 'Il venerdì sera jazz è un appuntamento fisso — tessera ARCI a 10€ annuali, vale la pena.',
 '🎷', NULL, 'centro'),

('Rocket Milano',
 'Via Pezzotti 52',
 'club', 'low',
 ARRAY['musicale','alternativo','social','nottambulo'],
 'Live club in zona Sud: punk, hardcore, metal, noise. Palco vicino al pubblico, sound potente, comunità affiatata.',
 'I concerti hardcore del sabato hanno l''energia più alta — porta i tappi per le orecchie.',
 '🚀', NULL, 'altro'),

('La Balera dell''Ortica',
 'Via San Faustino 7',
 'altro', 'low',
 ARRAY['musicale','social','vintage','festivo','rilassato'],
 'Balera all''aperto nel quartiere Ortica: balli di gruppo, liscio, swing, musica dal vivo. La tradizione della balera milanese rivive qui.',
 'Le serate swing estive sono magiche — non serve saper ballare, ti insegnano lì.',
 '💃', NULL, 'altro'),

('Apollo Live Club',
 'Via Borsi 9',
 'club', 'mid',
 ARRAY['musicale','social','nottambulo','festivo'],
 'Il palco live dell''Apollo: band emergenti, cover band, tribute night. Dopo il concerto si balla fino alle 3.',
 'Le tribute night del sabato (Queen, Bowie, Beatles) sono sempre sold out — biglietti in anticipo.',
 '🌟', NULL, 'navigli'),

('Garage Moulinski',
 'Via Magolfa 14',
 'altro', 'low',
 ARRAY['musicale','alternativo','creativo','social'],
 'Garage convertito in spazio per concerti e jam session: blues, rock, funk. Massimo 80 persone, atmosfera raw e autentica.',
 'Le jam session aperte del mercoledì accettano chiunque voglia suonare — porta il tuo strumento.',
 '🎸', NULL, 'navigli'),

('Santeria Toscana Live',
 'Via Toscana 31',
 'altro', 'mid',
 ARRAY['musicale','social','creativo','alternativo'],
 'Il palco live della Santeria Toscana: concerti indie, elettronica, DJ set. Anche ristorante, coworking e libreria. Hub culturale completo.',
 'I concerti nel cortile d''estate sono i migliori — aperitivo + concerto è la formula perfetta.',
 '🎶', NULL, 'porta_romana'),

-- ══════════════════════════════════════════════════════════════
-- WELLNESS & RELAX (8)
-- ══════════════════════════════════════════════════════════════

('Shala Yoga Milano',
 'Via Savona 97',
 'attivita', 'mid',
 ARRAY['zen','rilassato','sportivo','social'],
 'Centro yoga in zona Tortona: Hatha, Vinyasa, Yin, meditazione. Classi per tutti i livelli, insegnanti certificati, spazio luminoso e silenzioso.',
 'La lezione di Yin Yoga del venerdì sera è perfetta per rilassarsi dopo la settimana lavorativa.',
 '🧘', NULL, 'navigli'),

('Terme di Porta Romana',
 'Via Lamarmora 13',
 'attivita', 'high',
 ARRAY['zen','rilassato','elegante','social'],
 'Boutique spa nel cuore di Porta Romana: percorso termale, sauna finlandese, bagno turco, massaggi. Piccola, intima, prenotazione obbligatoria.',
 'Il percorso termale serale (dopo le 19) è meno affollato e più rilassante.',
 '♨️', NULL, 'porta_romana'),

('Float Therapy Lab',
 'Via Copernico 38',
 'attivita', 'mid',
 ARRAY['zen','rilassato','misterioso','creativo'],
 'Il primo centro di float therapy a Milano: vasche di deprivazione sensoriale con acqua e sale di Epsom. 60 minuti di galleggiamento nel buio totale.',
 'La prima sessione è sempre strana — dalla seconda volta il rilassamento è profondissimo.',
 '💧', NULL, 'altro'),

('Bikram Yoga Milano',
 'Via Borsieri 12',
 'attivita', 'mid',
 ARRAY['sportivo','zen','social'],
 'Hot yoga in Isola: 26 posture in una stanza a 40°C. Sfidante ma rigenerante. Classi per principianti e avanzati.',
 'Porta un asciugamano grande e una bottiglia d''acqua da 1.5L — ne avrai bisogno.',
 '🔥', NULL, 'isola'),

('Pilates Garage',
 'Via Tortona 5',
 'attivita', 'mid',
 ARRAY['sportivo','zen','rilassato','social'],
 'Studio di Pilates in uno spazio industriale in zona Tortona: reformer, mat, classi piccole (max 8 persone). Istruttori di alto livello.',
 'La lezione di reformer del mattino è la più efficace — prenota con almeno 3 giorni di anticipo.',
 '🤸', NULL, 'navigli'),

('Zen Zone Meditation',
 'Via Solferino 28',
 'attivita', 'mid',
 ARRAY['zen','rilassato','misterioso','creativo'],
 'Centro di meditazione guidata in Brera: sessioni di mindfulness, breathing, meditazione trascendentale. Spazio minimalista, zero distrazioni.',
 'La sessione di breathing del lunedì mattina alle 7:30 è il modo migliore per iniziare la settimana.',
 '🕉️', NULL, 'brera'),

('Nordik Spa',
 'Via Procaccini 10',
 'attivita', 'mid',
 ARRAY['zen','rilassato','social','elegante'],
 'Day spa ispirata alle tradizioni nordiche: sauna a legna, bagno freddo, zona relax. Il rituale caldo-freddo in stile finlandese.',
 'Il ciclo sauna + bagno freddo va ripetuto 3 volte — dopo la terza il rilassamento è totale.',
 '🧊', NULL, 'sempione'),

('Sound Bath Milano',
 'Via Vigevano 8',
 'attivita', 'mid',
 ARRAY['zen','misterioso','rilassato','creativo'],
 'Sessioni di bagno sonoro con gong, campane tibetane, singing bowls. Sdraiarsi e lasciare che le vibrazioni sciolgano lo stress.',
 'La sessione serale del sabato è la più intensa — arriva 10 minuti prima per sistemarti.',
 '🔔', NULL, 'navigli'),

-- ══════════════════════════════════════════════════════════════
-- ATTIVITÀ & ESPERIENZE (10)
-- ══════════════════════════════════════════════════════════════

('Pottery Lab Milano',
 'Via Savona 56',
 'attivita', 'mid',
 ARRAY['creativo','rilassato','social','zen'],
 'Laboratorio di ceramica aperto a tutti: corsi di tornio, smaltatura, scultura. Perfetto per una serata creativa con amici o un appuntamento originale.',
 'Il corso di tornio per principianti dura 2 ore e porti a casa la tua creazione — prenota per 2.',
 '🏺', NULL, 'navigli'),

('Paint & Wine',
 'Via Tortona 8',
 'attivita', 'mid',
 ARRAY['creativo','social','rilassato','festivo'],
 'Serate di pittura con vino incluso: un artista ti guida passo passo a dipingere un quadro mentre bevi. Nessuna esperienza richiesta.',
 'Prenota il venerdì sera — l''atmosfera è più festosa e il vino scorre meglio.',
 '🎨', NULL, 'navigli'),

('Cucina Lab Experience',
 'Via Festa del Perdono 6',
 'attivita', 'mid',
 ARRAY['foodie','social','creativo','godereccio'],
 'Corsi di cucina esperienziali: pasta fresca, risotto, pizza napoletana, sushi. Cucini, impari, poi mangi tutto quello che hai preparato.',
 'Il corso di pasta fresca è il più divertente — impari a fare ravioli e tagliatelle da zero.',
 '👨‍🍳', NULL, 'centro'),

('Wine Tasting Club',
 'Via Solferino 35',
 'attivita', 'mid',
 ARRAY['foodie','social','elegante','godereccio'],
 'Degustazioni guidate di vino in Brera: verticali, orizzontali, blind tasting. Il sommelier spiega tutto in modo accessibile, anche per neofiti.',
 'Le blind tasting del venerdì sono le più divertenti — indovinare il vino è più difficile di quanto pensi.',
 '🍷', NULL, 'brera'),

('Comedy Ring Milano',
 'Via De Amicis 17',
 'altro', 'mid',
 ARRAY['social','festivo','creativo','rilassato'],
 'Open mic e stand-up comedy in italiano e inglese: comici emergenti e ospiti a sorpresa. Birra, risate, atmosfera intima.',
 'L''open mic del martedì è gratuito — puoi anche iscriverti per fare 5 minuti di stand-up.',
 '😂', NULL, 'navigli'),

('Tango Milonga',
 'Via Piacenza 11',
 'attivita', 'mid',
 ARRAY['musicale','social','romantico','elegante'],
 'Milonga settimanale con lezione per principianti inclusa: tango argentino, vals, milonga. Anche se non hai mai ballato, qui ti insegnano.',
 'La lezione per principianti inizia alle 21 — arriva in orario, dopo si balla liberi.',
 '🩰', NULL, 'porta_romana'),

('Vintage Market Milano',
 'Piazza Frattini',
 'altro', 'low',
 ARRAY['creativo','vintage','social','alternativo'],
 'Mercato vintage itinerante: abbigliamento second-hand, vinili, mobili retrò, oggettistica. Ogni primo sabato del mese in piazze diverse.',
 'Arriva la mattina presto per i pezzi migliori — i cappotti vintage volano in 30 minuti.',
 '👗', NULL, 'navigli'),

('Running Club Parco Sempione',
 'Piazza Sempione 1',
 'attivita', 'low',
 ARRAY['sportivo','social','zen','rilassato'],
 'Gruppo di corsa gratuito ogni martedì e giovedì alle 19: 5-10km nel parco, tutti i livelli. Dopo la corsa, birra insieme.',
 'Il martedì è il giorno più frequentato — presentati al gazebo alle 18:50, non serve prenotare.',
 '🏃', NULL, 'sempione'),

('Cinema all''Aperto Arianteo',
 'Palazzo Reale — Cortile',
 'cinema', 'low',
 ARRAY['culturale','social','rilassato','romantico'],
 'Il cinema all''aperto estivo nel cortile di Palazzo Reale: film d''autore, anteprime, classici restaurati. L''esperienza cinematografica più suggestiva di Milano.',
 'Porta un cuscino per le sedie — i posti centrali nelle file 5-8 sono i migliori.',
 '🎬', NULL, 'centro'),

('Secret Room Escape',
 'Via Meda 3',
 'attivita', 'mid',
 ARRAY['avventuroso','social','misterioso','creativo'],
 'Escape room immersiva con scenografie teatrali: 4 stanze a tema (horror, detective, sci-fi, fantasy). Gruppi da 2 a 6, difficoltà variabile.',
 'La stanza detective è la più equilibrata per principianti — quella horror è davvero spaventosa.',
 '🔐', NULL, 'navigli'),

-- ══════════════════════════════════════════════════════════════
-- RISTORANTI — PESCE & MARE (6)
-- ══════════════════════════════════════════════════════════════

('Crudo Milano',
 'Via Solferino 44',
 'ristorante', 'high',
 ARRAY['foodie','elegante','romantico','social'],
 'Raw bar e ristorante di pesce in Brera: crudi, tartare, ostriche, ceviche. Pesce freschissimo, presentazione elegante, ambiente raffinato.',
 'Il plateau di crudi per due è lo showpiece — accompagna con un Vermentino.',
 '🦪', NULL, 'brera'),

('Trattoria del Pescatore',
 'Via Anfossi 10',
 'trattoria', 'mid',
 ARRAY['foodie','godereccio','rilassato','vintage'],
 'Trattoria di pesce classica in Porta Romana: spaghetti alle vongole, fritto misto, grigliata di pesce. Il mare a Milano, senza fronzoli.',
 'Lo spaghetto alle vongole del mercoledì è il piatto da non perdere — solo vongole veraci.',
 '🐚', NULL, 'porta_romana'),

('Oyster Bar Brera',
 'Via Pontaccio 19',
 'bar', 'high',
 ARRAY['elegante','foodie','aperitivo','romantico'],
 'Oyster bar in Brera: ostriche francesi e irlandesi, champagne al calice, tartare di tonno. L''aperitivo più raffinato di Milano.',
 'Le ostriche Fine de Claire n.3 sono le migliori — abbina con un calice di Blanc de Blancs.',
 '🥂', NULL, 'brera'),

('Gastronomia del Mare',
 'Via Vigevano 42',
 'ristorante', 'mid',
 ARRAY['foodie','social','godereccio','rilassato'],
 'Gastronomia di pesce fresco sui Navigli: piatti pronti, frittura da asporto, insalate di mare. Qualità da ristorante, prezzi da gastronomia.',
 'La frittura mista da asporto è perfetta per un pranzo sui Navigli — siediti sulla sponda e godi.',
 '🍤', NULL, 'navigli'),

('Cozze & Vino',
 'Via Casale 5',
 'ristorante', 'mid',
 ARRAY['foodie','social','godereccio','festivo'],
 'Specializzato in cozze: alla marinara, alla tarantina, gratinate, con birra belga. 12 preparazioni diverse, pentolone fumante al centro del tavolo.',
 'Le cozze alla marinara con il pane per fare la scarpetta sono irresistibili — ordina il pentolone per due.',
 '🫕', NULL, 'porta_venezia'),

('Sushi Masterclass',
 'Via Tortona 33',
 'attivita', 'mid',
 ARRAY['foodie','creativo','social','avventuroso'],
 'Masterclass di sushi con chef giapponese: impari a fare nigiri, maki, temaki. 2 ore, poi mangi tutto quello che hai preparato.',
 'Il corso del sabato mattina è il più rilassato — arrivi fresco e mangi il tuo sushi come pranzo.',
 '🍣', NULL, 'navigli'),

-- ══════════════════════════════════════════════════════════════
-- SPAZI CULTURALI & LIBRERIE (10)
-- ══════════════════════════════════════════════════════════════

('Libreria Centofiori',
 'Via delle Asole 2',
 'altro', 'low',
 ARRAY['culturale','rilassato','creativo','zen'],
 'Libreria indipendente nel centro storico: selezione curata, eventi letterari, presentazioni di libri. Piccola, accogliente, gestita da appassionati.',
 'Il giovedì sera ci sono presentazioni di libri con aperitivo — gratuito e sempre stimolante.',
 '📖', NULL, 'centro'),

('Cascinet — Spazio Culturale',
 'Via Cavriana 38',
 'altro', 'low',
 ARRAY['culturale','creativo','alternativo','social'],
 'Cascina rigenerata in zona Forlanini: mostre, concerti, teatro, orti urbani. Progetto di rigenerazione culturale con spirito comunitario.',
 'I concerti estivi nel cortile della cascina sono gratuiti — porta una coperta e siediti sull''erba.',
 '🏡', NULL, 'altro'),

('Spazio Eataly Arte',
 'Piazza XXV Aprile 10',
 'museo', 'low',
 ARRAY['culturale','creativo','foodie','social'],
 'Lo spazio espositivo sopra Eataly Smeraldo: mostre temporanee di arte contemporanea, fotografia, design. Ingresso libero, spesso sottovalutato.',
 'Dopo la mostra scendi da Eataly per un aperitivo — il percorso arte + cibo è perfetto.',
 '🖼️', NULL, 'porta_nuova'),

('Wow Spazio Fumetto',
 'Viale Campania 12',
 'museo', 'low',
 ARRAY['culturale','creativo','alternativo','social'],
 'Museo del fumetto di Milano: mostre su manga, comics, graphic novel, animazione. Libreria specializzata e workshop per aspiranti fumettisti.',
 'Le mostre temporanee di manga giapponesi sono le più popolari — controlla il calendario.',
 '💬', NULL, 'porta_romana'),

('Anteo nel Parco',
 'Parco Sempione',
 'cinema', 'low',
 ARRAY['culturale','rilassato','social','romantico'],
 'Il cinema all''aperto estivo di Anteo nel Parco Sempione: sdraio, coperte, popcorn, film d''autore sotto le stelle. Solo in estate.',
 'Porta la tua coperta e arriva 30 minuti prima per i posti migliori — al centro, fila 4-5.',
 '🌙', NULL, 'sempione'),

('Libreria Cortina',
 'Via Festa del Perdono 2',
 'altro', 'low',
 ARRAY['culturale','rilassato','creativo'],
 'Storica libreria universitaria in zona Statale: testi accademici, saggistica, narrativa. Punto di riferimento per studenti e intellettuali milanesi.',
 'La sezione di saggistica al primo piano è eccellente — chiedi consigli al personale, sono preparatissimi.',
 '📚', NULL, 'centro'),

('Fondazione Luciana Matalon',
 'Foro Buonaparte 67',
 'museo', 'low',
 ARRAY['culturale','creativo','elegante','rilassato'],
 'Fondazione d''arte contemporanea in Sempione: mostre di pittura, scultura, fotografia. Spazio intimo, mostre curate, ingresso spesso gratuito.',
 'Le inaugurazioni del giovedì sera sono aperte a tutti — arte + aperitivo gratis.',
 '🎭', NULL, 'sempione'),

('Mudec Lab',
 'Via Tortona 56',
 'museo', 'mid',
 ARRAY['culturale','creativo','social','avventuroso'],
 'Il laboratorio didattico del Mudec: workshop di arte etnica, ceramica africana, calligrafia giapponese. Esperienze pratiche per adulti e bambini.',
 'I workshop del weekend durano 2 ore e includi materiali — prenota online con anticipo.',
 '🌍', NULL, 'navigli'),

('Fondazione Forma',
 'Piazza Tito Lucrezio Caro 1',
 'museo', 'mid',
 ARRAY['culturale','creativo','elegante'],
 'Centro di fotografia contemporanea: mostre di grandi fotografi internazionali, workshop, masterclass. La fotografia come arte a Milano.',
 'Le mostre durano circa 3 mesi — il biglietto ridotto per under 26 è 5€.',
 '📷', NULL, 'porta_romana'),

('Base Radio',
 'Via Bergognone 34',
 'altro', 'low',
 ARRAY['musicale','creativo','alternativo','social'],
 'La web radio di BASE Milano: DJ set dal vivo, talk, performance sonore. Ascolta in streaming o vai di persona — lo studio è aperto al pubblico.',
 'I DJ set del venerdì pomeriggio sono gratuiti e aperti — l''aperitivo in BASE dopo è d''obbligo.',
 '📻', NULL, 'navigli'),

-- ══════════════════════════════════════════════════════════════
-- LOCALI SERALI — COCKTAIL & WINE (10)
-- ══════════════════════════════════════════════════════════════

('Nuova Era Cocktails',
 'Via Lambro 7',
 'cocktail_bar', 'mid',
 ARRAY['elegante','social','aperitivo','creativo'],
 'Cocktail bar nascosto in NoLo: drink di ricerca ispirati alla cucina, ingredienti fermentati, menù stagionale. Il bartender spiega ogni cocktail.',
 'Il cocktail con miso e yuzu è il signature — sorprendente e bilanciato.',
 '🍸', NULL, 'altro'),

('Vino al Vino',
 'Via Castel Morrone 14',
 'bar', 'mid',
 ARRAY['aperitivo','rilassato','social','foodie'],
 'Enoteca con mescita in Porta Venezia: vini naturali, biodinamici, piccoli produttori. Taglieri di formaggi e salumi abbinati dal sommelier.',
 'Lasciati guidare dal sommelier — digli il tuo umore e ti abbinerà il vino perfetto (è il tema di My Mood!).',
 '🍇', NULL, 'porta_venezia'),

('Balera Cocktail Club',
 'Via Ascanio Sforza 57',
 'cocktail_bar', 'mid',
 ARRAY['social','festivo','musicale','aperitivo'],
 'Cocktail bar con pista da ballo sui Navigli: drink anni ''70-''80, disco, funk, soul. Bevi bene e balli meglio.',
 'Il sabato sera la pista si accende dopo le 23 — arriva per l''aperitivo e resta.',
 '🪩', NULL, 'navigli'),

('Enoteca della Vetra',
 'Via Pio IV 3',
 'bar', 'mid',
 ARRAY['aperitivo','rilassato','vintage','foodie'],
 'Enoteca storica vicino alle Colonne di San Lorenzo: vini italiani al bicchiere, bruschette, formaggi. L''alternativa colta all''aperitivo da bar.',
 'Il bicchiere di Barolo con tagliere di formaggi piemontesi è il modo migliore per chiudere la giornata.',
 '🧀', NULL, 'navigli'),

('Spirito Cocktail Bar',
 'Via Borsieri 28',
 'cocktail_bar', 'mid',
 ARRAY['elegante','social','aperitivo','creativo'],
 'Cocktail bar d''autore in Isola: drink classici rivisitati con twist moderno, garnish elaborate, ghiaccio artigianale. Small ma impeccabile.',
 'L''Old Fashioned con bourbon affumicato è il drink signature — lo affumicano al tavolo.',
 '🥃', NULL, 'isola'),

('Cantina della Vetra',
 'Parco delle Basiliche',
 'bar', 'low',
 ARRAY['social','aperitivo','rilassato','festivo'],
 'Chiosco nel Parco delle Basiliche: birre artigianali, vino, panini. Aperitivo all''aperto nel verde, con vista sulle basiliche illuminate.',
 'D''estate l''aperitivo qui è imbattibile — porta una coperta, siediti sull''erba, e goditi il tramonto.',
 '🌳', NULL, 'navigli'),

('Vinile Wine Bar',
 'Via Clusone 6',
 'bar', 'mid',
 ARRAY['musicale','aperitivo','social','vintage'],
 'Wine bar con vinili: selezione di vini naturali, piatti freddi, musica su giradischi. Ogni sera un genere diverso (jazz, soul, funk).',
 'Il mercoledì è serata jazz con vinili originali — chiedi al proprietario di mettere il tuo album preferito.',
 '🎶', NULL, 'porta_romana'),

('Giardino Nascosto',
 'Via Privata Leida 4',
 'bar', 'mid',
 ARRAY['romantico','rilassato','elegante','aperitivo'],
 'Bar con giardino segreto in zona Città Studi: cocktail botanici, piante ovunque, luci soffuse. L''hideaway più romantico di Milano.',
 'Prenota il tavolo nel giardino interno — è piccolo (8 tavoli) e si riempie subito d''estate.',
 '🌿', NULL, 'altro'),

('Sidecar Milano',
 'Via Borsieri 32',
 'cocktail_bar', 'mid',
 ARRAY['elegante','social','aperitivo','misterioso'],
 'Speakeasy in Isola: porta nascosta, nessuna insegna, drink classici anni ''20. Ambiente intimo, musica jazz in sottofondo, massimo 30 posti.',
 'Cerca la porta senza insegna accanto al barbiere — bussa due volte e chiedi di Marco.',
 '🚪', NULL, 'isola'),

('Manifesto Bar',
 'Via Govone 2',
 'bar', 'mid',
 ARRAY['social','aperitivo','creativo','alternativo'],
 'Bar culturale in zona Cenisio: aperitivo con DJ set, mostre d''arte, presentazioni di libri. L''aperitivo intelligente per chi vuole qualcosa in più.',
 'Il giovedì sera c''è sempre un evento culturale — l''aperitivo è incluso nel prezzo dell''evento (10€).',
 '📰', NULL, 'sempione');
