-- ============================================================
-- MY MOOD — Seed v3 · Batch 5 (100 venue)
-- ============================================================
-- Focus: nightlife (Circle + altri), ristoranti zona sud/ovest,
--        attività indoor, caffè letterari, rooftop, periferie
-- ============================================================
-- Supabase → SQL Editor → incolla tutto → Run
-- ============================================================

INSERT INTO venues (name, address, type, price_range, compatible_moods, description, tips, emoji, website_url, neighborhood)
VALUES

-- ══════════════════════════════════════════════════════════════
-- DISCOTECHE & CLUB (10)
-- ══════════════════════════════════════════════════════════════

('Circle Milano',
 'Via Stendhal 36',
 'club', 'mid',
 ARRAY['nottambulo','social','festivo','musicale','elegante'],
 'Club nel Diesel Building in zona Tortona: soffitto con 8000 lampadine, interni urban-chic, musica dal pop ai classici anni ''90-2000. Lounge, ristorante e discoteca in uno.',
 'Il venerdì e il sabato sono le serate principali — lista consigliata per evitare la coda.',
 '🔵', 'https://circlemilano.com', 'navigli'),

('The Club Milano',
 'Corso Como 10',
 'club', 'high',
 ARRAY['nottambulo','elegante','esclusivo','social','festivo'],
 'Club esclusivo in Corso Como: interni raffinati, DJ internazionali, dress code rigoroso. Serate hip-hop, R&B e house per la Milano che conta.',
 'La lista è essenziale — contatta i PR per il weekend e arriva dopo mezzanotte.',
 '💎', 'https://theclubmilano.com', 'porta_nuova'),

('Amnesia Milano — Giardino',
 'Via Forlanini 65',
 'club', 'mid',
 ARRAY['nottambulo','musicale','social','festivo'],
 'Il giardino estivo dell''Amnesia: DJ set sotto le stelle, area lounge, cocktail bar all''aperto. La versione open-air della nightlife milanese.',
 'D''estate le serate nel giardino sono le migliori — arriva per l''aperitivo e resta.',
 '🌙', NULL, 'altro'),

('Depot Milano',
 'Via Valtorta 5',
 'club', 'mid',
 ARRAY['nottambulo','alternativo','musicale','social'],
 'Club underground in zona NoLo con programmazione elettronica di qualità: techno, house, drum & bass. Impianto Funktion-One, community underground.',
 'Le serate techno del sabato hanno i lineup migliori — segui su RA.',
 '🔊', NULL, 'altro'),

('Loolapaloosa',
 'Piazzale Cantore 12',
 'club', 'mid',
 ARRAY['nottambulo','social','festivo','musicale'],
 'Club-ristorante sui Navigli con giardino estivo: cena con show, poi DJ set fino a tardi. Serate a tema, burlesque, live band.',
 'La formula cena + discoteca è la migliore — mangi bene, poi non devi cambiare locale.',
 '🎭', NULL, 'navigli'),

('Le Banque',
 'Via Bassano Porrone 6',
 'club', 'high',
 ARRAY['nottambulo','elegante','esclusivo','festivo','social'],
 'Club in un''ex banca del centro: colonne, cassaforte, soffitti altissimi. Serate fashion, aperitivi esclusivi, dress code elegante obbligatorio.',
 'L''aperitivo di giovedì sera è il modo più accessibile per scoprire lo spazio — meno caro del weekend.',
 '🏦', NULL, 'centro'),

('Bobino Club',
 'Piazzale Stazione Genova 4',
 'club', 'mid',
 ARRAY['nottambulo','social','festivo','musicale','rilassato'],
 'Club nella storica Stazione di Porta Genova: loft industriale, aperitivo, cena, poi DJ set. Atmosfera che va dal rilassato al festaiolo, musica house e funk.',
 'Il nuovo spazio nella stazione è ancora più grande — arriva per l''aperitivo e resta.',
 '🌊', NULL, 'navigli'),

('Mono Milano',
 'Via Lecco 6',
 'club', 'mid',
 ARRAY['nottambulo','alternativo','musicale','misterioso'],
 'Club intimo in Porta Venezia dedicato alla musica elettronica underground: techno, house, ambient. Atmosfera dark, sound system potente, community affiatata.',
 'Le serate del venerdì hanno i guest più interessanti — biglietto in prevendita su RA.',
 '⚡', NULL, 'porta_venezia'),

('Straf Bar',
 'Via San Raffaele 3',
 'bar', 'mid',
 ARRAY['social','elegante','aperitivo','nottambulo'],
 'Il bar dell''hotel Straf a due passi dal Duomo: cocktail d''autore, design contemporaneo, musica selezionata. L''aperitivo chic del centro.',
 'Il Negroni dello Straf è tra i migliori del centro — perfetto prima di cena.',
 '🍸', NULL, 'centro'),

('Spirit de Milan — Giardino',
 'Via Bovisasca 59',
 'bar', 'mid',
 ARRAY['social','festivo','musicale','vintage','rilassato'],
 'Il giardino estivo dello Spirit de Milan: cena all''aperto, swing, liscio, DJ set sotto le stelle. La balera milanese in versione open-air.',
 'Le serate swing nel giardino d''estate sono imperdibili — prenota il tavolo fuori.',
 '💃', NULL, 'altro'),

-- ══════════════════════════════════════════════════════════════
-- RISTORANTI — CUCINA ITALIANA REGIONALE (10)
-- ══════════════════════════════════════════════════════════════

('Trattoria la Brisa',
 'Via Brisa 15',
 'trattoria', 'mid',
 ARRAY['foodie','romantico','rilassato','vintage'],
 'Trattoria con giardino nascosto tra i resti romani del centro: cucina lombarda rivisitata, atmosfera intima, candele la sera. Un segreto.',
 'D''estate il giardino tra le rovine romane è unico — prenota specificando "tavolo fuori".',
 '🏛️', NULL, 'centro'),

('Da Martino',
 'Via Anfossi 6',
 'trattoria', 'low',
 ARRAY['foodie','godereccio','vintage','rilassato','social'],
 'Trattoria di quartiere in Porta Romana: primi abbondanti, secondi della tradizione, vino della casa, prezzi onesti. Il pranzo come una volta.',
 'Il risotto alla milanese del mercoledì è il piatto da non perdere — arriva presto.',
 '🍲', NULL, 'porta_romana'),

('Osteria alla Concorrenza',
 'Via Orefici 17',
 'trattoria', 'mid',
 ARRAY['foodie','vintage','rilassato','social'],
 'Osteria storica nascosta dietro il Duomo: cucina lombarda senza fronzoli, ambiente rustico, frequentata dai milanesi doc. Zero turisti.',
 'I nervetti in insalata e il vitello tonnato sono gli antipasti classici — ordinali entrambi.',
 '🫒', NULL, 'centro'),

('Trattoria Sabbioneda',
 'Via Sabbioneta 3',
 'trattoria', 'mid',
 ARRAY['foodie','godereccio','vintage','rilassato'],
 'Trattoria di quartiere con cucina mantovana-milanese: tortelli di zucca, risotto, cotechino. Il tipo di posto dove il cameriere ti consiglia come un amico.',
 'I tortelli di zucca sono il piatto signature — delicati e perfetti.',
 '🎃', NULL, 'altro'),

('Masuelli San Marco',
 'Viale Umbria 80',
 'trattoria', 'mid',
 ARRAY['foodie','godereccio','vintage','social'],
 'Trattoria storica dal 1921: piemontese-milanese, carrello dei bolliti, vitello tonnato, fritto misto. La cucina delle nonne, fatta come si deve.',
 'Il carrello dei bolliti con le salse è lo spettacolo — lasciati consigliare dal cameriere sui tagli.',
 '🥩', NULL, 'porta_romana'),

('Osteria Brunello',
 'Via Solferino 37',
 'ristorante', 'mid',
 ARRAY['foodie','social','elegante','godereccio'],
 'Cucina toscana nel cuore di Brera: fiorentina, pappa al pomodoro, ribollita, vini toscani. La Toscana a Milano, senza pretese inutili.',
 'La fiorentina per due è il piatto da condividere — accompagna con un Chianti Classico.',
 '🐂', NULL, 'brera'),

('Sartoria Panatoni',
 'Via Niccolò Jommelli 13',
 'pizzeria', 'mid',
 ARRAY['foodie','godereccio','social','creativo'],
 'Pizzeria con impasto a lunga lievitazione e ingredienti campani premium: pizza fritta, montanara, classiche. Il napoletano a Città Studi.',
 'La montanara e la frittatina sono gli antipasti irresistibili — poi ordina la Margherita DOC.',
 '🍕', NULL, 'altro'),

('Al Vecchio Porco',
 'Via Valenza 5',
 'trattoria', 'low',
 ARRAY['foodie','godereccio','social','rilassato','vintage'],
 'Salumeria-trattoria con taglieri monumentali e piatti della tradizione emiliana: mortadella, culatello, tigelle, gnocco fritto. Il paradiso del salume.',
 'Il tagliere misto con tigelle calde e gnocco fritto è il piatto che devi ordinare — punto.',
 '🐷', NULL, 'navigli'),

('Nebbia',
 'Via Ravizza 8',
 'ristorante', 'mid',
 ARRAY['foodie','creativo','rilassato','social'],
 'Cucina lombarda contemporanea: ingredienti locali, piatti stagionali, presentazione moderna. Un ristorante di quartiere che punta alla qualità senza urlare.',
 'Il menu degustazione da 4 portate è il modo migliore per scoprire la cucina dello chef.',
 '🌫️', NULL, 'altro'),

('Tano Passami l''Olio',
 'Via Francesco Petrarca 4',
 'ristorante', 'high',
 ARRAY['foodie','elegante','creativo','romantico'],
 'Ristorante dello chef Gaetano Simonato: ogni piatto è costruito intorno a un olio extravergine diverso. Cucina italiana innovativa, stellato Michelin.',
 'Lascia scegliere al sommelier dell''olio — l''abbinamento olio-piatto è il cuore dell''esperienza.',
 '🫒', NULL, 'sempione'),

-- ══════════════════════════════════════════════════════════════
-- ROOFTOP & TERRAZZE (7)
-- ══════════════════════════════════════════════════════════════

('Terrazza Gallia',
 'Via Pirelli 20',
 'rooftop', 'high',
 ARRAY['elegante','romantico','aperitivo','social','esclusivo'],
 'Rooftop dell''Excelsior Hotel Gallia: vista sulla Stazione Centrale e sullo skyline, cocktail d''autore, finger food. Lusso discreto sopra i tetti.',
 'Al tramonto il panorama è spettacolare — prenota un tavolo esterno con vista.',
 '🌆', 'https://excelsiorhotelgallia.com', 'altro'),

('Terrazza 12',
 'Via Borsieri 12',
 'rooftop', 'mid',
 ARRAY['social','aperitivo','rilassato','elegante'],
 'Rooftop bar a Isola con vista sullo skyline di Porta Nuova: cocktail, taglieri, musica soft. Perfetto per aperitivi con vista senza spendere una fortuna.',
 'Vai al tramonto — la vista sui grattacieli illuminati è da cartolina.',
 '🌅', NULL, 'isola'),

('Rooftop Manzoni',
 'Via Manzoni 31',
 'rooftop', 'high',
 ARRAY['elegante','romantico','esclusivo','aperitivo'],
 'Terrazza dell''hotel in via Manzoni: vista sul quadrilatero della moda, cocktail classici, atmosfera sofisticata. Il Milano bene al suo meglio.',
 'Il Negroni qui è fatto con gin premium — accompagnalo con le olive siciliane.',
 '🍸', NULL, 'centro'),

('The Roof Milano',
 'Via Mazzini 8',
 'rooftop', 'mid',
 ARRAY['social','aperitivo','elegante','romantico'],
 'Terrazza panoramica in centro con vista a 360° su Milano: Duomo, Velasca, grattacieli. Cocktail curati in un setting da film.',
 'Chiedi il tavolo lato Duomo — è la vista migliore, soprattutto di sera con le luci.',
 '🏙️', NULL, 'centro'),

('Ceresio 7 Pools & Restaurant',
 'Via Ceresio 7',
 'rooftop', 'high',
 ARRAY['elegante','social','aperitivo','esclusivo','rilassato'],
 'Il celebre rooftop con due piscine affacciate sullo skyline: aperitivo, cena, pool party estivi. L''icona del rooftop milanese.',
 'La piscina è riservata ai soci del club — ma il ristorante e il bar sono aperti a tutti.',
 '🏊', 'https://ceresio7.com', 'porta_nuova'),

('Mare Culturale Urbano',
 'Via Giuseppe Gabetti 15',
 'bar', 'low',
 ARRAY['social','culturale','alternativo','rilassato','creativo'],
 'Cascina rigenerata in periferia con giardino, bar, cinema all''aperto, concerti. D''estate è un festival permanente: cultura, cibo e socialità.',
 'D''estate il cinema all''aperto nel giardino è un''esperienza magica — porta la coperta.',
 '🎬', 'https://maremilano.org', 'altro'),

('Terrazza Martini',
 'Piazza Armando Diaz 7',
 'rooftop', 'high',
 ARRAY['elegante','esclusivo','social','aperitivo'],
 'La storica terrazza Martini al 15° piano: vista mozzafiato sul Duomo, cocktail Martini perfetti, atmosfera da vecchia Milano elegante. Solo su invito o eventi.',
 'Controlla il calendario eventi — alcune serate sono aperte al pubblico con prenotazione.',
 '🍸', NULL, 'centro'),

-- ══════════════════════════════════════════════════════════════
-- RISTORANTI PESCE & MARE (7)
-- ══════════════════════════════════════════════════════════════

('Langosteria Café',
 'Via Savona 10',
 'ristorante', 'mid',
 ARRAY['foodie','social','rilassato','elegante'],
 'Il café della famiglia Langosteria: pesce in versione casual, crudi, insalate di mare, cocktail. La qualità Langosteria in formato accessibile.',
 'Il plateau di crudi è il piatto da cui partire — freschezza garantita come nelle sedi principali.',
 '🦪', 'https://langosteria.com', 'navigli'),

('The Fisherman Pasta',
 'Via Vigevano 9',
 'ristorante', 'mid',
 ARRAY['foodie','social','rilassato','godereccio'],
 'Pasta fresca fatta a mano con pesce: spaghetti alle vongole, paccheri allo scoglio, linguine all''astice. Solo pesce fresco, solo pasta fresca, sempre.',
 'Gli spaghetti alle vongole veraci sono il piatto da ordinare — semplici e perfetti.',
 '🍝', 'https://thefisherman.it', 'navigli'),

('Al Porto',
 'Piazzale Generale Cantore 9',
 'ristorante', 'mid',
 ARRAY['foodie','elegante','romantico','social'],
 'Ristorante di pesce storico sui Navigli dal 1907: crudità, pasta con frutti di mare, grigliata. Classico, affidabile, con più di un secolo di storia.',
 'Lo spaghetto allo scoglio e la grigliata mista sono i cavalli di battaglia — non sbagliare.',
 '⚓', NULL, 'navigli'),

('Trattoria del Pesce',
 'Via Atto Vannucci 5',
 'trattoria', 'mid',
 ARRAY['foodie','godereccio','rilassato','social'],
 'Trattoria di pesce fresco: il pesce arriva ogni mattina, il menu cambia di conseguenza. Zero fronzoli, tanta sostanza, porzioni generose.',
 'Chiedi cosa è arrivato oggi — il pesce del giorno è sempre la scelta migliore.',
 '🐠', NULL, 'porta_romana'),

('Sarti Mercato del Pesce',
 'Via Romagnosi 3',
 'ristorante', 'high',
 ARRAY['foodie','elegante','social','godereccio'],
 'Pescheria con ristorante annesso: compri il pesce fresco e te lo cucinano al momento, oppure scegli dal menu. Il mare nel centro di Milano.',
 'Il banco crudi al pianterreno è perfetto per un pranzo veloce ma di altissima qualità.',
 '🦐', NULL, 'brera'),

('Chiosco Mentana',
 'Largo Donegani 1',
 'ristorante', 'mid',
 ARRAY['rilassato','social','aperitivo','foodie'],
 'Chiosco gourmet in piazzetta: crudi di pesce, ceviche, tartare, cocktail. Atmosfera casual ma qualità alta, perfetto per aperitivi di pesce.',
 'Il ceviche del giorno con un cocktail al frutto della passione è la combo estiva perfetta.',
 '🍤', NULL, 'brera'),

('Osteria del Mare',
 'Via Savona 50',
 'ristorante', 'mid',
 ARRAY['foodie','godereccio','social','rilassato'],
 'Cucina di mare pugliese a Milano: ricci, cozze, orecchiette ai frutti di mare, frittura. Sapori del sud con il pesce del giorno.',
 'La frittura mista di paranza è il piatto signature — croccante e leggera.',
 '🌊', NULL, 'navigli'),

-- ══════════════════════════════════════════════════════════════
-- ATTIVITA & ESPERIENZE (10)
-- ══════════════════════════════════════════════════════════════

('The Sign Room — Escape Room',
 'Via Cardano 3',
 'attivita', 'mid',
 ARRAY['avventuroso','social','misterioso','creativo'],
 'Escape room con stanze ad alta immersione: scenografie teatrali, enigmi elaborati, trame avvincenti. Tra le più votate di Milano.',
 'La stanza "Il Conte" è la più difficile e la più bella — prenotala se vuoi la sfida vera.',
 '🔐', NULL, 'altro'),

('Fico Climbing',
 'Via Segantini 79',
 'attivita', 'mid',
 ARRAY['sportivo','social','avventuroso','zen'],
 'Palestra di boulder con pareti rinnovate ogni mese: problemi per tutti i livelli, area training, community attiva. Lo sport social per eccellenza.',
 'Il mercoledì sera c''è l''open session — perfetto per conoscere gente e fare boulder insieme.',
 '🧗', NULL, 'navigli'),

('Trampoline Park Jump World',
 'Via Mecenate 76',
 'attivita', 'mid',
 ARRAY['sportivo','social','festivo','avventuroso'],
 'Parco trampolini con aree freestyle, dodgeball, foam pit e ninja course. Divertimento puro per gruppi, compleanni, o semplicemente per scaricare energia.',
 'La sessione serale del venerdì ha musica e luci UV — bounce party per adulti.',
 '🤸', NULL, 'altro'),

('Combat Arena — Bubble Football',
 'Via Ripamonti 89',
 'attivita', 'mid',
 ARRAY['sportivo','social','festivo','avventuroso'],
 'Bubble football, archery tag e combat sports in arena dedicata. Perfetto per addii al celibato, team building o semplicemente ridere come pazzi.',
 'Il bubble football per 10 persone è l''esperienza più divertente — prenota per 1 ora.',
 '⚽', NULL, 'altro'),

('Milano Kart Indoor',
 'Via G.B. Grasselli 7',
 'attivita', 'mid',
 ARRAY['avventuroso','social','sportivo','festivo'],
 'Pista di go-kart indoor con kart elettrici: giri cronometrati, gare con amici, classifiche. Adrenalina pura al coperto, tutto l''anno.',
 'Prenota la sessione "gara" per 8+ persone — con qualifiche, griglia di partenza e podio finale.',
 '🏎️', NULL, 'altro'),

('Stadio Giuseppe Meazza — Tour',
 'Piazzale Angelo Moratti',
 'attivita', 'mid',
 ARRAY['sportivo','culturale','social','avventuroso'],
 'Tour guidato di San Siro: spogliatoi, tunnel, panchine, museo Inter & Milan. Per tifosi e non, uno dei templi del calcio mondiale.',
 'Il tour con accesso al campo è l''opzione migliore — cammini dove hanno giocato le leggende.',
 '🏟️', NULL, 'altro'),

('Terme QC Porta Romana',
 'Piazzale Medaglie d''Oro 2',
 'attivita', 'high',
 ARRAY['zen','rilassato','romantico','esclusivo'],
 'Il nuovo complesso termale QC in Porta Romana: piscine, saune, percorso spa, ristorante. Il wellness di lusso nel cuore della città.',
 'Il percorso serale con aperitivo è l''esperienza più completa — relax totale.',
 '♨️', NULL, 'porta_romana'),

('Milano Padel Arena',
 'Via Fantoli 7',
 'attivita', 'mid',
 ARRAY['sportivo','social','rilassato'],
 'Centro padel con 8 campi coperti: prenotazione online, lezioni per principianti, tornei sociali. Lo sport del momento, facile da provare.',
 'La lezione di prova per principianti è il modo migliore per iniziare — porta solo le scarpe.',
 '🎾', NULL, 'altro'),

('Museo Teatrale alla Scala',
 'Largo Antonio Ghiringhelli 1',
 'museo', 'mid',
 ARRAY['culturale','elegante','vintage'],
 'Il museo della Scala: costumi, spartiti, strumenti, ritratti di Verdi e Toscanini. Si sbircia anche dentro il teatro dalla sala del museo.',
 'La vista sulla sala del teatro dal museo è emozionante — sosta davanti alla finestra.',
 '🎼', NULL, 'centro'),

('Centro Balneare Romano',
 'Via Ponzio 28',
 'attivita', 'low',
 ARRAY['sportivo','rilassato','social','zen'],
 'Piscina pubblica scoperta con architettura degli anni ''30: vasche olimpioniche, giardino, solarium. D''estate è la spiaggia di Città Studi.',
 'Arriva la mattina presto d''estate — dopo le 11 è pieno. Porta il pranzo e stai tutto il giorno.',
 '🏊', NULL, 'altro'),

-- ══════════════════════════════════════════════════════════════
-- RISTORANTI ETNICI — ROUND 2 (10)
-- ══════════════════════════════════════════════════════════════

('Coa Asian Food & Drinks',
 'Via Vigevano 27',
 'ristorante', 'mid',
 ARRAY['foodie','social','avventuroso'],
 'Street food asiatico: bao bun, noodle, curry, spring roll. Piatti veloci, sapori intensi, porzioni da condividere. L''Asia pop a Milano.',
 'I bao bun con pork belly sono il piatto più venduto — aggiungi i gyoza fritti.',
 '🥟', NULL, 'navigli'),

('Shiro Poporoya',
 'Via Eustachi 17',
 'ristorante', 'mid',
 ARRAY['foodie','zen','elegante','romantico'],
 'Sushi bar autentico con lo chef giapponese al bancone: omakase, nigiri, sashimi. Pochi posti, pesce freschissimo, esperienza zen.',
 'L''omakase è l''unica scelta giusta — siediti al bancone e lascia fare allo chef.',
 '🍣', NULL, 'porta_venezia'),

('Kawa Sushi',
 'Via Lecco 4',
 'ristorante', 'mid',
 ARRAY['foodie','social','rilassato'],
 'Sushi di quartiere con qualità sopra la media: roll creativi, sashimi fresco, piatti caldi giapponesi. Il rapporto qualità-prezzo migliore della zona.',
 'Il chirashi bowl è il piatto da provare — generoso e colorato.',
 '🐟', NULL, 'porta_venezia'),

('Charcoal BBQ Coreano',
 'Via Maiocchi 11',
 'ristorante', 'mid',
 ARRAY['foodie','social','avventuroso','godereccio','festivo'],
 'Korean BBQ con griglia a carbone al tavolo: wagyu, manzo marinato, pancetta, banchan. Cucini tu, mangi con le mani, ti diverti.',
 'Prendi il set "All You Can Eat" per il tavolo — assaggi tutto e spendi il giusto.',
 '🔥', NULL, 'porta_venezia'),

('Dim Sum Gallery',
 'Via Castaldi 24',
 'ristorante', 'mid',
 ARRAY['foodie','social','elegante','creativo'],
 'Dim sum contemporaneo: ravioli al vapore con ripieni creativi, presentazione curata, tè cinesi pregiati. Il dim sum come forma d''arte.',
 'Il carrello dei dim sum la domenica a pranzo è l''esperienza completa — arriva alle 12.',
 '🫕', NULL, 'porta_venezia'),

('Tandoori Nights',
 'Via Melchiorre Gioia 73',
 'ristorante', 'mid',
 ARRAY['foodie','avventuroso','social','godereccio'],
 'Cucina indiana del nord: tandoori chicken, biryani, naan al formaggio, curry di agnello. Porzioni abbondanti, spezie autentiche, atmosfera calda.',
 'Il thali vegetariano è perfetto se vuoi assaggiare un po'' di tutto — completo e saporito.',
 '🍛', NULL, 'porta_nuova'),

('El Carnicero',
 'Via Melzo 16',
 'ristorante', 'mid',
 ARRAY['foodie','social','godereccio','festivo'],
 'Steakhouse argentina: empanadas, asado, chimichurri, dulce de leche. La carne sudamericana a Milano, con le porzioni all''argentina.',
 'L''asado misto per due con empanadas è il piatto per la prima visita — non guardare le calorie.',
 '🥩', NULL, 'porta_venezia'),

('Yan Fish',
 'Via Padova 2',
 'ristorante', 'low',
 ARRAY['foodie','avventuroso','social'],
 'Pesce fritto cinese in stile street food: gamberi croccanti, calamari fritti, riso saltato. Veloce, economico, autenticamente buono.',
 'Il fritto misto con riso bianco è la combo più soddisfacente — e costa pochissimo.',
 '🍤', NULL, 'altro'),

('Burgez Porta Nuova',
 'Viale della Liberazione 15',
 'ristorante', 'mid',
 ARRAY['godereccio','social','rilassato','festivo'],
 'Hamburger gourmet con carne selezionata e panini brioche: smash burger, bacon deluxe, cheese lover. Il fast food fatto bene.',
 'Lo smash burger doppio con bacon e cheddar è il piatto da ordinare — messy ma perfetto.',
 '🍔', NULL, 'porta_nuova'),

('Churrasco Paulista',
 'Via Washington 70',
 'ristorante', 'mid',
 ARRAY['foodie','social','godereccio','festivo'],
 'Churrascaria brasiliana con rodízio: camerieri con spiedoni di carne passano al tavolo, tu dici basta quando non ce la fai più. All you can eat di carne.',
 'Parti leggero con il buffet — tieni spazio per la picanha e il cuore di filetto.',
 '🇧🇷', NULL, 'sempione'),

-- ══════════════════════════════════════════════════════════════
-- CAFFETTERIE & COLAZIONI (8)
-- ══════════════════════════════════════════════════════════════

('Taglio Caffè',
 'Via Vigevano 10',
 'bar', 'mid',
 ARRAY['coffee_lover','rilassato','creativo','foodie'],
 'Specialty coffee con torrefazione propria e brunch curato: filtro, espresso, cappuccino con latte art. Il caffè come artigianato.',
 'Il flat white con il loro blend è il miglior caffè dei Navigli — provalo al bancone.',
 '☕', NULL, 'navigli'),

('Cafezal',
 'Via Lecco 14',
 'bar', 'mid',
 ARRAY['coffee_lover','rilassato','zen','creativo'],
 'Micro-roastery brasiliana: caffè di singola origine tostato in loco, metodi alternativi, dolci brasiliani. Il caffè come esperienza sensoriale.',
 'Il V60 con il caffè del Brasile è il modo migliore per capire lo specialty coffee.',
 '🫘', NULL, 'porta_venezia'),

('Pave Navigli',
 'Ripa di Porta Ticinese 55',
 'bar', 'mid',
 ARRAY['coffee_lover','foodie','godereccio','rilassato'],
 'La sede Navigli della celebre pasticceria: cornetti sfogliati, lievitati, caffè. La colazione milanese al suo meglio, in un quartiere vivace.',
 'Il cornetto al cioccolato fondente appena sfornato è il motivo per svegliarsi — arriva alle 8.',
 '🥐', NULL, 'navigli'),

('Aroma Caffè',
 'Via Napo Torriani 21',
 'bar', 'low',
 ARRAY['coffee_lover','rilassato','zen'],
 'Caffetteria di quartiere vicino alla Stazione Centrale: espresso perfetto, brioche burro e marmellata, atmosfera tranquilla. La pausa che serve.',
 'Il caffè al bancone è il rituale milanese — veloce, buono, e si riparte.',
 '☕', NULL, 'altro'),

('Vesta Coffee Roasters',
 'Via Tortona 20',
 'bar', 'mid',
 ARRAY['coffee_lover','creativo','rilassato','zen'],
 'Torrefazione specialty con café annesso: caffè da tutto il mondo, brewing methods multipli, workshop. Per chi vuole capire il caffè, non solo berlo.',
 'Chiedi la degustazione di 3 caffè — capisci le differenze tra origini in un sorso.',
 '🔥', NULL, 'navigli'),

('Lollo''s Coffee',
 'Via Anfossi 10',
 'bar', 'low',
 ARRAY['coffee_lover','rilassato','social'],
 'Caffetteria con brunch americano: pancake, uova, avocado toast, smoothie. Il brunch classico fatto con cura, porzioni generose.',
 'I pancake con sciroppo d''acero e frutti di bosco sono il piatto da ordinare il sabato.',
 '🥞', NULL, 'porta_romana'),

('Biancolatte',
 'Via Turati 30',
 'bar', 'mid',
 ARRAY['coffee_lover','elegante','rilassato','social'],
 'Caffè-ristorante tutto bianco in zona Turati: colazione, pranzo, aperitivo. Interior design minimalista, menu light, atmosfera curata.',
 'La colazione con cappuccino e torta della casa è il modo più elegante per iniziare la giornata.',
 '🥛', NULL, 'porta_nuova'),

('Emporio Brera Coffee',
 'Via Fiori Chiari 8',
 'bar', 'mid',
 ARRAY['coffee_lover','rilassato','elegante','vintage'],
 'Caffetteria nel cuore di Brera con tavolini nella via pedonale: espresso, cappuccino, dolci. Guardare la gente passare con un caffè in mano.',
 'Il tavolino fuori la mattina presto, prima che Brera si svegli — pace assoluta.',
 '☕', NULL, 'brera'),

-- ══════════════════════════════════════════════════════════════
-- PARCHI & NATURA (5)
-- ══════════════════════════════════════════════════════════════

('Orto Botanico di Brera',
 'Via Brera 28',
 'parco', 'low',
 ARRAY['zen','culturale','rilassato','romantico'],
 'Giardino botanico nascosto dentro il Palazzo di Brera: alberi secolari, aiuole curate, silenzio assoluto. Un''oasi segreta nel centro della città.',
 'Aperto solo in settimana di solito — controlla gli orari. Perfetto per una pausa meditativa.',
 '🌿', NULL, 'brera'),

('Parco delle Cave',
 'Via Fratelli Zoia',
 'parco', 'low',
 ARRAY['rilassato','zen','sportivo','social'],
 'Parco enorme in zona ovest con laghetti, sentieri, aree picnic, campi sportivi. Meno conosciuto di Sempione ma enormemente più spazioso.',
 'Il percorso running intorno ai laghi è di circa 7 km — perfetto per la corsa lunga.',
 '🏞️', NULL, 'altro'),

('Parco Lambro',
 'Via Feltre',
 'parco', 'low',
 ARRAY['rilassato','zen','sportivo','social'],
 'Il secondo parco più grande di Milano: colline, torrente, aree barbecue, percorsi ciclabili. Perfetto per gite fuori porta senza uscire dalla città.',
 'D''estate le aree barbecue sono molto richieste — arriva presto il sabato mattina.',
 '🌳', NULL, 'altro'),

('Giardino della Guastalla',
 'Via Francesco Sforza 28',
 'parco', 'low',
 ARRAY['zen','rilassato','romantico','culturale'],
 'Il giardino più antico di Milano (1555): vasca con pesci, statue barocche, panchine nascoste. Un angolo di pace rinascimentale vicino all''Università Statale.',
 'La panchina vicino alla vasca dei pesci rossi è il posto più tranquillo del centro.',
 '🐟', NULL, 'centro'),

('Bosco Verticale — Passeggiata',
 'Via Gaetano de Castillia',
 'parco', 'low',
 ARRAY['culturale','rilassato','zen','creativo'],
 'Passeggiata intorno ai celebri grattacieli-foresta di Stefano Boeri: architettura iconica, piante tropicali ai balconi, foto perfette.',
 'Il punto foto migliore è dall''angolo con via De Castillia — inquadri entrambe le torri.',
 '🌲', NULL, 'porta_nuova'),

-- ══════════════════════════════════════════════════════════════
-- COCKTAIL BAR & SPEAKEASY (8)
-- ══════════════════════════════════════════════════════════════

('Killer Ristorante',
 'Viale Umbria 120',
 'ristorante', 'mid',
 ARRAY['social','creativo','foodie','nottambulo'],
 'Ristorante nello storico spazio dell''ex Plastic: show cooking, sala rosa, cocktail bar. Cucina creativa in un luogo iconico della nightlife milanese.',
 'La sala "Pollaio" al piano superiore è la più intima — prenota lì per cena.',
 '🔪', NULL, 'porta_romana'),

('MAG La Pusterla',
 'Via Cesare Correnti 21',
 'cocktail_bar', 'mid',
 ARRAY['misterioso','elegante','romantico','social','alternativo'],
 'Bar con anima: cocktail d''autore in un palazzo storico, atmosfera tra speakeasy e salotto. Ospita il leggendario 1930 secret bar nel seminterrato.',
 'Chiedi del 1930 al piano di sotto — è lo speakeasy nascosto più famoso di Milano.',
 '📚', NULL, 'navigli'),

('The Spirit',
 'Via Boscovich 36',
 'cocktail_bar', 'mid',
 ARRAY['social','elegante','rilassato','aperitivo'],
 'Cocktail bar con oltre 500 etichette di spirits: rum, whisky, gin, mezcal. Ogni drink è un viaggio, ogni bottiglia ha una storia da raccontare.',
 'Chiedi il cocktail su misura — digli cosa ti piace e il barman crea qualcosa di unico.',
 '🥃', NULL, 'porta_venezia'),

('Rebelot',
 'Ripa di Porta Ticinese 55',
 'cocktail_bar', 'mid',
 ARRAY['alternativo','social','rilassato','aperitivo','foodie'],
 'Bistrot e cocktail bar sui Navigli, figlio del Pont de Ferr: tapas creative, drink artigianali, atmosfera da osteria moderna. Cucina e mixology insieme.',
 'Le tapas da condividere con un cocktail sono la formula perfetta — ordina 3-4 per il tavolo.',
 '🧪', NULL, 'navigli'),

('Mag Moustache',
 'Via Corsico 3',
 'cocktail_bar', 'low',
 ARRAY['alternativo','social','rilassato','aperitivo','creativo'],
 'Bar indipendente sui Navigli con cocktail a prezzi onesti, serate culturali, jam session. L''alternativa ai locali turistici della zona.',
 'Il gin tonic con botaniche fresche è il best-seller — accompagna con le bruschette.',
 '🥸', NULL, 'navigli'),

('Pinch — Spirits & Kitchen',
 'Ripa di Porta Ticinese 63',
 'cocktail_bar', 'mid',
 ARRAY['social','elegante','foodie','aperitivo'],
 'Cocktail bar con cucina: drink d''autore abbinati a piatti fusion. La formula aperitivo-cena in un unico locale raffinato sui Navigli.',
 'Il pairing cocktail + piatto è il modo migliore per vivere il locale — chiedi al barman.',
 '🍸', NULL, 'navigli'),

('Drinc. Mixology',
 'Via Plinio 32',
 'cocktail_bar', 'mid',
 ARRAY['elegante','misterioso','social','rilassato'],
 'Cocktail bar minimalista: pochi posti, menu stagionale, ingredienti freschi. Ogni drink è pensato come un piatto, con equilibrio e tecnica impeccabili.',
 'Il menu cambia ogni stagione — chiedi qual è la novità e lasciati sorprendere.',
 '🫧', NULL, 'porta_venezia'),

-- ══════════════════════════════════════════════════════════════
-- LOCALI SERALI & LIVE MUSIC — ROUND 2 (5)
-- ══════════════════════════════════════════════════════════════

('Garage Italia',
 'Piazzale Accursio 1',
 'bar', 'mid',
 ARRAY['creativo','elegante','social','aperitivo'],
 'Ex stazione di servizio Agip trasformata da Lapo Elkann: design iconico, cocktail curati, eventi. Il bar più instagrammabile di Milano.',
 'L''aperitivo nel dehor con la vecchia pompa di benzina illuminata è l''inquadratura perfetta.',
 '⛽', NULL, 'altro'),

('Teatro del Buratto',
 'Via Giovanni Bovio 5',
 'teatro', 'low',
 ARRAY['culturale','creativo','social'],
 'Teatro dedicato al teatro ragazzi e al contemporaneo: marionette, clown, performance. Programmazione intelligente per tutte le età.',
 'Gli spettacoli per adulti del venerdì sera sono spesso i più sorprendenti.',
 '🤡', NULL, 'altro'),

('Salumeria della Musica Live',
 'Via Antonio Pasinetti 4',
 'bar', 'mid',
 ARRAY['musicale','social','rilassato','vintage'],
 'Locale con palco per concerti live quasi ogni sera: jazz, blues, cantautorato, world music. Cucina da salumeria, vini naturali, atmosfera intima.',
 'Il concerto del giovedì sera è spesso il più intimo — arriva presto e prendi il tavolo davanti.',
 '🎵', NULL, 'altro'),

('Brellin',
 'Vicolo dei Lavandai 1',
 'bar', 'mid',
 ARRAY['social','vintage','rilassato','aperitivo','romantico'],
 'Bar-ristorante nel vicolo dei Lavandai, il lavatoio storico dei Navigli: tavolini sull''acqua, atmosfera d''altri tempi, aperitivo romantico.',
 'Il tavolo affacciato sui lavatoi è il più suggestivo della zona — prenota per l''aperitivo.',
 '🧺', NULL, 'navigli'),

('Biko Giardino',
 'Viale d''Annunzio 7',
 'bar', 'low',
 ARRAY['musicale','rilassato','social','alternativo','zen'],
 'Il giardino del Biko: concerti acustici, DJ set ambient, chiacchierate sotto gli alberi. La versione estiva e rilassata del club.',
 'D''estate il giardino con le lucine è magico — porta la felpa per la sera.',
 '🌿', NULL, 'navigli'),

-- ══════════════════════════════════════════════════════════════
-- GELATERIE & DOLCI — ROUND 2 (5)
-- ══════════════════════════════════════════════════════════════

('Gelato Bianco',
 'Via Turati 11',
 'altro', 'mid',
 ARRAY['godereccio','rilassato','elegante'],
 'Gelateria d''autore con gusti stagionali e ingredienti ricercati: pistacchio di Bronte, cioccolato monorigine, sorbetti di frutta fresca.',
 'Il gusto nocciola Piemonte e il sorbetto al mango sono i due da provare sempre.',
 '🍨', NULL, 'porta_nuova'),

('Crema',
 'Via Luigi Porro Lambertenghi 15',
 'altro', 'mid',
 ARRAY['godereccio','coffee_lover','rilassato','social'],
 'Gelateria-pasticceria con laboratorio a vista: gelato, semifreddi, croissant ripieni, torte. Tutto fatto in casa con ingredienti premium.',
 'Il croissant ripieno di crema al pistacchio è il motivo per cui la gente fa la coda.',
 '🥐', NULL, 'isola'),

('Hakuna Matata Gelato',
 'Via Spontini 14',
 'altro', 'low',
 ARRAY['godereccio','rilassato','social'],
 'Gelateria di quartiere a Città Studi: gelato artigianale fatto ogni giorno, gusti classici eseguiti perfettamente, prezzi onesti.',
 'Il fiordilatte è il test della gelateria — qui è puro e cremoso come deve essere.',
 '🍦', NULL, 'altro'),

('Belle Hélène',
 'Via Vincenzo Monti 55',
 'altro', 'mid',
 ARRAY['godereccio','elegante','foodie','coffee_lover'],
 'Pasticceria francese con macarons, éclairs, mille-feuille, croissant au beurre. La Francia in zona Cadorna, raffinata e golosa.',
 'I macarons al passion fruit e i Paris-Brest sono i pezzi forti — portane via una scatola.',
 '🇫🇷', NULL, 'sempione'),

('Cioccolat Italiani Navigli',
 'Ripa di Porta Ticinese 1',
 'altro', 'low',
 ARRAY['godereccio','social','rilassato'],
 'Gelato con fontana di cioccolato fuso, cono personalizzabile, crepes e churros. Goloso, divertente, perfetto per il passeggio sui Navigli.',
 'Il cono con granella e cioccolato fondente fuso è il più venduto — non resisterai.',
 '🍫', NULL, 'navigli'),

-- ══════════════════════════════════════════════════════════════
-- RISTORANTI — HAMBURGER & COMFORT FOOD (5)
-- ══════════════════════════════════════════════════════════════

('That''s Vapore Ristorante',
 'Via Procaccini 30',
 'ristorante', 'mid',
 ARRAY['foodie','social','godereccio','rilassato'],
 'Cucina al vapore e alla griglia con ingredienti di stagione: verdure croccanti, pesce, carne. Il pranzo leggero ma saporito per chi vuole mangiare bene.',
 'La bowl con quinoa, salmone e verdure al vapore è il piatto più equilibrato del menu.',
 '🥗', NULL, 'sempione'),

('Macinata',
 'Via Vigevano 19',
 'ristorante', 'mid',
 ARRAY['godereccio','social','foodie','rilassato'],
 'Hamburger con carne macinata fresca ogni giorno e panini artigianali: smash, classic, double. Il burger fatto come si deve, senza catene.',
 'Lo smash burger con cheddar e cipolla caramellata è la scelta giusta — always.',
 '🍔', NULL, 'navigli'),

('Ghe Sem',
 'Via Celentano 1',
 'trattoria', 'mid',
 ARRAY['foodie','godereccio','social','vintage'],
 'Trattoria moderna con cucina milanese rivisitata: risotto, cotoletta, ossobuco in versione contemporanea. "Ghe sem" in milanese significa "ci siamo".',
 'La cotoletta con insalata di rucola e pomodorini è la versione leggera del classico — perfetta.',
 '🐄', NULL, 'porta_venezia'),

('Slow Sud',
 'Via Casale 7',
 'ristorante', 'mid',
 ARRAY['foodie','godereccio','social','rilassato'],
 'Cucina del sud Italia a Milano: arancini, parmigiana, pasta alla norma, cannoli. Il comfort food meridionale fatto con ingredienti siciliani doc.',
 'Gli arancini fritti al momento sono il piatto da non saltare — croccanti e filanti.',
 '🍊', NULL, 'porta_venezia'),

('Zibo',
 'Via Piero della Francesca 32',
 'ristorante', 'mid',
 ARRAY['foodie','social','rilassato','godereccio'],
 'Cucina romagnola con piadine, crescioni, passatelli, tagliatelle al ragù. La Romagna a Milano, fatta con farina macinata a pietra e ingredienti veri.',
 'La piadina con squacquerone e fichi è la combo perfetta — semplice e divina.',
 '🫓', NULL, 'sempione'),

-- ══════════════════════════════════════════════════════════════
-- LIBRERIE, CINEMA & CULTURA (6)
-- ══════════════════════════════════════════════════════════════

('Arci Biko — Cinema all''Aperto',
 'Viale d''Annunzio 7',
 'cinema', 'low',
 ARRAY['culturale','social','rilassato','alternativo'],
 'Cinema all''aperto estivo nel giardino del Biko: proiezioni di film d''autore, documentari, anteprime. Sdraio, coperta, birra e grande schermo.',
 'Porta la coperta anche d''estate — la sera si rinfresca. Arriva 30 min prima per il posto.',
 '🎬', NULL, 'navigli'),

('Anteo Palazzo del Cinema — Caffè',
 'Via Milazzo 9',
 'bar', 'mid',
 ARRAY['culturale','rilassato','coffee_lover','social'],
 'Il bar dentro il cinema Anteo: caffè, aperitivi, taglieri. Perfetto prima o dopo il film, con un''atmosfera da cinefili rilassati.',
 'Il caffè con la torta della casa prima del film delle 21 è il rituale perfetto.',
 '🎥', NULL, 'isola'),

('Fondazione ICA Milano',
 'Via Orobia 26',
 'museo', 'low',
 ARRAY['culturale','creativo','alternativo'],
 'Spazio per arte contemporanea e ricerca: mostre gratuite, talk, workshop. Giovane, sperimentale, sempre stimolante. Ingresso libero.',
 'Le inaugurazioni del giovedì sera sono il momento migliore — aperitivo e arte insieme.',
 '🎨', NULL, 'porta_romana'),

('Cinema Beltrade — Arena Estiva',
 'Via N. A. Porpora 44',
 'cinema', 'low',
 ARRAY['culturale','rilassato','social','alternativo'],
 'Arena estiva del cinema Beltrade: proiezioni all''aperto nel cortile, film d''essai, rassegne tematiche. L''esperienza cinema più intima di Milano.',
 'Le rassegne tematiche estive sono curatissime — segui la programmazione sul sito.',
 '🌙', NULL, 'altro'),

('Pirelli HangarBicocca — Café',
 'Via Chiese 2',
 'bar', 'low',
 ARRAY['culturale','creativo','rilassato','coffee_lover'],
 'Il caffè dentro HangarBicocca: dopo le installazioni monumentali, una pausa in uno spazio industriale luminoso. Arte e caffè insieme.',
 'Combina la visita alla mostra (gratuita) con un caffè — il sabato mattina è il momento ideale.',
 '☕', NULL, 'altro'),

('Libreria Gogol & Company',
 'Via Savona 101',
 'altro', 'low',
 ARRAY['culturale','creativo','rilassato','alternativo','zen'],
 'Libreria indipendente con angolo caffè: selezione curata di narrativa, saggistica, fumetti. Presentazioni, reading, community di lettori.',
 'Chiedi ai librai cosa leggere — sono appassionati e sanno sempre consigliare il libro giusto.',
 '📚', NULL, 'navigli'),

-- ══════════════════════════════════════════════════════════════
-- COCKTAIL BAR — EXTRA (5)
-- ══════════════════════════════════════════════════════════════

('Soda Jerk',
 'Via Meravigli 16',
 'cocktail_bar', 'mid',
 ARRAY['social','creativo','rilassato','aperitivo'],
 'Cocktail bar con tema vintage americano: soda fountain, highball giapponesi, drink a basso contenuto alcolico. Perfetto per chi vuole bere bene senza esagerare.',
 'Gli highball giapponesi sono la specialità — leggeri, rinfrescanti e perfetti per l''aperitivo.',
 '🥤', NULL, 'centro'),

('Rita Cocktails Isola',
 'Via Borsieri 30',
 'cocktail_bar', 'mid',
 ARRAY['social','alternativo','rilassato','aperitivo'],
 'Cocktail bar di quartiere a Isola: drink curati, prezzi ragionevoli, atmosfera da bar di amici. Zero pretese, tanta sostanza.',
 'I drink del giorno sono sempre la scelta migliore — il barman li pensa con gli ingredienti freschi.',
 '🍹', NULL, 'isola'),

('Dopolavoro Bicocca',
 'Via Emanueli 15',
 'bar', 'low',
 ARRAY['social','alternativo','rilassato','musicale'],
 'Bar-circolo in zona Bicocca: aperitivo economico, concerti, serate quiz, proiezioni. Il ritrovo degli studenti e dei creativi del quartiere.',
 'Le serate quiz del martedì sono esilaranti — forma una squadra e presentati alle 21.',
 '🎯', NULL, 'altro'),

('Social Club Milano',
 'Via Ascanio Sforza 47',
 'cocktail_bar', 'mid',
 ARRAY['elegante','social','aperitivo','rilassato'],
 'Wine bar e cocktail lounge sui Navigli con giardino interno: selezione naturale, taglieri curati, DJ set acustici nel weekend.',
 'Il giardino nascosto è il segreto meglio custodito dei Navigli — perfetto per un aperitivo rilassato.',
 '🏆', NULL, 'navigli'),

('Nottingham Forest Città Studi',
 'Via Celoria 2',
 'cocktail_bar', 'mid',
 ARRAY['creativo','social','misterioso','aperitivo'],
 'Cocktail bar con drink serviti in modi teatrali: provette, alambicchi, fumo, ghiaccio secco. L''esperienza cocktail come spettacolo.',
 'Il drink con il ghiaccio secco è lo show-stopper — ordinalo almeno una volta per lo spettacolo.',
 '🧪', NULL, 'altro');
