-- ============================================================
-- MY MOOD — Seed v3 · Batch 2 (100 venue)
-- ============================================================
-- Categorie: ristoranti, gelaterie, wine bar, brunch, street
--            food, wellness, mercati, locali con giardino,
--            spazi creativi, bar storici
-- ============================================================
-- Supabase → SQL Editor → incolla tutto → Run
-- ============================================================

INSERT INTO venues (name, address, type, price_range, compatible_moods, description, tips, emoji, website_url, neighborhood)
VALUES

-- ══════════════════════════════════════════════════════════════
-- RISTORANTI — FINE DINING & CREATIVI (10)
-- ══════════════════════════════════════════════════════════════

('Seta by Antonio Guida',
 'Via Gesù 6/8',
 'ristorante', 'luxury',
 ARRAY['elegante','esclusivo','romantico','foodie','creativo'],
 'Due stelle Michelin al Mandarin Oriental. Cucina mediterranea raffinatissima, servizio impeccabile, ambiente da sogno.',
 'Il menu degustazione corto (5 portate) è il modo migliore per un primo approccio.',
 '⭐', 'https://mandarinoriental.com/milan', 'centro'),

('Enrico Bartolini al Mudec',
 'Via Tortona 56',
 'ristorante', 'luxury',
 ARRAY['elegante','esclusivo','foodie','creativo','culturale'],
 'Tre stelle Michelin sopra il MUDEC. Cucina contemporanea che reinterpreta l''Italia regione per regione. Uno dei migliori ristoranti del paese.',
 'Abbina la cena a una visita al museo — la combo cultura + gastronomia è imbattibile.',
 '🌟', 'https://enricobartolini.net', 'navigli'),

('Contraste',
 'Via Meda 2',
 'ristorante', 'luxury',
 ARRAY['foodie','creativo','elegante','esclusivo','avventuroso'],
 'Una stella Michelin. Cucina d''avanguardia con menu a sorpresa — non sai cosa mangerai fino a quando il piatto arriva. Esperienza teatrale.',
 'Non chiedere il menu: il concetto è la sorpresa. Segnala solo allergie e lasciati guidare.',
 '🎭', 'https://contrastemilano.it', 'navigli'),

('Vòce Aimo e Nadia',
 'Piazza XXV Aprile',
 'ristorante', 'high',
 ARRAY['foodie','elegante','creativo','romantico'],
 'All''interno di Eataly, una stella Michelin di cucina toscana contemporanea. Prodotti impeccabili, cotture precise, ambiente luminoso.',
 'Il risotto alla milanese rivisitato è un omaggio alla tradizione con tocco moderno.',
 '🍽️', NULL, 'porta_nuova'),

('Alice Ristorante',
 'Piazza XXV Aprile 10',
 'ristorante', 'high',
 ARRAY['foodie','elegante','romantico','creativo'],
 'Cucina di Viviana Varese su Eataly: menu che cambiano con le stagioni, forte impronta vegetale, piatti visivamente stupendi.',
 'I piatti vegetariani qui sono talmente buoni che non rimpiangierai la carne.',
 '🌿', 'https://vivianavarese.it', 'porta_nuova'),

('Lubar Ristorante',
 'Via Palermo 21',
 'ristorante', 'mid',
 ARRAY['foodie','social','rilassato','aperitivo'],
 'Ristorante e cocktail bar con giardino nascosto nel cuore di Brera. Cucina italiana contemporanea, porzioni generose, atmosfera rilassata.',
 'Il giardino interno d''estate è un segreto — chiedi il tavolo fuori.',
 '🌳', NULL, 'brera'),

('Carlo e Camilla in Segheria',
 'Via Giuseppe Meda 24',
 'ristorante', 'high',
 ARRAY['romantico','elegante','foodie','creativo','misterioso'],
 'Dentro un''ex segheria con un unico tavolo da 18 metri. Carlo Cracco firma una cucina elegante in un setting industriale drammatico.',
 'Prenota il posto centrale del tavolone — l''esperienza è cenare come in una scena di film.',
 '🏭', 'https://carloecamillainsegheria.it', 'navigli'),

('Langosteria Cucina',
 'Via Savona 10',
 'ristorante', 'luxury',
 ARRAY['foodie','elegante','esclusivo','romantico'],
 'Il quartier generale di Langosteria: crudo di pesce al livello più alto, pasta con crostacei, servizio che non sbaglia un colpo.',
 'Il plateau di crudo per due è l''inizio perfetto — poi la pasta con i ricci di mare.',
 '🦞', 'https://langosteria.com', 'navigli'),

('Trippa',
 'Via Giorgio Vasari 1',
 'ristorante', 'mid',
 ARRAY['foodie','creativo','alternativo','godereccio'],
 'Diego Rossi ha messo le frattaglie e i tagli poveri al centro della cucina milanese. Menu scritto a mano che cambia ogni giorno.',
 'Non si prenota — arriva presto o tardi, e fidati ciecamente del menu del giorno.',
 '🫀', NULL, 'porta_romana'),

('28 Posti',
 'Via Corsico 1',
 'ristorante', 'mid',
 ARRAY['foodie','creativo','social','alternativo','zen'],
 'Solo 28 coperti, cucina a vista, menu cortissimo che cambia settimanalmente. Progetto sociale con reinserimento lavorativo. Cibo e significato.',
 'Il pranzo fisso del mercoledì è un segreto: qualità altissima, prezzo accessibilissimo.',
 '🪑', 'https://28posti.org', 'navigli'),

-- ══════════════════════════════════════════════════════════════
-- RISTORANTI — CUCINA QUOTIDIANA (10)
-- ══════════════════════════════════════════════════════════════

('Da Giannino — L''Angolo d''Abruzzo',
 'Via Pio II 20',
 'trattoria', 'low',
 ARRAY['foodie','godereccio','vintage','rilassato','social'],
 'Trattoria abruzzese di famiglia: arrosticini alla brace, pasta fatta a mano, porzioni colossali. Zero fronzoli, massima sostanza.',
 'Gli arrosticini (minimo 20 a testa) sono il motivo per cui esiste questo posto.',
 '🐑', NULL, 'sempione'),

('Giulio Pane e Ojo',
 'Via Ludovico Muratori 10',
 'trattoria', 'low',
 ARRAY['foodie','godereccio','social','vintage','festivo'],
 'Cucina romana a Milano: carbonara, amatriciana, cacio e pepe. Porzioni enormi, prezzi da studente, atmosfera da osteria vera.',
 'La carbonara è la migliore fuori da Roma — arriva alle 19:30 o la coda è infinita.',
 '🍝', NULL, 'porta_romana'),

('Premiata Forneria',
 'Via Alzaia Naviglio Grande 2',
 'ristorante', 'mid',
 ARRAY['social','rilassato','foodie','aperitivo'],
 'Storico ristorante-bar sui Navigli con terrazza sull''acqua. Cucina italiana semplice, ottimi cocktail, vista che non stanca mai.',
 'Il tavolo sulla terrazza del canale al tramonto è il posto più romantico dei Navigli.',
 '🌅', NULL, 'navigli'),

('Al Matarel',
 'Via Maria Calvi 2',
 'trattoria', 'mid',
 ARRAY['foodie','vintage','rilassato','godereccio','romantico'],
 'Trattoria milanese storica con risotto giallo, ossobuco e mondeghili. Nulla è cambiato dagli anni ''60 — e va bene così.',
 'L''ossobuco con risotto allo zafferano è il piatto della tradizione qui portato alla perfezione.',
 '🍲', NULL, 'centro'),

('Antica Trattoria della Pesa',
 'Viale Pasubio 10',
 'trattoria', 'high',
 ARRAY['foodie','vintage','elegante','romantico','godereccio'],
 'Dal 1880 serve la cucina milanese più autentica della città. Cotoletta con l''osso, risotto, nervetti. Un monumento gastronomico.',
 'La cotoletta alla milanese con l''osso è leggendaria — ordinala alta e croccante.',
 '🏛️', NULL, 'porta_nuova'),

('Pescaria',
 'Via Tortona 11',
 'ristorante', 'mid',
 ARRAY['foodie','social','godereccio','rilassato'],
 'Street food di pesce pugliese: panini con polpo, tartare, fritture. Veloce, fresco e di qualità. Coda garantita ma scorre veloce.',
 'Il panino con polpo arrosto e burrata è il piatto signature — vale ogni minuto di coda.',
 '🐙', 'https://pescfrancearia.it', 'navigli'),

('Flower Burger',
 'Via Tortona 12',
 'ristorante', 'low',
 ARRAY['social','alternativo','creativo','godereccio'],
 'Hamburger 100% vegani con pane colorato naturalmente. Rosa, blu, nero: Instagram-friendly ma soprattutto buoni davvero.',
 'Il Cherry Bomb (pane rosa, pulled jackfruit) è il più popolare — provalo come primo approccio.',
 '🌸', 'https://flowerburger.it', 'navigli'),

('Ham Holy Burger',
 'Via Palermo 15',
 'ristorante', 'mid',
 ARRAY['foodie','social','godereccio','rilassato'],
 'Hamburger gourmet con carne selezionata da macellai artigianali. Pane fatto in casa, topping creativi, birre artigianali.',
 'Il classico HHB con bacon croccante e cheddar stagionato è il modo giusto per iniziare.',
 '🍔', 'https://hamholyburger.com', 'brera'),

('Poke House',
 'Piazza XXV Aprile 1',
 'ristorante', 'mid',
 ARRAY['social','rilassato','foodie','zen'],
 'Poke bowl personalizzabili con basi, proteine e topping freschi. Veloce, leggero, perfetto per un pranzo sano senza rinunce.',
 'La base di riso sushi con salmone e avocado è il classico che non sbaglia.',
 '🥗', 'https://pfranceokehouse.it', 'porta_nuova'),

('Mercato Metropolitano',
 'Via Valenza 2',
 'ristorante', 'mid',
 ARRAY['foodie','social','avventuroso','godereccio','festivo'],
 'Mercato coperto con decine di stand gastronomici: pizza, sushi, pasta fresca, BBQ, gelato. Il food court più interessante di Milano.',
 'Fai un giro completo prima di scegliere — lo stand di pasta fresca è sottovalutato.',
 '🏬', 'https://mercatometropolitano.it', 'porta_romana'),

-- ══════════════════════════════════════════════════════════════
-- GELATERIE & PASTICCERIE (8)
-- ══════════════════════════════════════════════════════════════

('Artico Gelateria Tradizionale',
 'Via Luigi Porro Lambertenghi 15',
 'altro', 'low',
 ARRAY['foodie','rilassato','godereccio','social'],
 'Gelato artigianale pluripremiato: ingredienti di filiera corta, gusti classici eseguiti alla perfezione. Forse il miglior gelato di Milano.',
 'Il pistacchio e il cioccolato fondente sono i due gusti su cui giudicare una gelateria — qui sono perfetti.',
 '🍦', NULL, 'isola'),

('Pavè Gelati e Granite',
 'Via Cesare Battisti 21',
 'altro', 'low',
 ARRAY['foodie','rilassato','godereccio','creativo'],
 'La gelateria dei creatori di Pavè: gelato artigianale con gusti che cambiano e granite siciliane d''estate. Qualità senza compromessi.',
 'La granita al caffè con panna è il miglior modo per sopravvivere all''estate milanese.',
 '🧊', NULL, 'centro'),

('Il Massimo del Gelato',
 'Via Lodovico Castelvetro 18',
 'altro', 'low',
 ARRAY['foodie','godereccio','rilassato'],
 'Gelato artigianale dal 1982: gusti classici con materie prime eccezionali. Il crema è un punto di riferimento assoluto per i milanesi.',
 'Il gusto crema è leggendario — inizia da quello prima di esplorare gli altri.',
 '🍨', NULL, 'sempione'),

('Ciacco Lab',
 'Via Spadari 13',
 'altro', 'mid',
 ARRAY['foodie','creativo','godereccio'],
 'Gelato gourmet a due passi dal Duomo: gusti audaci come gorgonzola e noci, pera e ricotta. Per palati avventurosi.',
 'Chiedi l''abbinamento consigliato dal gelataio — le combo inaspettate sono il bello.',
 '🧪', NULL, 'centro'),

('Iginio Massari Alta Pasticceria',
 'Via Piero Della Francesca 20',
 'altro', 'high',
 ARRAY['foodie','elegante','godereccio','coffee_lover'],
 'Il maestro dei maestri della pasticceria italiana. Ogni dolce è un''opera di precisione assoluta. Il panettone è il migliore d''Italia.',
 'Il croissant al burro è il test: croccante, sfogliato, burroso. Perfezione.',
 '🎂', 'https://iginiomassari.it', 'sempione'),

('Marchesi 1824',
 'Via Santa Maria alla Porta 11a',
 'altro', 'high',
 ARRAY['elegante','vintage','coffee_lover','romantico','foodie'],
 'Pasticceria storica milanese rilevata da Prada. Interni color verde salvia, praline leggendarie, atmosfera d''altri tempi con tocco contemporaneo.',
 'Le praline in scatola sono il regalo milanese perfetto — eleganti e buonissime.',
 '💚', 'https://pasticceriamarchesi.com', 'centro'),

('Gattullo',
 'Piazzale di Porta Lodovica 2',
 'altro', 'mid',
 ARRAY['vintage','coffee_lover','rilassato','godereccio'],
 'Bar-pasticceria dal 1961 con un bancone di dolci ipnotico: cannoli, bignè, torte classiche. La merenda della Milano di una volta.',
 'Il cannolo siciliano e il bignè alla crema sono i due must — prendili entrambi.',
 '🥐', NULL, 'porta_romana'),

('GROM',
 'Via Santa Margherita 16',
 'altro', 'mid',
 ARRAY['rilassato','godereccio','social'],
 'Catena di gelato artigianale con ingredienti bio e filiera controllata. Gusti classici ben eseguiti, sedi in posizioni strategiche.',
 'Il cioccolato extra-noir è intenso al punto giusto — perfetto dopo cena.',
 '🍦', 'https://grom.it', 'centro'),

-- ══════════════════════════════════════════════════════════════
-- WINE BAR & ENOTECHE (8)
-- ══════════════════════════════════════════════════════════════

('Cantine Isola',
 'Via Paolo Sarpi 30',
 'bar', 'mid',
 ARRAY['aperitivo','rilassato','foodie','social','alternativo'],
 'Enoteca di quartiere con selezione di vini naturali e artigianali. Taglieri di salumi e formaggi, atmosfera informale e appassionata.',
 'Fatti consigliare un naturale che non conosci — il proprietario ha un gusto infallibile.',
 '🍷', NULL, 'isola'),

('Vineria Londei',
 'Via Carmagnola 4',
 'bar', 'mid',
 ARRAY['aperitivo','rilassato','vintage','foodie','romantico'],
 'Piccola vineria con centinaia di etichette e una cucina che accompagna il vino alla perfezione. Intimo, colto, senza fretta.',
 'L''aperitivo con calice e tagliere di formaggi stagionati è il rituale perfetto.',
 '🧀', NULL, 'isola'),

('Al Garghet',
 'Via Valpetrosa 5',
 'bar', 'mid',
 ARRAY['vintage','rilassato','foodie','aperitivo','godereccio'],
 'Osteria con mescita a due passi dal Duomo: vini sfusi dal rubinetto, piatti della tradizione lombarda, atmosfera da film anni ''50.',
 'Il vino al bicchiere dalla botte è un''esperienza vintage autentica — provalo rosso.',
 '🏺', NULL, 'centro'),

('Cantina Urbana',
 'Via Vigevano 33',
 'bar', 'mid',
 ARRAY['alternativo','creativo','social','aperitivo','foodie'],
 'Cantina urbana che produce vino nel cuore dei Navigli. Degustazioni, workshop e possibilità di fare il tuo blend personalizzato.',
 'Il workshop di blend dove crei il tuo vino è un''esperienza che non trovi altrove a Milano.',
 '🍇', 'https://cantinfranceaurbana.it', 'navigli'),

('Enoteca Naturale',
 'Via Savona 27',
 'bar', 'mid',
 ARRAY['alternativo','rilassato','foodie','aperitivo','zen'],
 'Solo vini naturali e biodinamici: selezione curatissima, consigli appassionati, piattini da abbinare. Per chi il vino lo vive con consapevolezza.',
 'Chiedi il "flight" di tre assaggi a tema — il modo migliore per esplorare il naturale.',
 '🌱', NULL, 'navigli'),

('Enoteca Cotti',
 'Via Solferino 42',
 'bar', 'high',
 ARRAY['elegante','foodie','aperitivo','vintage','romantico'],
 'Enoteca storica di Brera con una cantina di migliaia di etichette italiane e francesi. Degustazioni guidate, ambiente raffinato.',
 'Le degustazioni verticali del sabato (stesso vino, annate diverse) sono un''educazione al palato.',
 '🍾', NULL, 'brera'),

('Dry Cocktails & Pizza',
 'Via Solferino 33',
 'cocktail_bar', 'mid',
 ARRAY['social','aperitivo','foodie','creativo','alternativo'],
 'L''accoppiata geniale: cocktail d''autore e pizza gourmet sotto lo stesso tetto. Ambiente industrial-chic, sempre pieno, sempre buono.',
 'Ordina un cocktail e una pizza da condividere — è il format perfetto per questo posto.',
 '🍸', 'https://drymilano.it', 'brera'),

('Champagneria Giulia',
 'Via Giulia 3',
 'bar', 'high',
 ARRAY['elegante','esclusivo','romantico','aperitivo','festivo'],
 'Bar interamente dedicato allo champagne e ai migliori spumanti. Centinaia di etichette, flûte impeccabili, atmosfera intima e raffinata.',
 'Il volo di tre champagne (brut, rosé, vintage) è il modo migliore per apprezzare il posto.',
 '🥂', NULL, 'centro'),

-- ══════════════════════════════════════════════════════════════
-- BRUNCH & COLAZIONI (8)
-- ══════════════════════════════════════════════════════════════

('Macha Café',
 'Via Lodovico Lazzaro Zamenhof 11',
 'bar', 'mid',
 ARRAY['zen','rilassato','coffee_lover','creativo'],
 'Café tutto matcha: latte, dolci, bowl e smoothie a base di tè verde giapponese. Estetica minimal, atmosfera meditativa.',
 'Il matcha latte con latte d''avena è il drink signature — la qualità del matcha è altissima.',
 '🍵', NULL, 'isola'),

('Forno del Mastro',
 'Viale Col di Lana 1',
 'altro', 'low',
 ARRAY['foodie','rilassato','godereccio','coffee_lover'],
 'Forno artigianale con pane a lievitazione naturale, focacce farcite e dolci da colazione. L''odore di pane fresco ti chiama dalla strada.',
 'La focaccia con mortadella e stracchino è il pranzo veloce perfetto.',
 '🍞', NULL, 'navigli'),

('Lùini Panzerotti',
 'Via Santa Radegonda 16',
 'altro', 'low',
 ARRAY['foodie','godereccio','social','vintage'],
 'Dal 1888 la famiglia Luini sforna panzerotti fritti e al forno. Un''istituzione milanese: coda perenne ma ne vale ogni secondo.',
 'Quello classico fritto con mozzarella e pomodoro è la perfezione — non cercare alternative.',
 '🥟', 'https://luini.it', 'centro'),

('Princi',
 'Via Speronari 6',
 'altro', 'mid',
 ARRAY['coffee_lover','foodie','rilassato','social'],
 'Forno-caffetteria iconico: cornetti caldi tutto il giorno, pizze al trancio, focacce ripiene. Design minimal, prodotti impeccabili.',
 'Le pizzette tonde alle 18 appena sfornate sono lo snack perfetto prima dell''aperitivo.',
 '🥖', 'https://princi.it', 'centro'),

('T''a Milano',
 'Via Clerici 1',
 'bar', 'high',
 ARRAY['elegante','coffee_lover','rilassato','romantico'],
 'Caffè e cioccolateria di lusso: praline artigianali, cioccolata calda densa, caffè preparato con cura estrema. Ambiente sofisticato.',
 'La cioccolata calda densa (non quella annacquata) è un''esperienza — scegli il fondente 70%.',
 '🍫', 'https://tfranceamilano.it', 'centro'),

('Emporio Armani Caffè',
 'Via Croce Rossa 2',
 'bar', 'high',
 ARRAY['elegante','esclusivo','coffee_lover','rilassato'],
 'Il caffè nel flagship Armani: design impeccabile, servizio da grand hotel, dolci raffinati. Il lusso milanese applicato alla colazione.',
 'La colazione con brioche e cappuccino è il modo più elegante per iniziare la giornata.',
 '☕', NULL, 'centro'),

('Fioraio Bianchi Caffè',
 'Via Montebello 7',
 'bar', 'mid',
 ARRAY['romantico','vintage','rilassato','coffee_lover','zen'],
 'Metà fiorista, metà caffè: bevi il tuo cappuccino circondato da fiori freschi e piante. Atmosfera botanica unica, profumo inebriante.',
 'Il tavolo nell''angolo tra le orchidee è il posto più romantico per un caffè a Milano.',
 '🌺', NULL, 'brera'),

('Panificio Davide Longoni',
 'Via Tiraboschi 19',
 'altro', 'mid',
 ARRAY['foodie','coffee_lover','rilassato','godereccio'],
 'Il panificio più celebre di Milano: pane con grani antichi, focacce e dolci da lievito. Longoni ha cambiato il modo in cui Milano pensa al pane.',
 'Il pane integrale con semi è straordinario — compralo intero e gustalo nei giorni successivi.',
 '🍞', 'https://davidelongoni.com', 'porta_romana'),

-- ══════════════════════════════════════════════════════════════
-- LOCALI CON GIARDINO / CORTILE (8)
-- ══════════════════════════════════════════════════════════════

('10 Corso Como',
 'Corso Como 10',
 'bar', 'high',
 ARRAY['elegante','creativo','aperitivo','esclusivo','culturale'],
 'Concept store leggendario con bar, ristorante, galleria, libreria e giardino segreto. Aperitivo nel cortile verde tra arte e moda.',
 'Il giardino interno è il cuore del posto — siediti fuori e goditi il mix di arte e drink.',
 '🌿', 'https://10corsfranceocomo.com', 'porta_nuova'),

('Mag Café (Naviglio Pavese)',
 'Ripa di Porta Ticinese 43',
 'bar', 'low',
 ARRAY['rilassato','social','alternativo','aperitivo','vintage'],
 'Bar storico con piccolo dehors sul Naviglio Pavese. Cocktail onesti, musica dal vivo, clientela mista e zero pretese.',
 'L''aperitivo con buffet libero è una delle migliori offerte della zona Navigli.',
 '📖', NULL, 'navigli'),

('Ugo',
 'Via Corsico 12',
 'bar', 'mid',
 ARRAY['social','aperitivo','rilassato','festivo'],
 'Bar con grande giardino interno illuminato da lucine. Perfetto d''estate: cocktail freschi, tavoli nel verde, musica soft in sottofondo.',
 'D''estate il giardino è il posto dove stare — vai presto per trovare il tavolo migliore.',
 '💡', NULL, 'navigli'),

('Frida',
 'Via Antonio Pollaiuolo 3',
 'bar', 'mid',
 ARRAY['social','alternativo','aperitivo','creativo','rilassato'],
 'Bar con cortile bohémien in zona Isola: murales, piante, divani vintage. Aperitivo e serate con DJ set nel weekend.',
 'Il cortile con i murales è perfetto per un aperitivo estivo — arrivo consigliato ore 18.',
 '🎨', NULL, 'isola'),

('Cascina Cuccagna',
 'Via Cuccagna 2',
 'ristorante', 'mid',
 ARRAY['rilassato','zen','foodie','social','alternativo'],
 'Cascina del ''600 restaurata: ristorante bio, orto urbano, mercato contadino e spazio eventi. Un pezzo di campagna in Porta Romana.',
 'Il brunch della domenica con prodotti dell''orto è un rito — prenota.',
 '🏡', 'https://cfranceascfrancecinacuccagna.org', 'porta_romana'),

('Santeria Paladini 8',
 'Via Ettore Paladini 8',
 'bar', 'low',
 ARRAY['social','alternativo','creativo','musicale','festivo'],
 'Spazio ibrido con bar, ristorante, palco per concerti e cortile. Il centro culturale di Lambrate: musica, arte, socialità.',
 'I concerti nel cortile d''estate sono eventi imperdibili — controlla il programma.',
 '🎵', 'https://santfranceeria.it', 'altro'),

('Hug Milano',
 'Via Tortona 22',
 'bar', 'mid',
 ARRAY['rilassato','social','aperitivo','creativo'],
 'Locale con ampio spazio esterno in zona Tortona. Cucina leggera, aperitivi curati, atmosfera contemporanea e rilassata.',
 'L''area esterna è coperta anche quando piove — aperitivo safe in ogni stagione.',
 '🤗', NULL, 'navigli'),

('Apollo Club',
 'Via Giosuè Borsi 9',
 'bar', 'mid',
 ARRAY['social','musicale','alternativo','aperitivo','festivo'],
 'Club culturale con giardino, musica live, DJ set e eventi di comunità. Il punto di ritrovo di Porta Romana per la generazione under-35.',
 'Le serate "aperitivo + live" del giovedì sono il miglior rapporto divertimento-prezzo della zona.',
 '🎶', NULL, 'porta_romana'),

-- ══════════════════════════════════════════════════════════════
-- MERCATI & ESPERIENZE FOOD (8)
-- ══════════════════════════════════════════════════════════════

('Mercato di Via Fauché',
 'Via Fauché',
 'altro', 'low',
 ARRAY['foodie','vintage','social','godereccio'],
 'Mercato rionale del martedì e sabato mattina: banchi di frutta, formaggi, salumi, fiori. L''esperienza di mercato milanese più autentica.',
 'Il sabato mattina è il giorno migliore — porta le borse di tela e arriva entro le 9.',
 '🍎', NULL, 'sempione'),

('East Market',
 'Via Mecenate 88/A',
 'altro', 'low',
 ARRAY['vintage','creativo','alternativo','social'],
 'Mercatino mensile di vintage, vinili, design e street food in un''ex fabbrica. L''evento per cacciatori di pezzi unici.',
 'Arriva la mattina presto per i pezzi migliori — nel pomeriggio i migliori sono già andati.',
 '💿', 'https://eastfrancemarketmilano.com', 'altro'),

('Mercato Comunale di Wagner',
 'Piazza Wagner',
 'altro', 'mid',
 ARRAY['foodie','godereccio','vintage','rilassato'],
 'Mercato coperto storico con banco di pesce, macelleria, gastronomia. Frequentato dalla borghesia milanese, qualità eccellente.',
 'Il banco di gastronomia con i piatti pronti è perfetto per un pranzo veloce e di qualità.',
 '🐟', NULL, 'sempione'),

('Oh Bej! Oh Bej!',
 'Castello Sforzesco',
 'altro', 'low',
 ARRAY['festivo','vintage','social','godereccio','culturale'],
 'La fiera tradizionale milanese del 7 dicembre (Sant''Ambrogio): bancarelle, artigianato, dolci tipici. L''evento che apre il Natale milanese.',
 'Il vin brulé e le caldarroste sono d''obbligo — non resistere al profumo.',
 '🎄', NULL, 'sempione'),

('Eataly Smeraldo',
 'Piazza XXV Aprile 10',
 'altro', 'mid',
 ARRAY['foodie','social','godereccio','culturale'],
 'Tre piani di eccellenze enogastronomiche italiane: ristoranti, banchi, corsi di cucina e mercato. Il tempio del cibo italiano a Milano.',
 'Il piano terra con il banco pasta fresca e la gastronomia è il cuore — fermati lì.',
 '🇮🇹', 'https://eataly.net', 'porta_nuova'),

('Milano Wine Week',
 'Varie sedi, Milano',
 'altro', 'mid',
 ARRAY['foodie','social','aperitivo','elegante','culturale'],
 'Festival annuale del vino (ottobre) con degustazioni, masterclass e cene a tema in tutta Milano. La settimana più enoica dell''anno.',
 'Le masterclass gratuite si esauriscono in poche ore — iscriviti appena aprono le registrazioni.',
 '🍷', 'https://milanfranceowinfranceeweek.com', 'centro'),

('Mercato Centrale Milano',
 'Via Giovanni Battista Sammartini',
 'altro', 'mid',
 ARRAY['foodie','social','godereccio','avventuroso'],
 'Food hall nella Stazione Centrale: artigiani del cibo, pasta fresca, pizza, pesce, carne. Aperto fino a mezzanotte, perfetto per ogni momento.',
 'La pasta fatta al momento davanti a te è lo spettacolo — scegli il formato e il sugo.',
 '🚉', 'https://mercatocentrale.com/milano', 'porta_nuova'),

('Naviglio Grande - Mercatone dell''Antiquariato',
 'Alzaia Naviglio Grande',
 'altro', 'low',
 ARRAY['vintage','culturale','social','romantico','creativo'],
 'Ogni ultima domenica del mese: 400 bancarelle di antiquariato, vintage e collezionismo lungo il Naviglio Grande. Passeggiata e scoperte.',
 'Arriva presto (ore 9) per trovare i pezzi migliori — dopo le 12 è affollato e il meglio è andato.',
 '🕰️', NULL, 'navigli'),

-- ══════════════════════════════════════════════════════════════
-- WELLNESS & SPA (5)
-- ══════════════════════════════════════════════════════════════

('Terme Milano',
 'Piazza Medaglie d''Oro 2',
 'attivita', 'high',
 ARRAY['rilassato','zen','romantico','elegante'],
 'Complesso termale nel cuore della città: vasche idromassaggio, sauna finlandese, bagno turco e area relax. Benessere urbano.',
 'Il percorso serale è meno affollato e più suggestivo — provalo il giovedì.',
 '🧖', NULL, 'centro'),

('Hammam della Rosa',
 'Via Panfilo Castaldi 17',
 'attivita', 'mid',
 ARRAY['rilassato','zen','romantico','misterioso'],
 'Bagno turco autentico ispirato alla tradizione marocchina. Scrub con sapone nero, massaggio con olio di argan, tè alla menta.',
 'Il rituale completo (hammam + scrub + massaggio) dura 2 ore — regalati il pacchetto intero.',
 '🫧', 'https://hammamdellarosa.it', 'porta_venezia'),

('Aspria Harbour Club',
 'Via Cascina Bellaria 19',
 'attivita', 'luxury',
 ARRAY['sportivo','elegante','rilassato','esclusivo','zen'],
 'Club sportivo di lusso con piscine, tennis, spa e ristorante. L''esperienza fitness più esclusiva di Milano.',
 'Il day pass per la spa è il modo più accessibile per provare il club senza abbonamento.',
 '🏊', 'https://aspfranceria.com', 'sempione'),

('Bagni Misteriosi',
 'Via Carlo Botta 18',
 'attivita', 'mid',
 ARRAY['social','rilassato','festivo','culturale','creativo'],
 'Piscina all''aperto del Teatro Franco Parenti: d''estate si nuota, si prende il sole e si assiste a spettacoli. Unica in Italia.',
 'Compra il biglietto pomeridiano e resta fino all''aperitivo a bordo vasca.',
 '🏊', 'https://bagnimisteriosi.com', 'porta_romana'),

('Virgin Active CityLife',
 'Piazza Tre Torri 3',
 'attivita', 'high',
 ARRAY['sportivo','social','rilassato','zen'],
 'Palestra premium con piscina, corsi di gruppo, spa e vista sui grattacieli di CityLife. Fitness con skyline.',
 'Il corso di yoga con vista sulla Torre Isozaki al tramonto è un''esperienza speciale.',
 '💪', 'https://virginactive.it', 'sempione'),

-- ══════════════════════════════════════════════════════════════
-- SPAZI CREATIVI & CO-WORKING SOCIALI (5)
-- ══════════════════════════════════════════════════════════════

('BASE Milano',
 'Via Bergognone 34',
 'altro', 'low',
 ARRAY['creativo','culturale','alternativo','social'],
 'Ex stabilimento Ansaldo ora centro culturale: mostre, workshop, concerti, co-working e bar. L''hub creativo più vibrante di Milano.',
 'Gli eventi gratuiti del giovedì sera sono il modo migliore per scoprirlo.',
 '🎨', 'https://base.milano.it', 'navigli'),

('Talent Garden Calabiana',
 'Via Arcivescovo Calabiana 6',
 'altro', 'mid',
 ARRAY['creativo','social','coffee_lover','zen'],
 'Campus di co-working e innovazione in un giardino. Spazi luminosi, caffetteria, eventi tech e startup. Il network conta quanto la scrivania.',
 'Il caffè al piano terra è aperto a tutti — perfetto per lavorare qualche ora in un ambiente stimolante.',
 '💻', 'https://talfranceentgarden.org', 'porta_romana'),

('Fondazione Giangiacomo Feltrinelli',
 'Viale Pasubio 5',
 'altro', 'low',
 ARRAY['culturale','zen','coffee_lover','creativo'],
 'Edificio iconico con sala studio pubblica gratuita, biblioteca e conferenze. Architettura di Herzog & de Meuron, atmosfera concentrata.',
 'La sala lettura con le vetrate è uno dei posti migliori di Milano per studiare — gratis e bellissima.',
 '📖', 'https://fondazionefeltrinelli.it', 'porta_nuova'),

('Spazio Maiocchi',
 'Via Achille Maiocchi 7',
 'altro', 'low',
 ARRAY['creativo','alternativo','culturale','social'],
 'Project space di Slam Jam: mostre, lanci di sneakers, talk e installazioni. Il punto d''incontro tra streetwear, arte e cultura urbana.',
 'Segui @slamjam su Instagram per sapere quando ci sono gli eventi — spesso sono a invito.',
 '👟', NULL, 'porta_venezia'),

('La Triennale - Design Library',
 'Viale Alemagna 6',
 'altro', 'low',
 ARRAY['culturale','creativo','zen','coffee_lover'],
 'La biblioteca specializzata in design e architettura della Triennale. Accesso gratuito, spazio luminoso, perfetto per studiare circondati da bellezza.',
 'Portati il portatile — Wi-Fi gratuito, prese ovunque, e un caffè a portata di mano.',
 '📐', 'https://triennale.org', 'sempione');

-- Batch 2 continua — ultimi 30 venue

INSERT INTO venues (name, address, type, price_range, compatible_moods, description, tips, emoji, website_url, neighborhood)
VALUES

-- ══════════════════════════════════════════════════════════════
-- BAR STORICI & ICONICI (8)
-- ══════════════════════════════════════════════════════════════

('Jamaica',
 'Via Brera 32',
 'bar', 'mid',
 ARRAY['vintage','social','culturale','alternativo','aperitivo'],
 'Il bar degli artisti dal 1921: Lucio Fontana, Dino Buzzati e Enzo Jannacci bevevano qui. Oggi resta il cuore pulsante di Brera.',
 'Siediti al bancone e guarda chi entra — Brera si vive ancora così.',
 '🎨', NULL, 'brera'),

('Bar Basso',
 'Via Plinio 39',
 'cocktail_bar', 'mid',
 ARRAY['vintage','elegante','social','aperitivo','culturale'],
 'Inventore del Negroni Sbagliato, aperto dal 1947. Arredi originali, atmosfera da Milano intellettuale, cocktail generosi.',
 'Il Negroni Sbagliato qui è servito nella coppetta grande — l''originale, l''unico.',
 '🍹', NULL, 'porta_venezia'),

('Radetzky',
 'Corso Garibaldi 105',
 'bar', 'mid',
 ARRAY['social','aperitivo','rilassato','vintage'],
 'Café storico su Corso Garibaldi: aperitivi, brunch e lettura dei giornali. Terrazza sulla strada dove guardare Milano passare.',
 'Il brunch della domenica con i giornali è un classico — arriva entro le 11.',
 '📰', NULL, 'porta_nuova'),

('Nottingham Forest',
 'Via Piave 1',
 'cocktail_bar', 'mid',
 ARRAY['misterioso','creativo','alternativo','vintage'],
 'Dal 1970 il laboratorio di cocktail più folle di Milano. Drink serviti in provette, alambicchi e oggetti assurdi. Un''esperienza più che un bar.',
 'Non guardare il menu — dì al barman cosa ti piace e lascia che crei qualcosa di unico.',
 '🧪', 'https://nottinghamforest.it', 'porta_venezia'),

('Camparino in Galleria',
 'Piazza del Duomo 21',
 'bar', 'high',
 ARRAY['elegante','vintage','aperitivo','culturale','romantico'],
 'Aperto nel 1915 nella Galleria Vittorio Emanuele: dove è nato l''aperitivo milanese. Interni liberty mozzafiato, cocktail classici impeccabili.',
 'Bevi un Campari al piano terra tra gli affreschi — il posto dove tutto è iniziato.',
 '🏛️', 'https://camfranceparino.com', 'centro'),

('Stork Milano',
 'Via Gian Giacomo Mora 2',
 'cocktail_bar', 'mid',
 ARRAY['social','alternativo','aperitivo','creativo'],
 'Bar e ristorante con terrazza coperta in zona Colonne. Menu internazionale, cocktail creativi, atmosfera giovane e cosmopolita.',
 'La terrazza è uno dei posti migliori per l''aperitivo nella zona delle Colonne.',
 '🍸', NULL, 'navigli'),

('Cova',
 'Via Montenapoleone 8',
 'bar', 'luxury',
 ARRAY['elegante','esclusivo','vintage','coffee_lover','romantico'],
 'Pasticceria e caffetteria dal 1817 nel cuore del quadrilatero della moda. Dolci leggendari, servizio impeccabile, atmosfera da gran Milano.',
 'Il montebianco e i marron glacés in autunno sono una tradizione — qui sono i migliori.',
 '💎', NULL, 'centro'),

('Nottingham Forest (Navigli)',
 'Via Ascanio Sforza 47',
 'bar', 'mid',
 ARRAY['social','aperitivo','rilassato','alternativo'],
 'Sede dei Navigli del celebre cocktail bar: stessa creatività, atmosfera più rilassata con affaccio sul canale.',
 'D''estate i tavoli sul Naviglio sono il posto migliore per un drink al tramonto.',
 '🌅', NULL, 'navigli'),

-- ══════════════════════════════════════════════════════════════
-- STREET FOOD & CASUAL (7)
-- ══════════════════════════════════════════════════════════════

('Luini Panzerotti',
 'Via Santa Radegonda 16',
 'altro', 'low',
 ARRAY['foodie','godereccio','social','vintage'],
 'Dal 1888: panzerotti fritti e al forno, coda perenne. Il fast food milanese originale, prima che esistesse il concetto.',
 'Il panzerotto classico fritto mozzarella-pomodoro è un dogma — non deviare.',
 '🥟', 'https://luini.it', 'centro'),

('Spontini',
 'Via Santa Radegonda 11',
 'pizzeria', 'low',
 ARRAY['godereccio','social','vintage','foodie'],
 'Pizza al trancio altissima e mozzarellosa dal 1953. Si mangia in piedi, veloce e senza cerimonie. Milano in un morso.',
 'Lo spicchio margherita classico è quello che devi prendere — è grande come un piatto.',
 '🍕', 'https://spontinfranceimilano.com', 'centro'),

('Kebhouze',
 'Via Vigevano 18',
 'ristorante', 'low',
 ARRAY['godereccio','social','festivo','avventuroso'],
 'Kebab gourmet con ingredienti premium: pane fatto in casa, carne di qualità, salse artigianali. Il kebab elevato a esperienza.',
 'Il kebab royale con carne mista e salsa yogurt speziata è la versione da provare.',
 '🥙', NULL, 'navigli'),

('Berberè (Navigli)',
 'Via Vigevano 8',
 'pizzeria', 'mid',
 ARRAY['foodie','social','rilassato','creativo'],
 'La sede Navigli della pizzeria bolognese: stessi impasti perfetti, ambiente più grande e vivace con dehors sulla via.',
 'La pizza con salsiccia artigianale e friarielli è il piatto da habitué.',
 '🍕', 'https://bereberepizza.it', 'navigli'),

('Temakinho',
 'Via Vigevano 18',
 'ristorante', 'mid',
 ARRAY['social','foodie','festivo','creativo','avventuroso'],
 'Fusion nippo-brasiliana: temaki, ceviche, açaí bowl e cocktail tropicali. Colori vivaci, musica latina, energia contagiosa.',
 'Il temaki di salmone con Philadelphia e avocado è il classico che piace a tutti.',
 '🌴', 'https://temakinho.com', 'navigli'),

('California Bakery',
 'Piazza Sant''Eustorgio 4',
 'bar', 'mid',
 ARRAY['rilassato','social','coffee_lover','godereccio'],
 'Brunch all''americana: pancakes, eggs benedict, bagel, cookie e cheesecake. Atmosfera da caffetteria di Brooklyn, porzioni generose.',
 'L''eggs benedict della domenica mattina è un rito — arriva prima delle 11 o c''è coda.',
 '🥞', 'https://californiabakery.it', 'navigli'),

('That''s Vapore',
 'Via Vigevano 8',
 'ristorante', 'mid',
 ARRAY['zen','rilassato','foodie','social'],
 'Cucina al vapore: dim sum, bao, gyoza e piatti asiatici cotti senza grassi aggiunti. Leggero, sano e sorprendentemente gustoso.',
 'Il set di dim sum misti (6 pezzi) è il modo migliore per provare tutto.',
 '♨️', NULL, 'navigli'),

-- ══════════════════════════════════════════════════════════════
-- LIVE MUSIC & JAZZ (7)
-- ══════════════════════════════════════════════════════════════

('Blue Note Milano',
 'Via Pietro Borsieri 37',
 'altro', 'high',
 ARRAY['musicale','elegante','romantico','culturale','social'],
 'Il tempio del jazz a Milano e l''unico Blue Note in Europa. Artisti internazionali, acustica perfetta, cena-concerto con cucina di livello.',
 'I posti in platea vicino al palco sono i migliori — prenota il dinner show per l''esperienza completa.',
 '🎷', 'https://blfranceuenotemilano.com', 'isola'),

('Serraglio Jazz Club',
 'Via Valenza 19',
 'altro', 'mid',
 ARRAY['musicale','alternativo','rilassato','culturale'],
 'Jazz club intimo con programmazione di qualità: dal bebop all''avanguardia, sempre artisti veri su un palco piccolo e ravvicinato.',
 'Il giovedì è jam session aperta — se suoni, porta lo strumento.',
 '🎵', NULL, 'porta_romana'),

('Legend Club',
 'Via Leoncavallo 20',
 'altro', 'mid',
 ARRAY['musicale','alternativo','social','festivo'],
 'Live club con programmazione rock, metal e indie. Suono ottimo, birre a buon prezzo, atmosfera da concerto vero sotto palco.',
 'Compra il biglietto in prevendita — molti show vanno sold out.',
 '🤘', NULL, 'altro'),

('Santeria Toscana 31',
 'Via Toscana 31',
 'bar', 'low',
 ARRAY['social','alternativo','creativo','musicale','aperitivo'],
 'Spazio multifunzione con bar, cucina, palco e cortile. Concerti, presentazioni di libri, workshop e aperitivi. Il cuore culturale di Città Studi.',
 'Il cortile d''estate è il posto perfetto per un aperitivo con musica live gratuita.',
 '🎤', 'https://santfranceeria.it', 'altro'),

('Circolo Magnolia',
 'Via Idro 10, Segrate',
 'altro', 'low',
 ARRAY['musicale','social','alternativo','festivo','rilassato'],
 'Concerti all''aperto sul lago dell''Idroscalo: indie, elettronica, pop. L''estate milanese vive qui tra erba, drink e musica.',
 'Porta una coperta per sederti sull''erba davanti al palco — l''atmosfera è unica.',
 '🌳', 'https://circolomagnolia.it', 'altro'),

('La Salumeria della Musica',
 'Via Pasinetti 4',
 'altro', 'mid',
 ARRAY['musicale','social','vintage','rilassato','alternativo'],
 'Locale storico per musica dal vivo: cantautori, jazz, blues, world music. Ambiente intimo, palco a un metro dal pubblico.',
 'Le serate cantautori italiani sono il momento migliore — atmosfera da salotto musicale.',
 '🎸', NULL, 'porta_romana'),

('Tunnel',
 'Via Sammartini 30',
 'club', 'mid',
 ARRAY['musicale','nottambulo','alternativo','misterioso'],
 'Lo storico club sotto la Stazione Centrale: techno, house e sperimentazione in un tunnel di mattoni con impianto potentissimo.',
 'Il sabato notte è la serata più forte — preparati a stare in piedi fino alle 5.',
 '🌀', NULL, 'porta_nuova'),

-- ══════════════════════════════════════════════════════════════
-- RISTORANTI PESCE & CARNE (8)
-- ══════════════════════════════════════════════════════════════

('Da Giacomo',
 'Via Pasquale Sottocorno 6',
 'ristorante', 'high',
 ARRAY['elegante','foodie','romantico','social'],
 'Ristorante di pesce classico milanese: crudo impeccabile, frittura leggera, pasta con crostacei. Arredo d''antiquariato, clientela chic.',
 'Il fritto misto con verdure pastellate è leggendario — perfetto da condividere come antipasto.',
 '🐟', NULL, 'porta_venezia'),

('Il Liberty',
 'Viale Monte Grappa 6',
 'ristorante', 'high',
 ARRAY['elegante','foodie','romantico','vintage'],
 'Ristorante in un palazzo liberty con cucina di pesce creativa. Interni eleganti con stucchi originali, servizio attento.',
 'Il risotto ai frutti di mare è una poesia — prenota un tavolo nella sala con gli affreschi.',
 '🦐', NULL, 'porta_nuova'),

('Maio Restaurant',
 'Piazza XXIV Maggio 1',
 'ristorante', 'high',
 ARRAY['elegante','foodie','social','aperitivo'],
 'Ristorante e bar affacciato sulla Darsena con terrazza panoramica. Cucina italiana contemporanea, aperitivi al tramonto.',
 'La terrazza al tramonto è da cartolina — prenota il tavolo all''angolo.',
 '🌇', NULL, 'navigli'),

('Beefbar Milano',
 'Via Privata Fratelli Gabba 7a',
 'ristorante', 'luxury',
 ARRAY['elegante','esclusivo','foodie','social'],
 'Steakhouse di lusso del gruppo Monte Carlo: carni pregiate da tutto il mondo, tartare al coltello, interni spettacolari.',
 'La tartare preparata al tavolo è uno show — la wagyu giapponese è un''altra dimensione.',
 '🥩', 'https://beefbar.com', 'brera'),

('Al Pont de Ferr',
 'Ripa di Porta Ticinese 55',
 'ristorante', 'high',
 ARRAY['foodie','romantico','creativo','elegante'],
 'Cucina creativa sul Naviglio Grande: menu che cambia con le stagioni, ingredienti di territorio, tecnica raffinata. Una stella Michelin meritatissima.',
 'Il menu degustazione con abbinamento vini è il modo migliore per vivere l''esperienza completa.',
 '⭐', NULL, 'navigli'),

('Antica Osteria il Ronchettone',
 'Via Moncucco 1',
 'trattoria', 'mid',
 ARRAY['foodie','vintage','godereccio','rilassato','social'],
 'Trattoria milanese con giardino: risotto, cotoletta, cassoeula in inverno. Cucina della tradizione in un''atmosfera familiare e genuina.',
 'La cassoeula in inverno è un rito — porzioni enormi, sapore di casa.',
 '🍲', NULL, 'navigli'),

('Osteria dei Vecchi Sapori',
 'Via San Calocero 3',
 'trattoria', 'mid',
 ARRAY['foodie','vintage','rilassato','godereccio'],
 'Cucina lombarda tradizionale con ingredienti di stagione. Pasta fresca, brasato, bollito — i piatti della nonna eseguiti con amore.',
 'Il bollito misto è disponibile solo il giovedì — se capiti quel giorno, non esitare.',
 '👵', NULL, 'navigli'),

('Trattoria Torre di Pisa',
 'Via Fiori Chiari 21/5',
 'trattoria', 'mid',
 ARRAY['foodie','vintage','rilassato','social','romantico'],
 'Trattoria storica nel cuore di Brera: piatti toscani e milanesi, menu scritto a mano, tovaglie a quadri. Senza tempo dal 1964.',
 'La ribollita toscana d''inverno e la tagliata d''estate sono i piatti guida.',
 '🗼', NULL, 'brera');
