-- ============================================================
-- MY MOOD — Seed v3 · Batch 3 (100 venue)
-- ============================================================
-- Focus: zone meno coperte (Città Studi, Lambrate, Sarpi,
--        Nolo, Loreto, Corvetto) + categorie nuove (karaoke,
--        yoga, gallerie, librerie, sushi, piadinerie, ecc.)
-- ============================================================
-- Supabase → SQL Editor → incolla tutto → Run
-- ============================================================

INSERT INTO venues (name, address, type, price_range, compatible_moods, description, tips, emoji, website_url, neighborhood)
VALUES

-- ══════════════════════════════════════════════════════════════
-- ZONA SARPI / CHINATOWN (8)
-- ══════════════════════════════════════════════════════════════

('Ravioleria Sarpi',
 'Via Paolo Sarpi 27',
 'ristorante', 'low',
 ARRAY['foodie','godereccio','social','avventuroso'],
 'Ravioli cinesi fatti a mano al momento, cotti al vapore o alla piastra. Minuscolo, autentico, coda perenne. Il cuore di Chinatown.',
 'I ravioli alla piastra (guotie) sono i più richiesti — prendi almeno due porzioni.',
 '🥟', NULL, 'altro'),

('Kathay',
 'Via Paolo Sarpi 46',
 'ristorante', 'low',
 ARRAY['foodie','social','avventuroso','godereccio'],
 'Dim sum autentico in piena Chinatown: har gow, siu mai, baozi. Servizio veloce, prezzi imbattibili, esperienza da Hong Kong.',
 'Ordina dal carrello che passa — punta sui dim sum al vapore e i ravioli fritti.',
 '🫕', NULL, 'altro'),

('Guangzhou',
 'Via Paolo Sarpi 30',
 'ristorante', 'low',
 ARRAY['foodie','avventuroso','godereccio'],
 'Cucina cantonese autentica frequentata dalla comunità cinese. Anatra alla pechinese, noodles tirati a mano, hot pot. Il vero deal.',
 'L''anatra alla pechinese va ordinata per telefono un giorno prima — ne vale assolutamente la pena.',
 '🦆', NULL, 'altro'),

('Gong Oriental Attitude',
 'Corso Sempione 4',
 'ristorante', 'mid',
 ARRAY['foodie','elegante','social','creativo'],
 'Cucina pan-asiatica in un ambiente elegante: sushi, dim sum, curry, wok. La versione raffinata della cucina orientale per serate speciali.',
 'Il sashimi misto e i gyoza sono i piatti da ordinare sempre — qualità costante.',
 '🏮', 'https://gong.it', 'sempione'),

('Bok',
 'Via Paolo Sarpi 17',
 'ristorante', 'low',
 ARRAY['foodie','avventuroso','social','godereccio'],
 'Korean street food: fried chicken, bibimbap, tteokbokki. Porzioni generose, sapori autentici, atmosfera giovane e informale.',
 'Il fried chicken con salsa gochujang è addictive — prendi anche il kimchi fatto in casa.',
 '🍗', NULL, 'altro'),

('Shi Feng Bao',
 'Via Rosmini 11',
 'ristorante', 'low',
 ARRAY['foodie','godereccio','avventuroso'],
 'Specialità: xiao long bao (ravioli al brodo). Piccolo locale con cucina shanghainese autentica. Pochi piatti, tutti perfetti.',
 'Gli xiao long bao si mangiano così: morso piccolo, aspira il brodo, poi intingi nell''aceto.',
 '🥢', NULL, 'altro'),

('Maoji Street Food',
 'Via Paolo Sarpi 42',
 'ristorante', 'low',
 ARRAY['foodie','avventuroso','social','godereccio','alternativo'],
 'Street food cinese in versione moderna: jianbing (crêpe cinese), noodles piccanti, bubble tea artigianale. Giovane, colorato, autentico.',
 'Il jianbing con uovo e salsa piccante è lo street snack perfetto — da provare almeno una volta.',
 '🧋', NULL, 'altro'),

('Oriental Market Superstore',
 'Via Paolo Sarpi 22',
 'altro', 'low',
 ARRAY['foodie','avventuroso','creativo'],
 'Il supermercato asiatico più fornito di Milano: ingredienti impossibili da trovare altrove. Non è un ristorante, è un''avventura gastronomica.',
 'Il reparto surgelati ha dim sum pronti ottimi e il reparto snack è un viaggio — porta una borsa grande.',
 '🛒', NULL, 'altro'),

-- ══════════════════════════════════════════════════════════════
-- ZONA NOLO / LORETO / CITTA STUDI (10)
-- ══════════════════════════════════════════════════════════════

('Lacerba',
 'Via Orti 4',
 'bar', 'mid',
 ARRAY['social','aperitivo','alternativo','creativo'],
 'Bar e galleria in zona Porta Romana / Città Studi. Mostre d''arte, DJ set, aperitivi curati. Il bar che fa anche cultura.',
 'Le inaugurazioni delle mostre hanno aperitivo gratis e ottima gente — segui gli eventi.',
 '🎨', NULL, 'porta_romana'),

('Lambretto Studios Café',
 'Via Massimiano 25',
 'bar', 'mid',
 ARRAY['creativo','social','coffee_lover','alternativo'],
 'Caffetteria dentro un complesso di studi creativi a Lambrate. Brunch, caffè specialty, eventi. Il ritrovo dei designer del quartiere.',
 'Il brunch del sabato è il momento migliore — pancakes e caffè filtro in un cortile industriale.',
 '💡', NULL, 'altro'),

('Nolo Bar Social Club',
 'Via Antonio Kramer 19',
 'bar', 'low',
 ARRAY['social','alternativo','aperitivo','rilassato','musicale'],
 'Il punto di ritrovo di NoLo (North of Loreto): birre artigianali, vinili, jam session e quartiere che si incontra.',
 'Le jam session del mercoledì sono aperte a tutti — porta lo strumento o solo le orecchie.',
 '🎶', NULL, 'altro'),

('Ostello Bello Grande',
 'Via Roberto Lepetit 33',
 'bar', 'low',
 ARRAY['social','festivo','avventuroso','alternativo'],
 'Il bar dell''ostello più cool di Milano: aperto a tutti, terrazza con vista, serate a tema e gente da tutto il mondo. Perfetto per incontrare sconosciuti.',
 'Il rooftop è aperto a chiunque — non devi dormire all''ostello per accedervi.',
 '🌍', 'https://ostellobello.com', 'porta_nuova'),

('Birrificio di Lambrate — Golgi',
 'Via Golgi 60',
 'bar', 'low',
 ARRAY['social','rilassato','godereccio','alternativo'],
 'La seconda sede del Birrificio Lambrate, in zona Città Studi: birre artigianali, panini, atmosfera da pub inglese tra universitari.',
 'La birra Montestella (bionda) è perfetta per iniziare — poi esplora le stagionali.',
 '🍺', 'https://birriffranceiciolambrate.com', 'altro'),

('Pizzeria Spontini — Corso Buenos Aires',
 'Corso Buenos Aires 60',
 'pizzeria', 'low',
 ARRAY['godereccio','social','festivo','vintage'],
 'La sede storica di Spontini su Corso Buenos Aires: pizza al trancio alta un dito, coda che scorre veloce, sapore inconfondibile.',
 'Prendi il trancio margherita e mangialo in piedi come tradizione comanda.',
 '🍕', 'https://spontinimilano.com', 'porta_venezia'),

('Sushi Daily Bar',
 'Via Padova 36',
 'ristorante', 'low',
 ARRAY['foodie','rilassato','social'],
 'Sushi all-you-can-eat onesto in zona Loreto/NoLo. Varietà ampia, qualità sopra la media per la categoria, prezzo fisso.',
 'A pranzo il prezzo fisso è più basso — il sashimi misto è il piatto migliore.',
 '🍣', NULL, 'altro'),

('Polimi Bovisa — Caffè Politecnico',
 'Via Lambruschini 4',
 'bar', 'low',
 ARRAY['coffee_lover','rilassato','social','zen'],
 'La caffetteria del campus Bovisa del Politecnico: caffè, panini e studio intenso. Il posto dove nascono startup e amicizie tra ingegneri.',
 'Il Wi-Fi è velocissimo e c''è sempre posto il sabato mattina — studiare qui ha un''energia speciale.',
 '📐', NULL, 'altro'),

('ViVi Bistrot — Città Studi',
 'Piazza Leonardo da Vinci 7',
 'ristorante', 'mid',
 ARRAY['rilassato','foodie','social','zen'],
 'Bistrot sano e moderno vicino al Politecnico: bowl, insalate creative, piatti del giorno equilibrati. Il pranzo degli studenti consapevoli.',
 'La bowl con quinoa, avocado e salmone è il piatto più ordinato — per buoni motivi.',
 '🥑', NULL, 'altro'),

('Mama''s Burger — Loreto',
 'Viale Brianza 30',
 'ristorante', 'mid',
 ARRAY['godereccio','social','festivo'],
 'Hamburger smash style con carne fresca macinata al momento. Pane brioche, salse fatte in casa, patatine croccanti. Fast food fatto bene.',
 'Lo smash burger doppio con cheddar e bacon è la scelta per chi non vuole compromessi.',
 '🍔', NULL, 'altro'),

-- ══════════════════════════════════════════════════════════════
-- SUSHI & GIAPPONESE (8)
-- ══════════════════════════════════════════════════════════════

('Nobu Milano',
 'Via Pisoni 1',
 'ristorante', 'luxury',
 ARRAY['elegante','esclusivo','foodie','creativo','romantico'],
 'Il ristorante di Nobu Matsuhisa all''Armani Hotel: fusion nippo-peruviana al massimo livello. Black cod con miso è leggendario.',
 'Il black cod miso e il yellowtail jalapeño sono i piatti che hanno reso Nobu famoso nel mondo.',
 '🐟', 'https://noburestaurants.com', 'centro'),

('Iyo Aalto',
 'Via Piero della Francesca 70',
 'ristorante', 'high',
 ARRAY['foodie','elegante','creativo','social'],
 'Il secondo ristorante di Iyo: omakase più accessibile, bancone dove guardare gli chef lavorare. Qualità altissima, esperienza più informale.',
 'Siediti al bancone per l''omakase — è come avere uno spettacolo privato.',
 '🍱', 'https://iyo.it', 'sempione'),

('Wicky''s Innovative Japanese Cuisine',
 'Corso Italia 6',
 'ristorante', 'high',
 ARRAY['foodie','creativo','elegante','avventuroso'],
 'Cucina giapponese creativa con influenze africane dello chef Wicky Priyan. Piatti che non troverai in nessun altro ristorante.',
 'Il menu degustazione è l''unico modo per capire la visione dello chef — fidati ciecamente.',
 '🌍', NULL, 'centro'),

('Finger''s Garden',
 'Via Keplero 2',
 'ristorante', 'high',
 ARRAY['foodie','elegante','social','romantico'],
 'Ristorante giapponese con giardino giapponese interno. Sushi tradizionale di qualità, tempura perfetta, sake curato.',
 'Il giardino è un''oasi — cenare fuori tra bambù e lanterne è un''esperienza unica a Milano.',
 '🎋', 'https://fingerfrances.it', 'isola'),

('Basara Milano',
 'Via Tortona 12',
 'ristorante', 'mid',
 ARRAY['foodie','social','elegante','rilassato'],
 'Sushi all-you-can-eat premium: pesce di qualità nettamente superiore alla media, ambiente curato, servizio attento.',
 'Scegli il menu premium — la differenza di qualità nel pesce rispetto al base si sente.',
 '🍣', 'https://basarfranceamilano.it', 'navigli'),

('Sakeya',
 'Via Sottocorno 5',
 'bar', 'high',
 ARRAY['foodie','elegante','misterioso','creativo','zen'],
 'Il primo sake bar di Milano: decine di sake giapponesi, abbinamenti con cibo curati, atmosfera zen. Un viaggio in Giappone senza aereo.',
 'Chiedi il flight di tre sake con spiegazione — imparerai più che in un corso.',
 '🍶', NULL, 'porta_venezia'),

('Poporoya',
 'Via Eustachi 17',
 'ristorante', 'mid',
 ARRAY['foodie','vintage','rilassato','zen'],
 'Sushi bar minuscolo gestito da un giapponese dal 1986: il primo sushi bar di Milano. Pochi posti, pesce freschissimo, zero compromessi.',
 'Prenota per telefono e fidati dello chef — omakase informale al bancone.',
 '🐡', NULL, 'porta_venezia'),

('Temaki Home',
 'Via Vigevano 44',
 'ristorante', 'mid',
 ARRAY['foodie','social','rilassato'],
 'Temaki (coni di sushi) fatti al momento con combinazioni creative. Formato veloce e divertente, perfetto per una cena informale.',
 'Il temaki con salmone scottato e avocado è il best-seller — prova anche quello con gambero tempura.',
 '🍙', NULL, 'navigli'),

-- ══════════════════════════════════════════════════════════════
-- KARAOKE & ENTERTAINMENT (6)
-- ══════════════════════════════════════════════════════════════

('KTV Karaoke',
 'Via Edmondo De Amicis 25',
 'attivita', 'mid',
 ARRAY['social','festivo','musicale','avventuroso'],
 'Karaoke in stile giapponese con stanze private: schermi grandi, catalogo enorme, drink al tavolo. Perfetto per compleanni e serate folli.',
 'Prenota la stanza grande (fino a 15 persone) per il weekend — si riempie subito.',
 '🎤', NULL, 'navigli'),

('Big Karaoke',
 'Via Cusani 10',
 'attivita', 'mid',
 ARRAY['social','festivo','musicale'],
 'Karaoke con stanze private in pieno centro. Catalogo aggiornato, impianto audio serio, drink service in stanza.',
 'Le stanze VIP con divani sono molto più comode — il sovrapprezzo è minimo.',
 '🎵', NULL, 'centro'),

('Giocolandia',
 'Via dei Missaglia 97',
 'attivita', 'low',
 ARRAY['social','festivo','avventuroso'],
 'Mega centro divertimento: bowling, laser tag, sala giochi e go-kart indoor. Perfetto per gruppi numerosi e feste.',
 'Combina bowling + laser tag per un pomeriggio/serata di puro divertimento a prezzo pacchetto.',
 '🎮', NULL, 'altro'),

('The Cage — Escape Room',
 'Via Donatello 36',
 'attivita', 'mid',
 ARRAY['avventuroso','misterioso','social','creativo'],
 'Escape room con stanze ad alta tecnologia: effetti speciali, enigmi fisici e digitali, storie immersive. Tra le migliori di Milano.',
 'La stanza "The Bunker" è la più immersiva — pronta per gruppo da 4-5.',
 '🗝️', NULL, 'porta_venezia'),

('Virtual Arena Milano',
 'Via Mecenate 84/10',
 'attivita', 'mid',
 ARRAY['avventuroso','social','festivo','creativo'],
 'Arena di realtà virtuale multiplayer: giochi di squadra, esperienze horror e avventura. Ci si muove davvero nello spazio — non è un visore da divano.',
 'L''esperienza horror multiplayer è la più adrenalinica — non per deboli di cuore.',
 '🕶️', NULL, 'altro'),

('Axe Throwing Milano',
 'Via Mecenate 76',
 'attivita', 'mid',
 ARRAY['avventuroso','social','festivo','sportivo'],
 'Lancio dell''ascia in corsie dedicate: istruttori che insegnano la tecnica, birre disponibili, atmosfera da weekend warrior.',
 'Prenota la sessione di gruppo con birra inclusa — diventa competitivo molto in fretta.',
 '🪓', NULL, 'altro'),

-- ══════════════════════════════════════════════════════════════
-- YOGA, BENESSERE & SPORT (7)
-- ══════════════════════════════════════════════════════════════

('YogaOne Milano',
 'Via Solferino 27',
 'attivita', 'mid',
 ARRAY['zen','rilassato','sportivo'],
 'Centro yoga con lezioni per tutti i livelli: vinyasa, hatha, yin, hot yoga. Spazio luminoso e insegnanti preparati.',
 'La lezione di vinyasa delle 7:30 è il modo migliore per iniziare la giornata — energia garantita.',
 '🧘', NULL, 'brera'),

('Bouldering Hub',
 'Via Rogoredo 69',
 'attivita', 'mid',
 ARRAY['sportivo','avventuroso','social'],
 'Palestra di boulder con percorsi aggiornati settimanalmente. Area training, café e community forte. Lo sport che crea amicizia.',
 'Le serate "social climbing" del venerdì sono perfette per incontrare gente nuova.',
 '🧗', NULL, 'altro'),

('SNAG Milano — Padel & Tennis',
 'Via Giovanni Battista Piranesi 10',
 'attivita', 'mid',
 ARRAY['sportivo','social','rilassato'],
 'Centro padel e tennis con campi di ultima generazione, spogliatoi moderni e area bar. Lo sport del momento con tutti i comfort.',
 'Prenota il campo delle 18 e fermati per l''aperitivo al bar dopo la partita.',
 '🎾', NULL, 'porta_romana'),

('Idroscalo — Spiaggia e Sport',
 'Via Rivoltana, Segrate',
 'parco', 'low',
 ARRAY['sportivo','rilassato','social','avventuroso','zen'],
 'Il "mare dei milanesi": spiaggia, wakeboard, canoa, SUP e percorsi running. L''estate milanese si vive qui, a 15 minuti dal centro.',
 'Il wakeboard park è per tutti i livelli — anche la prima volta è divertentissima.',
 '🏄', NULL, 'altro'),

('Piscina Cozzi',
 'Viale Tunisia 35',
 'attivita', 'low',
 ARRAY['sportivo','rilassato','vintage'],
 'Piscina storica degli anni ''30 con architettura razionalista: vasche olimpiche, trampolini e un fascino retrò unico. Aperta al pubblico.',
 'Il biglietto per il nuoto libero costa pochissimo — è la palestra più economica della città.',
 '🏊', NULL, 'porta_venezia'),

('Milano Climbing — Sesto',
 'Via Gramsci 19, Sesto San Giovanni',
 'attivita', 'mid',
 ARRAY['sportivo','avventuroso','social'],
 'La palestra di arrampicata più grande della Lombardia: pareti fino a 18 metri, boulder, corsi per bambini e adulti.',
 'Il corso di prova per principianti include tutto (scarpe, imbragatura, lezione) — zero esperienza richiesta.',
 '🏔️', NULL, 'altro'),

('Ride Milano — Cycling Studio',
 'Via Vigevano 18',
 'attivita', 'mid',
 ARRAY['sportivo','social','musicale','festivo'],
 'Spinning in stile SoulCycle: buio, musica alta, istruttori carismatici, energia di gruppo. Più concerto che palestra.',
 'La prima lezione è a prezzo ridotto — vai preparato a sudare e a divertirti.',
 '🚴', NULL, 'navigli'),

-- ══════════════════════════════════════════════════════════════
-- GALLERIE D''ARTE & LIBRERIE (8)
-- ══════════════════════════════════════════════════════════════

('Galleria Lia Rumma',
 'Via Stilicone 19',
 'museo', 'low',
 ARRAY['culturale','creativo','alternativo','elegante'],
 'Galleria di arte contemporanea con artisti di calibro internazionale. Spazi enormi, mostre che fanno pensare. Ingresso libero.',
 'Le inaugurazioni sono eventi mondani — cocktail gratis e gente interessante.',
 '🖼️', NULL, 'sempione'),

('Galleria Massimo de Carlo',
 'Via Ventura 5',
 'museo', 'low',
 ARRAY['culturale','creativo','elegante','alternativo'],
 'Una delle gallerie più importanti d''Italia, nel cuore del design district di Lambrate. Artisti emergenti e star dell''arte contemporanea.',
 'Visita durante il Salone del Mobile (aprile) quando tutta la zona diventa un museo a cielo aperto.',
 '🎨', 'https://massimodecarlo.com', 'altro'),

('Armani/Silos',
 'Via Bergognone 40',
 'museo', 'mid',
 ARRAY['culturale','elegante','creativo','esclusivo'],
 'Il museo personale di Giorgio Armani: 40 anni di moda in un ex granaio industriale. L''estetica della semplicità, raccontata attraverso i vestiti.',
 'L''ultimo piano con i vestiti da red carpet è il momento più emozionante del percorso.',
 '👔', 'https://armanisilos.com', 'navigli'),

('Open — Care of',
 'Via Piranesi 10',
 'museo', 'low',
 ARRAY['culturale','creativo','alternativo'],
 'Non-profit che cura mostre di giovani artisti italiani e internazionali in spazi industriali. Fresco, sperimentale, gratuito.',
 'Le inaugurazioni del giovedì sera sono il momento migliore — arte e aperitivo.',
 '✨', NULL, 'porta_romana'),

('Libreria Hoepli',
 'Via Ulrico Hoepli 5',
 'altro', 'mid',
 ARRAY['culturale','zen','coffee_lover','creativo'],
 'La libreria più grande di Milano dal 1870: sei piani di libri su ogni argomento. Perdersi tra gli scaffali è un''esperienza in sé.',
 'Il reparto arte e architettura al terzo piano è un gioiello — sedie per sfogliare con calma.',
 '📚', 'https://hoepli.it', 'centro'),

('Libreria Utopia',
 'Via Vallazze 34',
 'altro', 'low',
 ARRAY['culturale','alternativo','zen','creativo'],
 'Libreria indipendente e caffè letterario in zona Lambrate: presentazioni, reading, club del libro e caffè buono. La libreria come luogo di comunità.',
 'Il club del libro mensile è aperto a tutti — un modo bello per conoscere gente con interessi simili.',
 '📖', NULL, 'altro'),

('Rizzoli Galleria',
 'Galleria Vittorio Emanuele II',
 'altro', 'mid',
 ARRAY['culturale','elegante','vintage','zen'],
 'Libreria dentro la Galleria Vittorio Emanuele: soffitti affrescati, scaffali in legno, sensazione di essere in un film. I libri come oggetto di lusso.',
 'Il piano superiore con i libri d''arte è meno affollato — sfoglia con calma guardando i mosaici del pavimento.',
 '📕', NULL, 'centro'),

('Mudec Photo',
 'Via Tortona 56',
 'museo', 'mid',
 ARRAY['culturale','creativo','alternativo'],
 'Lo spazio fotografico del MUDEC: mostre di fotografia contemporanea e reportage. Formato più intimo rispetto al museo principale.',
 'Combina la visita con il museo principale e un caffè al bar del MUDEC — mezza giornata perfetta.',
 '📷', 'https://mudec.it', 'navigli'),

-- ══════════════════════════════════════════════════════════════
-- PIADINERIE, FOCACCERIE & FAST CASUAL (8)
-- ══════════════════════════════════════════════════════════════

('La Piadineria',
 'Via Torino 5',
 'altro', 'low',
 ARRAY['godereccio','social','rilassato'],
 'Piadine romagnole farcite al momento: squacquerone, rucola, prosciutto crudo. Veloce, economico, sempre soddisfacente.',
 'La classica con squacquerone e rucola è il benchmark — poi sperimenta con la salsiccia.',
 '🫓', NULL, 'centro'),

('Poke''it',
 'Via Mercato 28',
 'ristorante', 'mid',
 ARRAY['rilassato','foodie','social','zen'],
 'Poke bowl con basi e topping scelti da te: riso, pesce crudo, verdure, salse. Fresco, leggero, personalizzabile all''infinito.',
 'La base con riso integrale e salmone scottato è la combo più equilibrata.',
 '🐠', NULL, 'brera'),

('Miscusi',
 'Piazza Oberdan 3',
 'ristorante', 'mid',
 ARRAY['foodie','social','rilassato','godereccio'],
 'Pastificio con pasta fresca fatta in casa e condita al momento. Menu che cambia con le stagioni, ingredienti italiani, atmosfera conviviale.',
 'Le cacio e pepe e l''amatriciana sono i piatti da giudicare — qui sono fatti col cuore.',
 '🍝', 'https://miscfranceusi.com', 'porta_venezia'),

('Alice Pizza',
 'Via Santa Radegonda 11',
 'pizzeria', 'low',
 ARRAY['godereccio','social','rilassato'],
 'Pizza al taglio romana: teglia con impasto croccante, topping abbondanti, vendita al peso. Fast, cheap, delicious.',
 'La pizza con fiori di zucca e alici è la sleeper hit — provala se c''è.',
 '🍕', NULL, 'centro'),

('Rossopomodoro',
 'Via Boccaccio 9',
 'pizzeria', 'mid',
 ARRAY['foodie','social','godereccio','rilassato'],
 'Pizzeria napoletana con forno a legna e ingredienti campani DOP. Impasto soffice, mozzarella filante, atmosfera da trattoria del sud.',
 'La DOC con mozzarella di bufala e pomodorini è la scelta sicura — semplice e perfetta.',
 '🍕', 'https://rossopomodoro.it', 'sempione'),

('Panino Giusto',
 'Piazza Beccaria 4',
 'ristorante', 'mid',
 ARRAY['foodie','rilassato','social','godereccio'],
 'Panini gourmet con ingredienti di alta qualità: prosciutto tagliato al momento, formaggi DOP, pane croccante. L''evoluzione del panino italiano.',
 'Il Panino del Nonno con bresaola e robiola è il classico che non tradisce.',
 '🥪', 'https://pfranceanfranceinogiusto.it', 'centro'),

('Kebab de Milan',
 'Via Lecco 7',
 'ristorante', 'low',
 ARRAY['godereccio','social','avventuroso','festivo'],
 'Kebab artigianale con pane fatto in casa, carne marinata per 24 ore, salse homemade. La versione milanese del comfort food notturno.',
 'Il kebab completo con tutte le salse e verdure grigliate è il pasto perfetto post-serata.',
 '🥙', NULL, 'porta_venezia'),

('That''s Bakery',
 'Via Vigevano 41',
 'altro', 'mid',
 ARRAY['coffee_lover','rilassato','godereccio','social'],
 'Bakery americana: cookies giganti, brownies, cinnamon rolls, banana bread. Tutto fatto in house, tutto oversize, tutto buono.',
 'Il cookie al cioccolato fondente caldo appena sfornato è il motivo per cui torni — sempre.',
 '🍪', NULL, 'navigli'),

-- ══════════════════════════════════════════════════════════════
-- RISTORANTI INDIANI, MEDIORIENTALI & AFRICANI (8)
-- ══════════════════════════════════════════════════════════════

('Tandoor Indian Restaurant',
 'Via Maddalena 3',
 'ristorante', 'mid',
 ARRAY['foodie','avventuroso','social','godereccio'],
 'Cucina indiana con forno tandoor autentico: naan perfetto, tikka masala, biryani profumato. Il ristorante indiano di riferimento in centro.',
 'Il butter chicken con naan all''aglio è la combo vincente — aggiungi un mango lassi.',
 '🍛', NULL, 'centro'),

('Shisha Café',
 'Via Casale 5',
 'bar', 'low',
 ARRAY['rilassato','social','misterioso','alternativo'],
 'Caffè con narghilé, tè alla menta e dolci mediorientali. Atmosfera mediorientale autentica, perfetto per chiacchierate lunghe.',
 'Il tè alla menta con i dolcetti al pistacchio è il rituale da fare almeno una volta.',
 '💨', NULL, 'porta_venezia'),

('Maoz Falafel',
 'Via Larga 8',
 'ristorante', 'low',
 ARRAY['foodie','godereccio','social','zen'],
 'Falafel freschi con bar di condimenti a volontà: hummus, tahina, insalate, salse piccanti. Veloce, vegetariano, economico.',
 'Prendi il piatto (non la pita) per avere più spazio per i condimenti — riempi senza pietà.',
 '🧆', NULL, 'centro'),

('Al Maqam',
 'Via Melzo 7',
 'ristorante', 'mid',
 ARRAY['foodie','social','avventuroso','rilassato'],
 'Cucina libanese autentica: mezze, fattoush, shawarma, piatti alla griglia. Porzioni generose per condivisione, atmosfera accogliente.',
 'Il mezze misto per due è il modo migliore per iniziare — hummus, babaganoush, tabbouleh e falafel.',
 '🫒', NULL, 'porta_venezia'),

('Noor Milano',
 'Via Savona 1',
 'ristorante', 'mid',
 ARRAY['foodie','creativo','avventuroso','elegante'],
 'Cucina mediorientale contemporanea: piatti della tradizione rivisitati con presentazione moderna e ingredienti premium.',
 'Il lamb kofte con yogurt e melograno è il piatto signature — bello e buono.',
 '🌙', NULL, 'navigli'),

('Ethiopian Restaurant Mesob',
 'Via Piacenza 12',
 'ristorante', 'low',
 ARRAY['foodie','avventuroso','social','godereccio','alternativo'],
 'Cucina etiope autentica: injera con stufati di carne e verdure, tutto da condividere con le mani. Esperienza comunitaria e sapori intensi.',
 'Il combo misto carne + verdure per due è il piatto perfetto per la prima volta.',
 '🫓', NULL, 'porta_romana'),

('Persian House',
 'Via Lecco 13',
 'ristorante', 'mid',
 ARRAY['foodie','avventuroso','rilassato','godereccio'],
 'Cucina persiana: kebab koobideh, riso allo zafferano, stufati lenti. Sapori delicati e speziati, porzioni generose.',
 'Il koobideh con riso allo zafferano e burro è il piatto da ordinare sempre — comfort food persiano.',
 '🍚', NULL, 'porta_venezia'),

('Africana Ristorante',
 'Via Padova 47',
 'ristorante', 'low',
 ARRAY['foodie','avventuroso','social','godereccio','alternativo'],
 'Cucina dell''Africa occidentale: jollof rice, suya, plantain fritto. Un viaggio gastronomico poco esplorato a Milano.',
 'Il jollof rice con pollo e plantain fritto è il piatto da scoprire — sapori che non ti aspetti.',
 '🌍', NULL, 'altro'),

-- ══════════════════════════════════════════════════════════════
-- LOCALI NOTTURNI & AFTER HOUR (7)
-- ══════════════════════════════════════════════════════════════

('Dude Club',
 'Via Davanzati 58',
 'club', 'low',
 ARRAY['nottambulo','alternativo','musicale','social'],
 'Club underground per chi ama l''elettronica vera: techno, acid house, breakbeat. Piccolo, sudato, con un sound system che picchia.',
 'Le serate del venerdì sono le più credibili — segui i flyer su Instagram.',
 '🔈', NULL, 'altro'),

('Plastic',
 'Via Gargano 15',
 'club', 'mid',
 ARRAY['nottambulo','alternativo','social','festivo','creativo'],
 'Il club più iconico di Milano dalla scena anni ''80. Si è reinventato mille volte: oggi techno, performance e serate queer.',
 'Le serate a tema sono le migliori — controlla la programmazione prima di andare.',
 '🪩', NULL, 'altro'),

('Gate Milano',
 'Via Valtellina 36',
 'club', 'mid',
 ARRAY['nottambulo','social','festivo','musicale'],
 'Club con programmazione varia: house, techno, hip-hop, reggaeton. Due sale, impianto potente, folla giovane ed energica.',
 'Il sabato è la serata più piena — lista consigliata per evitare la coda.',
 '🚪', NULL, 'isola'),

('Volt Club',
 'Via F. Casati 7',
 'club', 'mid',
 ARRAY['nottambulo','alternativo','musicale','misterioso'],
 'Club che ospita le serate techno e house più rispettate di Milano. Line-up internazionali, atmosfera dark, suono cristallino.',
 'Compra il biglietto su Resident Advisor — le serate migliori vanno sold out.',
 '⚡', NULL, 'porta_venezia'),

('Old Fashion Club',
 'Viale Emilio Alemagna 6',
 'club', 'high',
 ARRAY['nottambulo','elegante','social','festivo','esclusivo'],
 'Club dentro Parco Sempione: terrazza all''aperto, dress code elegante, serate a tema. Il clubbing milanese in versione glam.',
 'D''estate la terrazza è il posto dove stare — prenota un tavolo con bottiglia.',
 '🥂', 'https://oldfashion.it', 'sempione'),

('Just Cavalli',
 'Via Luigi Camoens 1',
 'club', 'high',
 ARRAY['nottambulo','elegante','esclusivo','festivo','social'],
 'Club-ristorante di Roberto Cavalli alla Torre Branca: design leopardato, clientela fashion, serate con DJ internazionali.',
 'La cena + discoteca è il pacchetto migliore — entri senza coda e mangi bene.',
 '🐆', 'https://justcavalli.com', 'sempione'),

('Tocqueville 13',
 'Via Alexis de Tocqueville 13',
 'club', 'high',
 ARRAY['nottambulo','elegante','social','festivo','esclusivo'],
 'Club storico di Corso Como: quattro sale, terrazza, eventi privati. Il punto di riferimento della nightlife elegante milanese.',
 'La lista è fondamentale — contatta i PR per il weekend o rischi di restare fuori.',
 '✨', NULL, 'porta_nuova'),

-- ══════════════════════════════════════════════════════════════
-- BIRRERIE & CRAFT BEER (5)
-- ══════════════════════════════════════════════════════════════

('Birrificio Lambrate',
 'Via Adelchi 5',
 'bar', 'low',
 ARRAY['social','rilassato','foodie','godereccio','alternativo'],
 'Il birrificio artigianale storico di Milano: birre prodotte in loco, giardino, taglieri. Un pezzo di storia della craft beer italiana.',
 'La Ghisa (amber ale) e la Montestella (IPA) sono le signature — accompagna con i taglieri.',
 '🍺', 'https://birrificiolambrate.com', 'altro'),

('Baladin Milano',
 'Via Solferino 56',
 'bar', 'mid',
 ARRAY['social','foodie','rilassato','godereccio'],
 'La casa milanese di Teo Musso: 30+ birre artigianali alla spina, hamburger gourmet, atmosfera calda. La birra italiana elevata ad arte.',
 'La Nazionale è perfetta per iniziare — poi esplora le birre stagionali.',
 '🍻', 'https://baladin.it', 'brera'),

('Hop Stuff',
 'Via Pastrengo 16',
 'bar', 'mid',
 ARRAY['social','alternativo','rilassato','godereccio'],
 'Beer shop con 200+ referenze da tutto il mondo e 8 spine rotanti. Il paradiso del beer geek: IPA americane, sour belghe, stout imperiali.',
 'Chiedi consiglio al barista — cambiano spine ogni settimana e sanno tutto.',
 '🍺', NULL, 'isola'),

('LambicZoon',
 'Via Friuli 46',
 'bar', 'mid',
 ARRAY['foodie','alternativo','rilassato','social','creativo'],
 'Bar specializzato in birre lambic e sour belghe: gueuze, kriek, framboise. Una nicchia per palati curiosi, atmosfera intima.',
 'Prova un flight di lambic se è la tua prima volta — sono birre che non assomigliano a nient''altro.',
 '🫧', NULL, 'porta_romana'),

('Brewdog Milano',
 'Viale Pasubio 3',
 'bar', 'mid',
 ARRAY['social','godereccio','rilassato','festivo'],
 'Il flagship italiano della catena scozzese: 20 spine, hamburger, atmosfera da pub moderno. Perfetto per gruppi e serate informali.',
 'La Punk IPA è il classico — ma le guest tap hanno spesso sorprese migliori.',
 '🐕', 'https://brewdog.com', 'isola'),

-- ══════════════════════════════════════════════════════════════
-- ESCAPE ROOM, BOWLING & GAMING (5)
-- ══════════════════════════════════════════════════════════════

('Escape Room Milano',
 'Via Moisè Loria 37',
 'attivita', 'mid',
 ARRAY['avventuroso','social','misterioso','creativo'],
 'Escape room con stanze a tema immersive: horror, detective, avventura. Lavoro di squadra, adrenalina e rompicapi per gruppi da 2 a 6.',
 'La stanza horror è la più difficile — prenota quella se vuoi una vera sfida.',
 '🔐', NULL, 'altro'),

('Bowling Bicocca',
 'Viale Sarca 186',
 'attivita', 'mid',
 ARRAY['social','festivo','rilassato','godereccio'],
 'Bowling con 16 piste, luci fluorescenti, bar e zona arcade. Classicone per compleanni, serate in gruppo, primo appuntamento easy.',
 'Il cosmic bowling del venerdì sera (con luci UV e musica) è il più divertente.',
 '🎳', NULL, 'altro'),

('VR Star',
 'Via Gian Battista Pergolesi 8',
 'attivita', 'mid',
 ARRAY['avventuroso','creativo','social','festivo'],
 'Centro di realtà virtuale con esperienze multiplayer: sparatutto, esplorazione, horror VR. Tecnologia di ultima generazione, sessioni da 30-60 min.',
 'Prenota la sessione multiplayer per 4 — le esperienze collaborative sono le più divertenti.',
 '🥽', NULL, 'porta_venezia'),

('Board Game Café L''Orso',
 'Via Savona 14',
 'bar', 'low',
 ARRAY['social','rilassato','creativo','alternativo'],
 'Caffè con 500+ giochi da tavolo disponibili: strategici, party game, cooperativi. Ordini da bere, scegli un gioco, giochi quanto vuoi.',
 'Per gruppi grandi i party game come Codenames funzionano sempre — chiedi aiuto allo staff per scegliere.',
 '🎲', NULL, 'navigli'),

('Puttshack Milano',
 'Piazza Lina Bo Bardi 1',
 'attivita', 'mid',
 ARRAY['social','festivo','rilassato','godereccio'],
 'Mini golf tech-infused in CityLife: piste con tracking automatico, cocktail, cibo. La versione moderna e social del minigolf.',
 'Prenota il weekend sera con il pacchetto drink — è la formula migliore per gruppi.',
 '⛳', 'https://puttshack.com', 'sempione'),

-- ══════════════════════════════════════════════════════════════
-- COLAZIONI & BRUNCH SPOT (5)
-- ══════════════════════════════════════════════════════════════

('Pavé',
 'Via Felice Casati 27',
 'bar', 'mid',
 ARRAY['coffee_lover','foodie','rilassato','godereccio','creativo'],
 'Pasticceria artigianale di culto: cornetti sfogliati, lievitati, torte. Un laboratorio a vista dove tutto è fatto con ossessione per la qualità.',
 'Il cornetto al pistacchio e il pain au chocolat sono i due motivi per svegliarsi presto.',
 '🥐', 'https://pavemilano.com', 'porta_venezia'),

('Orsonero Coffee',
 'Via Broggi 15',
 'bar', 'mid',
 ARRAY['coffee_lover','rilassato','zen','creativo'],
 'Specialty coffee bar di riferimento a Milano: caffè filtro, V60, aeropress. Chicchi selezionati, baristi competenti, zero compromessi.',
 'Prova il filtro del giorno — ogni settimana un''origine diversa, ogni tazza una scoperta.',
 '☕', 'https://orfrancesonero.coffee', 'porta_venezia'),

('Forno del Mastro',
 'Via Spontini 8',
 'altro', 'low',
 ARRAY['foodie','godereccio','rilassato','coffee_lover'],
 'Forno con pane a lievitazione naturale, focacce, pizzette e dolci rustici. Il profumo del pane appena sfornato ti attira da un isolato.',
 'La focaccia con pomodorini e origano alle 8 di mattina, appena uscita dal forno — religione.',
 '🍞', NULL, 'porta_venezia'),

('Fondazione Prada Bar Luce',
 'Largo Isarco 2',
 'bar', 'mid',
 ARRAY['coffee_lover','culturale','elegante','creativo','vintage'],
 'Il bar disegnato da Wes Anderson dentro Fondazione Prada: interni pastello, formica, jukebox. Colazione o aperitivo in un set cinematografico.',
 'Vai la mattina presto per goderti il bar vuoto — la luce è perfetta e non c''è coda.',
 '🎬', 'https://fondazioneprada.org', 'porta_romana'),

('Marchesi 1824',
 'Via Santa Maria alla Porta 11a',
 'bar', 'high',
 ARRAY['coffee_lover','elegante','vintage','godereccio','esclusivo'],
 'Pasticceria storica milanese dal 1824, ora parte del gruppo Prada: panettone, praline, brioche. L''eleganza milanese in forma di dolce.',
 'La brioche con crema è un classico intoccabile — accompagnala con un caffè al bancone come si fa qui.',
 '🎩', 'https://pasticceriamarchesi.com', 'centro'),

-- ══════════════════════════════════════════════════════════════
-- TRATTORIE & OSTERIE TRADIZIONALI (5)
-- ══════════════════════════════════════════════════════════════

('Trattoria Milanese',
 'Via Santa Marta 11',
 'trattoria', 'mid',
 ARRAY['foodie','godereccio','vintage','rilassato'],
 'Trattoria dal 1933: risotto alla milanese, cotoletta, ossobuco, mondeghili. La cucina meneghina nella sua forma più pura e rassicurante.',
 'La cotoletta alta con l''osso è il piatto simbolo — ordinala con il risotto giallo.',
 '🥘', NULL, 'centro'),

('Osteria del Treno',
 'Via San Gregorio 46',
 'trattoria', 'mid',
 ARRAY['foodie','vintage','social','godereccio','rilassato'],
 'Osteria dentro un''ex stazione ferroviaria: soffitti alti, arredi d''epoca, cucina lombarda. Un viaggio nel tempo gastronomico.',
 'Il carrello dei bolliti è lo spettacolo — scegli i tagli e le salse che preferisci.',
 '🚂', 'https://osteriadeltreno.it', 'porta_venezia'),

('Ratanà',
 'Via Gaetano de Castillia 28',
 'ristorante', 'mid',
 ARRAY['foodie','elegante','godereccio','social'],
 'Cucina milanese contemporanea in un edificio Liberty restaurato: ingredienti locali, ricette della tradizione rivisitate con leggerezza.',
 'Il risotto con midollo e zafferano è la loro versione del classico — perfetto.',
 '🏛️', 'https://ratana.it', 'porta_nuova'),

('Trattoria del Nuovo Macello',
 'Via Cesare Lombroso 20',
 'trattoria', 'mid',
 ARRAY['foodie','godereccio','vintage','alternativo'],
 'Trattoria fuori dai radar turistici: piatti della tradizione lombarda eseguiti con cura artigianale. Porzioni generose, vini naturali, zero fronzoli.',
 'I tortelli di zucca e il brasato sono i piatti da non perdere — riserva un tavolo a pranzo.',
 '🍷', NULL, 'porta_romana'),

-- ══════════════════════════════════════════════════════════════
-- COWORKING CAFÉ & STUDY SPOT (5)
-- ══════════════════════════════════════════════════════════════

('Santeria Paladini 8',
 'Via Paladini 8',
 'bar', 'low',
 ARRAY['creativo','social','rilassato','alternativo','coffee_lover'],
 'Spazio ibrido: caffè, coworking, concerti, mostre. Di giorno si lavora al laptop, di sera si ascolta musica live. Il multitasking milanese.',
 'Di giorno prendi il caffè e lavora al piano superiore — la sera controlla la programmazione concerti.',
 '🎤', 'https://santfranceeria.it', 'altro'),

('Colibrì Café',
 'Via Solferino 5',
 'bar', 'low',
 ARRAY['coffee_lover','rilassato','zen','creativo'],
 'Piccolo caffè con atmosfera tranquilla, perfetto per lavorare o studiare: WiFi veloce, prese ovunque, caffè specialty.',
 'Il tavolo lungo in fondo è il posto migliore per lavorare — silenzioso e con prese.',
 '☕', NULL, 'brera'),

('Open Milano',
 'Viale Monte Nero 6',
 'bar', 'mid',
 ARRAY['creativo','social','rilassato','coffee_lover','alternativo'],
 'Spazio multifunzione: bar, ristorante, coworking, eventi. Giardino interno, atmosfera rilassata, community di freelance e creativi.',
 'Il brunch del weekend è il modo migliore per scoprire lo spazio — poi torni per lavorarci.',
 '💻', NULL, 'porta_romana'),

('Moleskine Café',
 'Corso Garibaldi 65',
 'bar', 'mid',
 ARRAY['creativo','coffee_lover','elegante','culturale','zen'],
 'Il caffè letterario di Moleskine: design curato, mostre, workshop creativi. Perfetto per scrivere, disegnare, pensare con un caffè perfetto.',
 'Il tavolo vicino alla vetrina è il posto più instagrammabile — ma il mezzanino è il più tranquillo.',
 '📓', 'https://moleskine.com', 'brera'),

('BASE Milano',
 'Via Bergognone 34',
 'altro', 'low',
 ARRAY['creativo','alternativo','culturale','social','coffee_lover'],
 'Ex stabilimento Ansaldo trasformato in hub culturale: mostre, talk, coworking, mercatini. Il centro gravitazionale della Milano creativa.',
 'Controlla il calendario eventi prima di andare — c''è sempre qualcosa di interessante in programma.',
 '🏭', 'https://base.milano.it', 'navigli'),

-- ══════════════════════════════════════════════════════════════
-- VARIE — ESPERIENZE UNICHE (6)
-- ══════════════════════════════════════════════════════════════

('Bagni Misteriosi',
 'Via Carlo Botta 18',
 'altro', 'mid',
 ARRAY['social','rilassato','creativo','alternativo','festivo'],
 'Piscina all''aperto del Teatro Franco Parenti: si nuota d''estate, d''inverno diventa pista di pattinaggio. Bar, sdraio, eventi culturali a bordo vasca.',
 'D''estate vai al tramonto — nuoti con la luce dorata e poi aperitivo a bordo piscina.',
 '🏊', 'https://bfranceagnimisteriosi.it', 'porta_romana'),

('Spirit de Milan',
 'Via Bovisasca 59',
 'bar', 'mid',
 ARRAY['musicale','vintage','social','festivo','godereccio'],
 'Ex fabbrica trasformata in balera milanese: swing, liscio, musica dal vivo, cucina tradizionale. Un viaggio negli anni ''40 con cocktail in mano.',
 'Le serate swing del giovedì sono le più iconiche — impara due passi e buttati.',
 '💃', 'https://spiritdemilan.it', 'altro'),

('Civico Planetario',
 'Corso Venezia 57',
 'museo', 'low',
 ARRAY['culturale','zen','romantico','misterioso','creativo'],
 'Il planetario più grande d''Italia: proiezioni del cielo stellato, conferenze di astronomia. Un''esperienza immersiva sotto una cupola di stelle.',
 'Le serate di osservazione con telescopio sono le più emozionanti — controlla il calendario.',
 '🔭', 'https://comune.milano.it/planetario', 'porta_venezia'),

('Ippodromo SNAI San Siro',
 'Piazzale dello Sport 16',
 'attivita', 'mid',
 ARRAY['social','elegante','avventuroso','festivo','vintage'],
 'Corse di cavalli in un impianto storico: trotto e galoppo, tribune eleganti, prato per picnic. Un pomeriggio diverso dal solito.',
 'Le giornate di galoppo primaverili sono le migliori — vai in tribuna con gli amici e scommetti per gioco.',
 '🏇', NULL, 'altro'),

('Naviglio Grande — Passeggiata',
 'Alzaia Naviglio Grande',
 'parco', 'low',
 ARRAY['rilassato','romantico','social','zen','vintage'],
 'La passeggiata lungo il Naviglio Grande: botteghe antiquarie, street art, locali storici. Il lato più poetico e autentico di Milano.',
 'Cammina dal Ponte delle Sirenette fino alla Darsena al tramonto — il percorso più bello.',
 '🌅', NULL, 'navigli'),

('Castello Sforzesco — Cortili',
 'Piazza Castello',
 'museo', 'low',
 ARRAY['culturale','rilassato','romantico','zen','vintage'],
 'I cortili del Castello Sforzesco: aperti e gratuiti, perfetti per passeggiate, letture, picnic informali. La storia di Milano a portata di mano.',
 'Entra dal cortile delle Armi e attraversa fino al Parco Sempione — è il percorso più suggestivo.',
 '🏰', 'https://milanocastello.it', 'sempione');
