-- ============================================================
-- MY MOOD — Seed v3 · Batch 1 (100 venue)
-- ============================================================
-- Categorie: cinema, teatri, musei, ristoranti, pizzerie,
--            trattorie, club, pub, lounge, parchi, attività
-- ============================================================
-- Come usarlo:
-- Supabase → SQL Editor → incolla tutto → Run
-- ============================================================

INSERT INTO venues (name, address, type, price_range, compatible_moods, description, tips, emoji, website_url, neighborhood)
VALUES

-- ══════════════════════════════════════════════════════════════
-- CINEMA (8)
-- ══════════════════════════════════════════════════════════════

('Anteo Palazzo del Cinema',
 'Piazza XXV Aprile 8',
 'cinema', 'mid',
 ARRAY['culturale','rilassato','romantico','creativo'],
 'Multisala indipendente con caffetteria, ristorante e terrazza. Programmazione d''autore e blockbuster selezionati. Il cinema più amato dai milanesi.',
 'La terrazza al terzo piano è perfetta per un aperitivo pre-film.',
 '🎬', NULL, 'porta_nuova'),

('Cinema Mexico',
 'Via Savona 57',
 'cinema', 'low',
 ARRAY['alternativo','culturale','vintage','creativo'],
 'Sala storica sopravvissuta alla gentrificazione di via Savona. Film indipendenti, rassegne a tema e prezzi da un''altra epoca.',
 'Il lunedì i biglietti costano meno — serata perfetta per un film fuori dagli schemi.',
 '🎞️', NULL, 'navigli'),

('Cinema Beltrade',
 'Via Nino Oxilia 10',
 'cinema', 'low',
 ARRAY['alternativo','culturale','rilassato','creativo','vintage'],
 'Monosala di quartiere con programmazione curatissima: classici restaurati, documentari, cinema indipendente da tutto il mondo.',
 'Il bar interno è gestito da un collettivo — prova la birra artigianale prima del film.',
 '📽️', NULL, 'isola'),

('Cineteca Milano MEET',
 'Viale Vittorio Veneto 2',
 'cinema', 'mid',
 ARRAY['culturale','creativo','alternativo','misterioso'],
 'Centro internazionale per la cultura digitale: installazioni immersive, cinema sperimentale e mostre interattive sulla tecnologia.',
 'Le esperienze immersive durano circa 45 minuti — prenota online per evitare la coda.',
 '🖥️', 'https://meetcenter.it', 'porta_venezia'),

('The Space Cinema Odeon',
 'Via Santa Radegonda 8',
 'cinema', 'mid',
 ARRAY['social','rilassato','festivo'],
 'Multisala in pieno centro con sala IMAX tra le più grandi d''Italia. Perfetto per blockbuster in grande stile, a due passi dal Duomo.',
 'La sala IMAX vale il sovrapprezzo — esperienza totalmente diversa.',
 '🍿', 'https://thespacecinema.it', 'centro'),

('Cinema Arlecchino',
 'Via San Pietro all''Orto 9',
 'cinema', 'mid',
 ARRAY['culturale','vintage','rilassato','romantico'],
 'Sala elegante nel cuore del quadrilatero con programmazione che bilancia autore e mainstream. Interni restaurati con cura.',
 'In estate proiettano film all''aperto nel cortile — controlla la programmazione.',
 '🎭', NULL, 'centro'),

('Cinema Gnomo',
 'Via Lanzone 30',
 'cinema', 'low',
 ARRAY['alternativo','culturale','creativo','vintage'],
 'Piccola sala indipendente con una selezione coraggiosa: documentari, cortometraggi, film di nicchia che non trovi altrove.',
 'Le rassegne tematiche del weekend sono il momento migliore per scoprirlo.',
 '🎥', NULL, 'centro'),

('UCI Cinemas Bicocca',
 'Viale Sarca 336',
 'cinema', 'mid',
 ARRAY['social','rilassato','festivo'],
 'Multiplex con 18 sale, IMAX e ScreenX. L''opzione classica per serate film in compagnia con parcheggio facile e ogni comfort.',
 'Compra online per evitare la coda alle casse del venerdì sera.',
 '🎬', NULL, 'altro'),

-- ══════════════════════════════════════════════════════════════
-- TEATRI (7)
-- ══════════════════════════════════════════════════════════════

('Piccolo Teatro Grassi',
 'Via Rovello 2',
 'teatro', 'mid',
 ARRAY['culturale','elegante','creativo','vintage'],
 'Il primo teatro stabile d''Italia, fondato nel 1947. Prosa classica e contemporanea in una sala intima e perfettamente restaurata.',
 'I biglietti per gli under-30 costano pochissimo — controlla le promozioni.',
 '🎭', 'https://piccoloteatro.org', 'centro'),

('Piccolo Teatro Strehler',
 'Largo Greppi 1',
 'teatro', 'mid',
 ARRAY['culturale','elegante','creativo'],
 'La sala grande del Piccolo Teatro: 970 posti, acustica perfetta, produzioni di livello internazionale.',
 'I posti in platea centrale sono i migliori — vale la pena investire qualcosa in più.',
 '🎭', 'https://piccoloteatro.org', 'centro'),

('Teatro Elfo Puccini',
 'Corso Buenos Aires 33',
 'teatro', 'mid',
 ARRAY['culturale','creativo','alternativo','social'],
 'Due sale dedicate al teatro contemporaneo, nuova drammaturgia e stand-up comedy. Sempre in bilico tra provocazione e poesia.',
 'Il bar interno è un punto di ritrovo — fermati dopo lo spettacolo per incontrare gli attori.',
 '🎪', 'https://elfo.org', 'porta_venezia'),

('Teatro Franco Parenti',
 'Via Pier Lombardo 14',
 'teatro', 'mid',
 ARRAY['culturale','creativo','social','alternativo'],
 'Tre sale, una piscina estiva e un ristorante: è un centro culturale a tutto tondo, non solo un teatro. Programmazione eclettica.',
 'D''estate la piscina-teatro è un''esperienza unica — aperitivo in costume e spettacolo.',
 '🏊', 'https://teatrofrancoparenti.it', 'porta_romana'),

('Teatro Dal Verme',
 'Via San Giovanni sul Muro 2',
 'teatro', 'mid',
 ARRAY['musicale','culturale','elegante','romantico'],
 'Storico teatro milanese rinato come sala concerti per orchestra sinfonica, jazz e musica da camera. Acustica eccellente.',
 'I concerti dell''Orchestra dei Pomeriggi Musicali sono un affare per il rapporto qualità-prezzo.',
 '🎵', 'https://dalverme.org', 'centro'),

('Teatro Carcano',
 'Corso di Porta Romana 63',
 'teatro', 'mid',
 ARRAY['culturale','creativo','vintage','romantico'],
 'Uno dei teatri più antichi di Milano (1803). Musical, prosa e danza in un ambiente storico che non perde il suo fascino.',
 'I posti in galleria offrono una vista sorprendentemente buona a metà prezzo.',
 '🎶', 'https://teatrocarcano.com', 'porta_romana'),

('Teatro degli Arcimboldi',
 'Viale dell''Innovazione 20',
 'teatro', 'high',
 ARRAY['culturale','elegante','musicale','festivo','esclusivo'],
 'Sala da 2400 posti che ha ospitato la Scala durante i restauri. Opera, concerti, musical e grandi eventi. Architettura moderna imponente.',
 'Prendi i posti centrali in platea o primo anello — la visuale laterale può essere limitata.',
 '🏛️', 'https://teatroarcimboldi.it', 'altro'),

-- ══════════════════════════════════════════════════════════════
-- MUSEI & SPAZI CULTURALI (10)
-- ══════════════════════════════════════════════════════════════

('MUDEC — Museo delle Culture',
 'Via Tortona 56',
 'museo', 'mid',
 ARRAY['culturale','creativo','alternativo','zen'],
 'Museo dedicato alle culture del mondo con mostre temporanee di grande richiamo. L''architettura interna di David Chipperfield è un''opera d''arte.',
 'Le mostre temporanee al piano terra sono spesso gratuite — controlla il sito.',
 '🌍', 'https://mudec.it', 'navigli'),

('Museo del Novecento',
 'Piazza del Duomo 8',
 'museo', 'mid',
 ARRAY['culturale','creativo','elegante','romantico'],
 'Arte italiana del XX secolo con vista mozzafiato sul Duomo dall''ultimo piano. Da Boccioni a Fontana, tutto in un percorso cronologico.',
 'L''ultimo piano con il Neon di Fontana e la vetrata sul Duomo è il momento più forte.',
 '🎨', 'https://museodelnovecento.org', 'centro'),

('Triennale Milano',
 'Viale Alemagna 6',
 'museo', 'mid',
 ARRAY['culturale','creativo','elegante','alternativo'],
 'Design, architettura e arte contemporanea nel cuore di Parco Sempione. Mostre che cambiano spesso, sempre stimolanti e ben curate.',
 'Il ristorante Terrazza Triennale ha una delle viste più belle di Milano.',
 '🏛️', 'https://triennale.org', 'sempione'),

('Pinacoteca di Brera',
 'Via Brera 28',
 'museo', 'high',
 ARRAY['culturale','elegante','romantico','vintage','creativo'],
 'Una delle collezioni d''arte più importanti d''Italia: Raffaello, Caravaggio, Mantegna. Il cortile con il Napoleone di Canova è iconico.',
 'Il primo giovedì del mese l''ingresso è gratuito dopo le 18 — ma arriva presto.',
 '🖼️', 'https://pinacotecabrera.org', 'brera'),

('Planetario di Milano',
 'Corso Venezia 57',
 'museo', 'mid',
 ARRAY['culturale','romantico','misterioso','zen','creativo'],
 'Il più grande planetario d''Italia, dentro ai Giardini Montanelli. Proiezioni del cielo stellato, conferenze di astronomia e serate a tema.',
 'Le serate speciali con osservazione al telescopio sono magiche — prenota in anticipo.',
 '🔭', 'https://comune.milano.it/aree-tematiche/cultura', 'porta_venezia'),

('Fondazione Prada',
 'Largo Isarco 2',
 'museo', 'mid',
 ARRAY['culturale','creativo','elegante','alternativo','esclusivo'],
 'Complesso espositivo progettato da Rem Koolhaas: arte contemporanea in spazi industriali trasformati. Il Bar Luce di Wes Anderson è cult.',
 'Il Bar Luce da solo vale la visita — colazione o aperitivo in un set cinematografico.',
 '💎', 'https://fondazioneprada.org', 'porta_romana'),

('Pirelli HangarBicocca',
 'Via Chiese 2',
 'museo', 'low',
 ARRAY['culturale','creativo','alternativo','zen'],
 'Ex fabbrica trasformata in spazio per arte contemporanea su larga scala. I Sette Palazzi Celesti di Kiefer sono permanenti e impressionanti. Ingresso gratuito.',
 'Ingresso sempre gratuito su prenotazione — uno dei migliori spazi d''arte gratis in Europa.',
 '🏭', 'https://pirellihangarbicocca.org', 'altro'),

('Museo Nazionale Scienza e Tecnologia',
 'Via San Vittore 21',
 'museo', 'mid',
 ARRAY['culturale','avventuroso','creativo','social'],
 'Il più grande museo tecnico-scientifico d''Italia: dal sottomarino Enrico Toti alla galleria di Leonardo. Perfetto per curiosi di ogni età.',
 'Il sottomarino Toti si visita solo su prenotazione — aggiungilo subito al biglietto.',
 '🚀', 'https://museoscienza.org', 'navigli'),

('Acquario Civico di Milano',
 'Viale Gadio 2',
 'museo', 'low',
 ARRAY['culturale','rilassato','zen','romantico'],
 'Piccolo acquario liberty ai bordi di Parco Sempione. Pesci d''acqua dolce e marina in vasche curate, atmosfera tranquilla e fuori dal tempo.',
 'Ingresso a pochi euro — combinalo con una passeggiata nel parco per un pomeriggio slow.',
 '🐠', 'https://acquariocivicomilano.eu', 'sempione'),

('Fondazione Feltrinelli',
 'Viale Pasubio 5',
 'museo', 'low',
 ARRAY['culturale','creativo','zen','coffee_lover','alternativo'],
 'Edificio spettacolare di Herzog & de Meuron con libreria, spazi studio e caffetteria. Un posto dove leggere, lavorare e respirare cultura.',
 'La caffetteria al piano terra è perfetta per lavorare — Wi-Fi veloce e atmosfera concentrata.',
 '📚', 'https://fondazionefeltrinelli.it', 'porta_nuova'),

-- ══════════════════════════════════════════════════════════════
-- RISTORANTI (12)
-- ══════════════════════════════════════════════════════════════

('Ratanà',
 'Via Gaetano de Castillia 28',
 'ristorante', 'high',
 ARRAY['foodie','elegante','romantico','rilassato'],
 'Cucina milanese rivisitata in una ex casa dei ferrovieri con vista su Porta Nuova. Risotto allo zafferano tra i migliori della città.',
 'Prenota il tavolo in giardino d''estate — il risotto giallo è imperdibile.',
 '🍚', NULL, 'porta_nuova'),

('Tokuyoshi',
 'Via San Calocero 3',
 'ristorante', 'luxury',
 ARRAY['foodie','elegante','esclusivo','creativo','romantico'],
 'Una stella Michelin. Cucina giapponese-italiana dello chef Yoji Tokuyoshi, allievo di Bottura. Piatti che sorprendono ad ogni portata.',
 'Il menu degustazione è l''unico modo per capire davvero la sua cucina — fidati dello chef.',
 '⭐', 'https://tokuyoshi.it', 'navigli'),

('Erba Brusca',
 'Alzaia Naviglio Pavese 286',
 'ristorante', 'mid',
 ARRAY['foodie','rilassato','romantico','zen','creativo'],
 'Ristorante con orto proprio lungo il Naviglio Pavese. Menu che cambia ogni giorno in base al raccolto. Atmosfera campagna in città.',
 'D''estate si mangia in giardino tra le piante dell''orto — prenota il tavolo fuori.',
 '🌱', 'https://erbabrusca.it', 'navigli'),

('Al Fresco',
 'Via Savona 50',
 'ristorante', 'mid',
 ARRAY['foodie','social','rilassato','aperitivo'],
 'Brunch e pranzo in un cortile nascosto di via Savona. Menu stagionale, bowl colorate e atmosfera californiana nel cuore di Milano.',
 'Il brunch del weekend è il loro punto forte — arriva entro le 11 o prenota.',
 '🥗', NULL, 'navigli'),

('Dongiò',
 'Via Bernardino Corio 3',
 'ristorante', 'mid',
 ARRAY['foodie','godereccio','social','vintage','rilassato'],
 'Trattoria calabrese che è un''istituzione per gli universitari della Bocconi. Porzioni enormi, sapori del sud, prezzi onesti.',
 'La ''nduja e la pasta con le sarde sono da ordinare ad occhi chiusi.',
 '🌶️', NULL, 'porta_romana'),

('Røst',
 'Ripa di Porta Ticinese 7',
 'ristorante', 'high',
 ARRAY['foodie','creativo','elegante','alternativo'],
 'Panificazione d''autore di giorno, ristorante creativo di sera. Ogni piatto ruota attorno al pane e ai cereali. Esperienza unica.',
 'Il pane al carbone con burro affumicato è il piatto simbolo — non perderlo.',
 '🍞', NULL, 'navigli'),

('Langosteria Bistrot',
 'Via Privata Bobbio 2',
 'ristorante', 'luxury',
 ARRAY['foodie','elegante','esclusivo','romantico'],
 'La versione più accessibile di Langosteria: pesce freschissimo, servizio impeccabile, atmosfera rilassata ma raffinata.',
 'Il crudo misto è il modo migliore per iniziare — lasciati guidare dal cameriere.',
 '🦞', 'https://langosteria.com', 'porta_romana'),

('Dim Sum',
 'Via Nino Bixio 29',
 'ristorante', 'mid',
 ARRAY['foodie','social','avventuroso','creativo'],
 'Cucina cinese autentica (non il classico ristorante cinese italiano). Dim sum fatti a mano, anatra alla pechinese, xiao long bao perfetti.',
 'Gli xiao long bao (ravioli al vapore) sono i migliori di Milano — ordina almeno due porzioni.',
 '🥟', NULL, 'porta_venezia'),

('Maido',
 'Via Savona 15',
 'ristorante', 'mid',
 ARRAY['foodie','avventuroso','social','creativo'],
 'Ramen giapponese artigianale con brodo cotto per 18 ore. Ambiente minimal e autenticamente giapponese, senza compromessi.',
 'Il tonkotsu ramen è il piatto bandiera — se ami il brodo denso, ordina "extra rich".',
 '🍜', NULL, 'navigli'),

('Berbere',
 'Via Sebenico 21',
 'pizzeria', 'mid',
 ARRAY['foodie','social','creativo','rilassato'],
 'Pizza a lunga lievitazione con farine macinate a pietra e topping stagionali creativi. Birre artigianali selezionate con cura.',
 'La margherita con pomodorino giallo è il benchmark — poi esplora le speciali.',
 '🍕', 'https://berberepizza.it', 'isola'),

('Lievità',
 'Via Privata Cesare Battisti 1',
 'pizzeria', 'mid',
 ARRAY['foodie','social','godereccio','rilassato'],
 'Pizza gourmet napoletana in varie sedi milanesi. Impasto leggero, ingredienti di alta qualità, fritture da urlo.',
 'Il fritto misto all''ingresso non è decorativo — ordinalo come antipasto, è spettacolare.',
 '🍕', 'https://lievitapizzagourmet.it', 'centro'),

('Gino Sorbillo',
 'Largo Corsia dei Servi 11',
 'pizzeria', 'mid',
 ARRAY['foodie','godereccio','social','festivo'],
 'Il re della pizza napoletana è sbarcato a Milano. Impasto soffice, cornicione alto, ingredienti campani doc. Sempre coda, sempre vale la pena.',
 'Arriva all''apertura o dopo le 14:30 per evitare la coda peggiore.',
 '🍕', 'https://sorbillo.it', 'centro'),

-- ══════════════════════════════════════════════════════════════
-- TRATTORIE (5)
-- ══════════════════════════════════════════════════════════════

('Trattoria Milanese',
 'Via Santa Marta 11',
 'trattoria', 'mid',
 ARRAY['foodie','vintage','rilassato','godereccio'],
 'Dal 1933 la stessa famiglia serve i piatti della tradizione milanese: risotto, ossobuco, cotoletta. Un pezzo di storia che non cambia mai.',
 'La cotoletta alla milanese alta (con l''osso) è la migliore della città — punto.',
 '🥩', NULL, 'centro'),

('Trattoria del Nuovo Macello',
 'Via Cesare Lombroso 20',
 'trattoria', 'mid',
 ARRAY['foodie','vintage','godereccio','rilassato','social'],
 'Cucina casalinga con tocco creativo in una zona fuori dai radar. Menu che cambia ogni giorno, vini naturali, atmosfera genuina.',
 'Il menu del giorno a pranzo è un affare incredibile per la qualità che offrono.',
 '🍷', NULL, 'porta_romana'),

('Osteria del Treno',
 'Via San Gregorio 46',
 'trattoria', 'mid',
 ARRAY['foodie','vintage','rilassato','social','godereccio'],
 'Dentro l''ex dopolavoro ferroviario: soffitti liberty, piatti della tradizione lombarda, porzioni generose. Un viaggio nel tempo gastronomico.',
 'Il bollito misto del giovedì è un rito — se capiti quel giorno, non ordinare altro.',
 '🚂', NULL, 'porta_venezia'),

('Trattoria Trippa',
 'Via Giorgio Vasari 1',
 'trattoria', 'mid',
 ARRAY['foodie','creativo','alternativo','godereccio'],
 'Cucina popolare rivisitata: frattaglie, tagli dimenticati, verdure di stagione. Sempre pieno, niente prenotazioni, menu scritto a mano.',
 'Non si prenota — arriva alle 19:30 o dopo le 21 per trovare posto.',
 '🫀', NULL, 'porta_romana'),

('Ratanà Bistrot',
 'Via Gaetano de Castillia 28',
 'trattoria', 'mid',
 ARRAY['foodie','rilassato','social','vintage'],
 'La versione bistrot di Ratanà: piatti milanesi più semplici a prezzi più accessibili, stessa qualità, atmosfera meno formale.',
 'Il mondeghili (polpette milanesi) sono perfetti come antipasto condiviso.',
 '🍝', 'https://ratana.it', 'porta_nuova'),

-- ══════════════════════════════════════════════════════════════
-- CLUB & DISCOTECHE (8)
-- ══════════════════════════════════════════════════════════════

('Fabrique',
 'Via Gaudenzio Fantoli 9',
 'club', 'mid',
 ARRAY['nottambulo','festivo','social','musicale','alternativo'],
 'Ex capannone industriale da 3000 persone. Ospita i nomi più grossi dell''elettronica internazionale: Amelie Lens, Charlotte de Witte, Bicep.',
 'Compra i biglietti su Dice appena escono — i live sold out in poche ore.',
 '🔊', 'https://fabriquemilano.it', 'altro'),

('Amnesia Milano',
 'Via Gatto 1',
 'club', 'mid',
 ARRAY['nottambulo','festivo','social','musicale'],
 'Club storico di Milano con line-up che spaziano dalla techno alla house. Due sale, impianto audio devastante, atmosfera vera da clubbing.',
 'Il venerdì è la serata più forte — sabato è più commerciale.',
 '🪩', 'https://amnesiamilano.com', 'altro'),

('Alcatraz',
 'Via Valtellina 25',
 'club', 'high',
 ARRAY['nottambulo','festivo','social','musicale','alternativo'],
 'Venue da 3000 posti per concerti live e serate club. Dai Radiohead ai DJ set techno, qui ci è passato chiunque.',
 'Per i concerti, arriva presto e posizionati vicino al mixer — il suono è migliore lì.',
 '🎸', 'https://alcatrazmilano.it', 'isola'),

('Rocket Club',
 'Via Pezzotti 52',
 'club', 'mid',
 ARRAY['nottambulo','alternativo','musicale','social'],
 'Club underground con bookings di qualità: techno, minimal, ambient. Piccolo, sudato, autentico. Il posto giusto per chi ama la musica davvero.',
 'Segui le pagine delle singole serate, non del club — ogni serata ha la sua identità.',
 '🚀', NULL, 'navigli'),

('Tunnel Club',
 'Via Sammartini 30',
 'club', 'mid',
 ARRAY['nottambulo','alternativo','musicale','misterioso'],
 'Sotto i binari della Stazione Centrale: techno dura in un tunnel di mattoni. L''esperienza è viscerale, il suono ti attraversa il corpo.',
 'Porta i tappi per le orecchie — il volume è altissimo e le serate durano fino alle 6.',
 '🌀', NULL, 'porta_nuova'),

('Hollywood Milano',
 'Corso Como 15',
 'club', 'high',
 ARRAY['nottambulo','festivo','social','esclusivo','elegante'],
 'Il club più celebre di Corso Como: dagli anni ''80 qui si fa la Milano che balla. Pop, commerciale, hip-hop — pura energia da weekend.',
 'La lista è importante — contatta i PR su Instagram per entrare senza coda.',
 '⭐', 'https://hollywoodmilano.it', 'porta_nuova'),

('Spirit de Milan',
 'Via Bovisasca 59',
 'club', 'mid',
 ARRAY['musicale','vintage','social','alternativo','festivo'],
 'Ex fabbrica con balere, concerti swing e jazz, serate folk. Atmosfera anni ''40 con cucina lombarda. Milano com''era, in chiave moderna.',
 'Le serate balera del giovedì sono uniche — non serve saper ballare, ti insegnano lì.',
 '🎺', 'https://spiritdemilan.it', 'altro'),

('Magazzini Generali',
 'Via Pietrasanta 14',
 'club', 'mid',
 ARRAY['nottambulo','social','festivo','alternativo','musicale'],
 'Venue storica per concerti e serate club in zona Porta Vigentina. Programmazione varia: indie, elettronica, hip-hop italiano.',
 'Il cortile esterno è l''area chill perfetta per riprendere fiato tra un set e l''altro.',
 '📦', 'https://magazzinigenerali.it', 'porta_romana'),

-- ══════════════════════════════════════════════════════════════
-- PUB & BIRRERIE (7)
-- ══════════════════════════════════════════════════════════════

('Birrificio Lambrate',
 'Via Adelchi 5',
 'bar', 'low',
 ARRAY['social','rilassato','godereccio','alternativo','aperitivo'],
 'Il birrificio artigianale più storico di Milano. Birre prodotte a pochi metri dal bancone, atmosphere da pub inglese ma con anima milanese.',
 'La Ghisa (ambrata) è la birra simbolo — perfetta con il tagliere di salumi.',
 '🍺', NULL, 'altro'),

('Baladin Milano',
 'Via Solferino 56',
 'bar', 'mid',
 ARRAY['social','godereccio','rilassato','alternativo','aperitivo'],
 'Open baladin milanese: 40 spine di birra artigianale italiana, hamburger gourmet e un''atmosfera conviviale perfetta per gruppi.',
 'Prova la Nora (birra con spezie) se vuoi qualcosa di diverso dal solito.',
 '🍻', 'https://baladin.it', 'brera'),

('Hop Stuff Brew Pub',
 'Via Negroli 4',
 'bar', 'low',
 ARRAY['social','rilassato','godereccio','alternativo'],
 'Brew pub di quartiere con birre prodotte in loco. Atmosfera informale, menu di panini e comfort food, perfetto per serate senza pretese.',
 'Chiedi la birra del mese — sperimentano sempre con ricette nuove.',
 '🍺', NULL, 'altro'),

('LambiczZoon',
 'Via Friuli 46',
 'bar', 'mid',
 ARRAY['alternativo','godereccio','social','misterioso'],
 'Bar specializzato in birre a fermentazione spontanea (lambic, gueuze, kriek). Selezione unica in Italia per gli appassionati del genere.',
 'Se non conosci i lambic, fatti consigliare — il barista ti guiderà nel percorso gustativo.',
 '🧪', NULL, 'porta_romana'),

('The Doping Club',
 'Via Pastrengo 4',
 'bar', 'mid',
 ARRAY['social','alternativo','rilassato','coffee_lover'],
 'Di giorno specialty coffee, di sera cocktail e birre artigianali. Spazio luminoso e contemporaneo nel cuore di Isola.',
 'Il cold brew d''estate e i cocktail a base caffè sono la specialità della casa.',
 '☕', NULL, 'isola'),

('Pub LOM',
 'Viale Monte Nero 15',
 'bar', 'low',
 ARRAY['social','rilassato','godereccio','aperitivo','vintage'],
 'Pub di quartiere con selezione di birre artigianali, panini generosi e calcio in TV. Il rifugio perfetto per serate semplici tra amici.',
 'Il mercoledì c''è il quiz night — porta una squadra di almeno 4 persone.',
 '🍔', NULL, 'porta_romana'),

('Bésame Mucho',
 'Via Corsico 1',
 'bar', 'low',
 ARRAY['social','alternativo','vintage','rilassato','aperitivo'],
 'Bar e vintage market sui Navigli: scaffali pieni di oggetti retro, vinili in sottofondo, cocktail a prezzi onesti. L''aperitivo con personalità.',
 'Fruga tra gli oggetti vintage mentre aspetti il drink — trovi pezzi incredibili.',
 '💿', NULL, 'navigli'),

-- ══════════════════════════════════════════════════════════════
-- LOUNGE & ROOFTOP (6)
-- ══════════════════════════════════════════════════════════════

('Terrazza Aperol',
 'Piazza del Duomo',
 'rooftop', 'mid',
 ARRAY['aperitivo','social','elegante','festivo'],
 'Terrazza con vista frontale sul Duomo. Spritz ovviamente protagonista, atmosfera turistica ma la vista ripaga tutto.',
 'Vai al tramonto per lo scatto migliore — la luce sulle guglie è perfetta.',
 '🍊', NULL, 'centro'),

('Radio Rooftop',
 'Via Marco Polo 18',
 'rooftop', 'high',
 ARRAY['elegante','aperitivo','romantico','esclusivo'],
 'Rooftop bar dell''hotel ME Milan il Duca: cocktail d''autore, skyline mozzafiato, musica lounge. Milano dall''alto con stile.',
 'Prenota un tavolo per il tramonto — il panorama a 360° è il migliore di Milano.',
 '📻', 'https://melia.com/radio-rooftop-bar', 'centro'),

('Ceresio 7',
 'Via Ceresio 7',
 'rooftop', 'luxury',
 ARRAY['elegante','esclusivo','aperitivo','romantico','social'],
 'Due piscine sul tetto degli ex uffici Enel, ristorante e cocktail bar. L''icona del lusso milanese contemporaneo, firmato Dsquared2.',
 'L''aperitivo a bordo piscina è l''esperienza top — ma prenota con largo anticipo.',
 '🏊', 'https://ceresio7.com', 'sempione'),

('Bulgari Hotel Bar',
 'Via Privata Fratelli Gabba 7b',
 'lounge', 'luxury',
 ARRAY['elegante','esclusivo','romantico','rilassato','misterioso'],
 'Il bar del Bulgari Hotel: giardino nascosto nel centro di Milano, cocktail impeccabili, atmosfera da club esclusivo senza forzature.',
 'Il giardino interno è un''oasi segreta — uno dei posti più belli di Milano nascosti ai più.',
 '💎', 'https://bulgarihotels.com/milan', 'brera'),

('Botanical Club',
 'Via Pastrengo 11',
 'lounge', 'mid',
 ARRAY['rilassato','creativo','aperitivo','alternativo','zen'],
 'Cocktail bar ispirato alla botanica: drink con erbe fresche, fiori commestibili e distillati artigianali. Atmosfera da laboratorio verde.',
 'I gin tonic botanici sono il loro forte — chiedi quello stagionale.',
 '🌿', 'https://thebotanicalclub.com', 'isola'),

('The Yard Milano',
 'Piazza XXIV Maggio 8',
 'lounge', 'mid',
 ARRAY['rilassato','social','aperitivo','elegante','romantico'],
 'Cocktail bar dell''hotel The Yard con cortile interno protetto e atmosfera intima. Drink classici eseguiti alla perfezione.',
 'Il cortile interno d''estate è perfetto per un drink romantico lontano dal caos.',
 '🌳', 'https://theyardmilano.it', 'navigli'),

-- ══════════════════════════════════════════════════════════════
-- PARCHI (7)
-- ══════════════════════════════════════════════════════════════

('Parco Sempione',
 'Piazza Sempione',
 'parco', 'low',
 ARRAY['rilassato','romantico','sportivo','zen','social'],
 'Il grande parco storico di Milano tra il Castello Sforzesco e l''Arco della Pace. Jogging, picnic, passeggiate e aperitivi al tramonto.',
 'Il punto panoramico migliore è dalla collinetta vicino all''Arena Civica — vista sull''intero parco.',
 '🌳', NULL, 'sempione'),

('Biblioteca degli Alberi',
 'Via Gaetano de Castillia',
 'parco', 'low',
 ARRAY['rilassato','zen','romantico','social','sportivo'],
 'Parco contemporaneo nel cuore di Porta Nuova: giardini botanici, yoga gratuito, concerti estivi. Il salotto verde della Milano moderna.',
 'Le lezioni gratuite di yoga la mattina sono un modo incredibile per iniziare la giornata.',
 '🌸', 'https://bam.milano.it', 'porta_nuova'),

('Giardini Indro Montanelli',
 'Corso Venezia',
 'parco', 'low',
 ARRAY['rilassato','romantico','zen','culturale'],
 'Il giardino pubblico più antico di Milano (1784). Laghetto, planetario, museo di storia naturale — tutto in un angolo verde elegante.',
 'Il laghetto con le paperelle è il posto più rilassante della città — portati un libro.',
 '🦆', NULL, 'porta_venezia'),

('Parco delle Basiliche',
 'Via Molino delle Armi',
 'parco', 'low',
 ARRAY['rilassato','zen','romantico','social'],
 'Parco che collega le basiliche di San Lorenzo e Sant''Eustorgio. Panchine sotto i tigli, vista sulle colonne romane, atmosfera raccolta.',
 'Di sera le colonne di San Lorenzo illuminate sono uno dei panorami più belli di Milano.',
 '🏛️', NULL, 'navigli'),

('Boscoincittà',
 'Via Novara 340',
 'parco', 'low',
 ARRAY['sportivo','zen','rilassato','avventuroso'],
 '110 ettari di bosco urbano a ovest di Milano: sentieri per bici, orti comunitari, aree pic-nic e percorsi natura. La fuga dalla città senza uscirne.',
 'Il percorso ad anello da 5 km è perfetto per una corsa immersi nel verde.',
 '🌲', 'https://boscoincittà.it', 'altro'),

('Parco Nord Milano',
 'Via Clerici 150, Sesto San Giovanni',
 'parco', 'low',
 ARRAY['sportivo','zen','rilassato','avventuroso','social'],
 'Enorme parco metropolitano a nord: bunker della WWII visitabili, piste ciclabili, osservazione uccelli. Natura e storia insieme.',
 'I tour guidati ai bunker della Breda sono un''esperienza unica — prenotazione obbligatoria.',
 '🏃', NULL, 'altro'),

('CityLife Park',
 'Piazza Tre Torri',
 'parco', 'low',
 ARRAY['rilassato','sportivo','social','zen','romantico'],
 'Parco urbano moderno circondato dai grattacieli di CityLife. Pista di jogging, area giochi, collinette verdi. Il nuovo skyline milanese.',
 'La passeggiata serale con le torri illuminate è spettacolare — porta la fotocamera.',
 '🏙️', NULL, 'sempione'),

-- ══════════════════════════════════════════════════════════════
-- ATTIVITA' SPORTIVE & LEISURE (10)
-- ══════════════════════════════════════════════════════════════

('K1 Speed Milano',
 'Via Mecenate 76',
 'attivita', 'mid',
 ARRAY['avventuroso','sportivo','social','festivo'],
 'Karting indoor con kart elettrici professionali. Pista con curve tecniche, cronometraggio digitale, perfetto per sfide tra amici.',
 'Prenota la sessione di gruppo (minimo 6) per avere la pista quasi tutta per voi.',
 '🏎️', NULL, 'altro'),

('Urban Paintball Milano',
 'Via Fantoli 15',
 'attivita', 'mid',
 ARRAY['avventuroso','sportivo','social','festivo'],
 'Campo paintball indoor con scenari diversi: urbano, foresta, bunker. Attrezzatura fornita, partite organizzate per gruppi.',
 'Le sessioni del sabato pomeriggio sono le più divertenti — gruppi misti di sconosciuti.',
 '🎯', NULL, 'altro'),

('Laser Game Milano - LaserMaxx',
 'Via Tertulliano 68',
 'attivita', 'low',
 ARRAY['avventuroso','social','festivo','sportivo'],
 'Arena laser tag su due livelli con effetti luminosi e sonori. Partite rapide da 15 minuti, perfette per gruppi e feste.',
 'Prenota almeno 2 partite — la prima è per capire come funziona, la seconda per vincere.',
 '🔫', NULL, 'porta_romana'),

('Padel City Milano',
 'Via Rizzoli 4',
 'attivita', 'mid',
 ARRAY['sportivo','social','rilassato'],
 'Centro padel con campi indoor e outdoor, lezioni per principianti e tornei. Lo sport del momento, facile da imparare e divertente subito.',
 'Prenota il campo per le 18 — dopo la partita c''è l''aperitivo al bar interno.',
 '🎾', NULL, 'altro'),

('Rockspot - Arrampicata Milano',
 'Via Segantini 61',
 'attivita', 'mid',
 ARRAY['sportivo','avventuroso','social','zen'],
 'Palestra di arrampicata con boulder e pareti da 15 metri. Corsi per tutti i livelli, dalla prima volta al training avanzato.',
 'Il corso introduttivo di 2 ore è il modo migliore per iniziare — ti insegnano tutto.',
 '🧗', NULL, 'navigli'),

('QC Terme Milano',
 'Piazzale Medaglie d''Oro 2',
 'attivita', 'high',
 ARRAY['rilassato','zen','romantico','elegante','esclusivo'],
 'Terme e spa nel cuore di Milano, dentro un edificio liberty. Vasche calde, sauna, bagno turco e area relax con vista sulle guglie.',
 'Il percorso serale è più economico e più suggestivo — le luci cambiano tutto.',
 '♨️', 'https://qcterme.com/milano', 'centro'),

('Bowling Rozzano',
 'Strada Vecchia Binasco',
 'attivita', 'low',
 ARRAY['social','festivo','rilassato','godereccio'],
 'Centro bowling con 24 piste, area giochi e ristorante. Classico senza tempo per serate in compagnia tra strike e birre.',
 'La serata "cosmic bowling" con luci UV e musica è molto più divertente del bowling classico.',
 '🎳', NULL, 'altro'),

('Escape Room Milano - Intrappola.to',
 'Via Melchiorre Gioia 3',
 'attivita', 'mid',
 ARRAY['avventuroso','misterioso','social','creativo'],
 'Escape room con stanze a tema: horror, investigazione, avventura. Enigmi ben progettati per gruppi da 2 a 6 persone. Adrenalina e logica.',
 'La stanza "Serial Killer" è la più difficile — provaci solo se hai già esperienza.',
 '🔑', NULL, 'porta_nuova'),

('Virtual Reality Experience - VRUMS',
 'Via Donatello 11',
 'attivita', 'mid',
 ARRAY['avventuroso','creativo','misterioso','social'],
 'Centro di realtà virtuale con esperienze immersive: giochi multiplayer, viaggi virtuali, arte in VR. Tecnologia di ultima generazione.',
 'L''esperienza multiplayer in gruppo è la più divertente — prenotate per almeno 4.',
 '🥽', NULL, 'porta_venezia'),

('Cooking Class at Eataly',
 'Piazza XXV Aprile 10',
 'attivita', 'mid',
 ARRAY['foodie','social','creativo','romantico'],
 'Corsi di cucina nel cuore di Eataly Milano: dalla pasta fresca alla pizza, dalla pasticceria alla cucina regionale. Si impara e si mangia.',
 'Il corso di pasta fresca è il più popolare — prenota con almeno una settimana di anticipo.',
 '👨‍🍳', 'https://eataly.net/it_it/negozi/milano-smeraldo', 'porta_nuova');

-- Batch 1 continua — ultimi 20 venue

INSERT INTO venues (name, address, type, price_range, compatible_moods, description, tips, emoji, website_url, neighborhood)
VALUES

-- ══════════════════════════════════════════════════════════════
-- COCKTAIL BAR & CAFFETTERIE (10)
-- ══════════════════════════════════════════════════════════════

('Backdoor 43',
 'Via Scaldasole 43',
 'cocktail_bar', 'high',
 ARRAY['misterioso','esclusivo','elegante','romantico','creativo'],
 'Il bar più piccolo del mondo: 4 posti dietro una porta nascosta. Prenotazione obbligatoria, cocktail personalizzati, esperienza irripetibile.',
 'Prenota sul sito con almeno 2 settimane di anticipo — solo 4 slot al giorno.',
 '🚪', 'https://backdoor43.it', 'navigli'),

('Iter',
 'Via Marcona 37',
 'cocktail_bar', 'high',
 ARRAY['elegante','misterioso','creativo','esclusivo'],
 'Cocktail bar d''autore che reinventa i classici con ingredienti inaspettati. Ogni drink racconta un viaggio, il menu cambia stagionalmente.',
 'Fidati del bartender — descrivi cosa ti piace e lascia che crei qualcosa per te.',
 '🗺️', NULL, 'porta_romana'),

('Pavé',
 'Via Felice Casati 27',
 'bar', 'mid',
 ARRAY['coffee_lover','rilassato','creativo','social','zen'],
 'Pasticceria e specialty coffee che ha rivoluzionato la colazione milanese. Cornetti sfogliati, lievitati creativi e caffè filtro perfetto.',
 'Il cornetto alla crema di pistacchio è il motivo per cui c''è la coda — arriva alle 8.',
 '🥐', 'https://pavemilano.it', 'porta_venezia'),

('Orsonero Coffee',
 'Via Broggi 15',
 'bar', 'mid',
 ARRAY['coffee_lover','zen','rilassato','creativo'],
 'Micro-roastery con caffè specialty da singola origine. Filtro, aeropress, V60 — per chi il caffè lo prende sul serio.',
 'Il V60 con il caffè etiope è un''esperienza — se bevi solo espresso, preparati a cambiare idea.',
 '☕', 'https://orsonero.com', 'porta_venezia'),

('Taglio',
 'Via Vigevano 10',
 'bar', 'mid',
 ARRAY['coffee_lover','aperitivo','social','rilassato','foodie'],
 'Di giorno gastronomia gourmet e caffè, di sera aperitivo con taglieri e vini naturali. Punto di riferimento sui Navigli per chi ama mangiare bene.',
 'Il tagliere di formaggi con le confetture fatte in casa è il piatto da condividere.',
 '🧀', NULL, 'navigli'),

('Fonderie Milanesi',
 'Via Giovenale 7',
 'bar', 'mid',
 ARRAY['coffee_lover','creativo','social','rilassato','alternativo'],
 'Ex fonderia trasformata in caffetteria e spazio eventi. Brunch, caffè specialty e atmosfera industriale curata.',
 'Il brunch del weekend con granola fatta in casa e succhi freschi è top.',
 '🏭', NULL, 'porta_romana'),

('N''Ombra de Vin',
 'Via San Marco 2',
 'bar', 'mid',
 ARRAY['aperitivo','vintage','rilassato','foodie','romantico'],
 'Enoteca storica in un chiostro agostiniano del ''400. Centinaia di vini, taglieri ricercati, atmosfera da cena medievale romantica.',
 'Chiedi un vino naturale lombardo — la selezione è impressionante.',
 '🍷', NULL, 'brera'),

('Lùbar',
 'Via Carmagnola 5',
 'bar', 'low',
 ARRAY['social','alternativo','aperitivo','rilassato','godereccio'],
 'Circolo ARCI con cortile, concerti, mercatini e birre a prezzi da circolo. Il punto di aggregazione più genuino di Isola.',
 'D''estate il cortile è il posto migliore per un aperitivo economico nella zona.',
 '🌻', NULL, 'isola'),

-- ══════════════════════════════════════════════════════════════
-- RISTORANTI ETNICI & FUSION (12)
-- ══════════════════════════════════════════════════════════════

('Iyo',
 'Via Piero della Francesca 74',
 'ristorante', 'luxury',
 ARRAY['foodie','elegante','esclusivo','creativo','romantico'],
 'Primo ristorante giapponese con stella Michelin in Italia. Omakase di livello assoluto, fusion nippo-italiano.',
 'L''omakase al bancone è l''esperienza definitiva — guardare lo chef lavorare è uno spettacolo.',
 '🍣', NULL, 'sempione'),

('Ba Asian Mood',
 'Via Raffaello Sanzio 22',
 'ristorante', 'mid',
 ARRAY['foodie','avventuroso','social','creativo'],
 'Street food asiatico autentico: bao, gyoza, noodles, curry thai. Tutto fresco, tutto buono, prezzi corretti.',
 'I bao al maiale sono il piatto da non perdere — croccanti fuori, morbidi dentro.',
 '🥡', NULL, 'sempione'),

('Zazà Ramen',
 'Via Solferino 48',
 'ristorante', 'mid',
 ARRAY['foodie','avventuroso','social','rilassato'],
 'Ramen artigianale con brodi cotti per ore. Ambiente minimal giapponese, sapori profondi, porzioni soddisfacenti.',
 'Il tonkotsu extra-rich con uovo marinato è il piatto che non puoi sbagliare.',
 '🍜', NULL, 'brera'),

('Tagiura',
 'Via Tagiura 5',
 'ristorante', 'mid',
 ARRAY['foodie','social','rilassato','godereccio'],
 'Ristorante eritreo/etiope autentico: injera, zighinì, combinazioni vegetariane. Si mangia con le mani, si condivide tutto.',
 'Ordina il misto di carne e verdure su injera — è il modo migliore per provare tutto.',
 '🫓', NULL, 'altro'),

('Bomaki',
 'Via Mercato 3',
 'ristorante', 'mid',
 ARRAY['foodie','social','elegante','creativo'],
 'Fusion nippo-brasiliana: sushi rolls creativi, poke bowl colorati, temaki giganti. Fresco e fotogenico.',
 'Il Bomaki roll signature con tempura di gambero è il piatto bandiera.',
 '🍣', NULL, 'brera'),

('El Porteño Grill',
 'Viale Corsica 5',
 'ristorante', 'mid',
 ARRAY['foodie','godereccio','social','festivo'],
 'Steakhouse argentino con parrilla a vista: asado, entraña, choripan e empanadas. Carne alla brace come a Buenos Aires.',
 'L''entraña (diaframma) alla brace è il taglio che non puoi non provare.',
 '🥩', NULL, 'porta_romana'),

('Mama Shelter Restaurant',
 'Via Tortona 12',
 'ristorante', 'mid',
 ARRAY['social','festivo','foodie','aperitivo','creativo'],
 'Ristorante dell''hotel Mama Shelter con cucina italiana rivisitata, pizza e cocktail. Atmosfera colorata e festosa.',
 'Il brunch della domenica è una festa — con DJ, cocktail e buffet infinito.',
 '🎉', NULL, 'navigli'),

('Taqueria El Nuevo Mariachi',
 'Via Giuseppe Sirtori 11',
 'ristorante', 'low',
 ARRAY['foodie','social','godereccio','avventuroso','festivo'],
 'Tacos, burritos e quesadillas preparati da cuochi messicani. Piccolo, colorato e autentico.',
 'I tacos al pastor con ananas grigliato sono perfetti — aggiungi la salsa habanero se reggi.',
 '🌮', NULL, 'porta_venezia'),

('Haam Korean Restaurant',
 'Via Melzo 1',
 'ristorante', 'mid',
 ARRAY['foodie','avventuroso','social','creativo'],
 'Cucina coreana autentica: bibimbap, kimchi jjigae, korean BBQ al tavolo. Piccolo e sempre pieno, sapori veri.',
 'Il Korean BBQ con il set misto di carni è l''esperienza completa — ordina anche il soju.',
 '🥘', NULL, 'porta_venezia'),

('Piz',
 'Via Torino 34',
 'pizzeria', 'low',
 ARRAY['foodie','social','godereccio','rilassato'],
 'Pizza al taglio romana con impasto croccante e topping creativi. Veloce, economica e perfetta per uno snack in centro.',
 'La pizza con mortadella e stracciatella è la combo più richiesta — arriva prima delle 13.',
 '🍕', NULL, 'centro'),

('Berberè (Isola)',
 'Via Sebenico 21',
 'pizzeria', 'mid',
 ARRAY['foodie','social','creativo','alternativo'],
 'Seconda sede milanese della celebre pizzeria bolognese. Impasto a lunga lievitazione, ingredienti ricercati e birre artigianali.',
 'La pizza con nduja e burrata è la scelta che non delude mai.',
 '🍕', NULL, 'isola'),

('Da Zero',
 'Via Caminadella 2',
 'pizzeria', 'mid',
 ARRAY['foodie','godereccio','rilassato','social'],
 'Pizza napoletana fatta con farine bio e lievito madre. Cornicione soffice, mozzarella di bufala campana DOP. Ambiente informale e accogliente.',
 'La Margherita DOP con bufala campana è il test definitivo — qui è straordinaria.',
 '🍕', 'https://dazeropizza.it', 'navigli');
