-- ============================================================
-- MY MOOD — Seed v3 · Batch 4 (100 venue)
-- ============================================================
-- Focus: ristoranti di quartiere, aperitivo spot, wellness,
--        sport, cultura, vita notturna — zone miste
-- ============================================================
-- Supabase → SQL Editor → incolla tutto → Run
-- ============================================================

INSERT INTO venues (name, address, type, price_range, compatible_moods, description, tips, emoji, website_url, neighborhood)
VALUES

-- ══════════════════════════════════════════════════════════════
-- APERITIVO & WINE BAR (10)
-- ══════════════════════════════════════════════════════════════

('Frida Isola',
 'Via Pollaiuolo 3',
 'bar', 'mid',
 ARRAY['social','aperitivo','rilassato','alternativo'],
 'Bar con giardino nascosto a Isola: aperitivo ricco, cocktail creativi, atmosfera bohémien. Il rifugio perfetto dopo l''ufficio.',
 'D''estate il giardino interno è magico — arriva presto perché i tavoli finiscono.',
 '🌿', NULL, 'isola'),

('Botanical Club Città Studi',
 'Via Pasteur 18',
 'cocktail_bar', 'mid',
 ARRAY['social','elegante','aperitivo','creativo'],
 'Cocktail bar botanico con drink a base di erbe, fiori e infusioni fatte in casa. Ogni drink è una piccola opera d''arte vegetale.',
 'Il cocktail con basilico e lime è il signature — perfetto per iniziare la serata.',
 '🌺', NULL, 'altro'),

('Bar Rita',
 'Via Angelo Fumagalli 1',
 'bar', 'low',
 ARRAY['social','aperitivo','rilassato','vintage'],
 'Bar di quartiere con tavolini fuori, aperitivo generoso e atmosfera da vecchia Milano. Semplice, autentico, frequentato dai locals.',
 'L''aperitivo con focaccia e salumi è abbondante e costa poco — il vero aperitivo milanese.',
 '🍷', NULL, 'porta_romana'),

('Cape Town Café',
 'Via Vigevano 3',
 'bar', 'mid',
 ARRAY['social','aperitivo','musicale','festivo'],
 'Bar sui Navigli con musica dal vivo, cocktail sudafricani e vibe internazionale. Ogni sera un genere diverso: jazz, afrobeat, funk.',
 'Il giovedì sera jazz è imperdibile — arriva alle 20 per prendere posto vicino al palco.',
 '🎵', NULL, 'navigli'),

('Iter Cocktail Bar',
 'Via Castaldi 18',
 'cocktail_bar', 'mid',
 ARRAY['elegante','misterioso','social','aperitivo'],
 'Speakeasy senza insegna: citofonare per entrare. Dentro, cocktail d''autore, luci soffuse, barman in gilet. L''esperienza proibizionismo a Milano.',
 'Non c''è menu — descrivi i tuoi gusti al barman e lui creerà qualcosa su misura.',
 '🥃', NULL, 'porta_venezia'),

('Gineria Brera',
 'Via Fiori Chiari 12',
 'bar', 'mid',
 ARRAY['elegante','social','aperitivo','rilassato'],
 'Bar specializzato in gin: 150+ etichette da tutto il mondo, toniche artigianali, garnish ricercati. Il paradiso per gli amanti del G&T.',
 'Chiedi il flight di 3 gin — ti fanno assaggiare tre combinazioni diverse con toniche abbinate.',
 '🫧', NULL, 'brera'),

('Enoteca Sabbia d''Oro',
 'Via Ravizza 23',
 'bar', 'mid',
 ARRAY['rilassato','foodie','social','vintage','aperitivo'],
 'Enoteca con mescita e taglieri curati: vini naturali, salumi artigianali, formaggi d''alpeggio. L''aperitivo per chi preferisce il vino ai cocktail.',
 'Chiedi il calice del giorno — cambiano vino ogni sera e lo abbinano a un tagliere.',
 '🍇', NULL, 'altro'),

('Terzo Piano Rooftop',
 'Via Tortona 33',
 'rooftop', 'mid',
 ARRAY['social','elegante','aperitivo','romantico'],
 'Rooftop nascosto in zona Tortona: vista sullo skyline, drink curati, finger food. Perfetto per aperitivi speciali e tramonti urbani.',
 'Vai al tramonto per la golden hour — la vista sulla Madonnina da qui è spettacolare.',
 '🌇', NULL, 'navigli'),

('N''Ombra de Vin',
 'Via San Marco 2',
 'bar', 'mid',
 ARRAY['foodie','vintage','rilassato','social','aperitivo'],
 'Enoteca storica in un chiostro del XVI secolo: 3000+ etichette, tavolini sotto i portici, atmosfera senza tempo. Vino e storia insieme.',
 'Il tagliere di formaggi lombardi con mostarda è l''abbinamento perfetto per un calice di rosso.',
 '🏛️', NULL, 'brera'),

('Combo Milano',
 'Ripa di Porta Ticinese 83',
 'bar', 'low',
 ARRAY['social','alternativo','musicale','festivo','aperitivo'],
 'Ostello-bar-spazio culturale sui Navigli: aperitivo internazionale, concerti, DJ set. La versione più cosmopolita e accessibile dei Navigli.',
 'L''aperitivo del giovedì con DJ set sul terrazzo è il miglior rapporto prezzo-vibe della zona.',
 '🌍', NULL, 'navigli'),

-- ══════════════════════════════════════════════════════════════
-- RISTORANTI — CUCINA CREATIVA & CONTEMPORANEA (10)
-- ══════════════════════════════════════════════════════════════

('Lume',
 'Via Giacomo Watt 37',
 'ristorante', 'high',
 ARRAY['elegante','foodie','romantico','creativo'],
 'Ristorante stellato dello chef Luigi Taglienti: cucina ligure-milanese contemporanea, ingredienti di stagione, piatti esteticamente perfetti.',
 'Il menu degustazione è il modo migliore per vivere l''esperienza completa — lasciati guidare.',
 '⭐', 'https://lumemilano.com', 'altro'),

('Erba Brusca al Parco',
 'Alzaia Naviglio Pavese 286',
 'ristorante', 'mid',
 ARRAY['foodie','rilassato','zen','romantico','creativo'],
 'Ristorante con orto proprio in una cascina lungo il Naviglio: menu stagionale che cambia ogni settimana, ortaggi raccolti il giorno stesso.',
 'Prenota un tavolo nel giardino per il pranzo della domenica — sembra di essere in campagna.',
 '🌱', NULL, 'navigli'),

('Røst Coffee & Kitchen',
 'Via Cadore 9',
 'ristorante', 'mid',
 ARRAY['foodie','rilassato','coffee_lover','creativo'],
 'Cucina nordica con influenze italiane: piatti semplici, materie prime eccellenti, caffè specialty. Il brunch del weekend è leggendario.',
 'Il brunch del sabato con uova pochées e salmone è il piatto signature — arriva presto.',
 '🥑', NULL, 'porta_romana'),

('Altatto',
 'Via Melzo 24',
 'ristorante', 'mid',
 ARRAY['foodie','social','godereccio','rilassato'],
 'Cucina di mercato con menu che cambia ogni giorno: piatti scritti a mano sulla lavagna, ingredienti comprati la mattina. Zero sprechi, tutto buono.',
 'Fidati della lavagna — il piatto del giorno è sempre la scelta migliore.',
 '📋', NULL, 'porta_venezia'),

('Un Posto a Milano',
 'Via Cuccagna 2',
 'ristorante', 'mid',
 ARRAY['foodie','rilassato','social','zen','creativo'],
 'Ristorante dentro Cascina Cuccagna: orto urbano, cucina a km zero, giardino con alberi da frutto. La campagna dentro la città.',
 'La domenica il brunch nel giardino è un''esperienza da fare almeno una volta — prenota.',
 '🌳', NULL, 'porta_romana'),

('Alchemist Garden',
 'Via Vigevano 18',
 'ristorante', 'mid',
 ARRAY['foodie','creativo','social','elegante'],
 'Ristorante-laboratorio dove la cucina è sperimentazione: fermentazioni, affumicature, tecniche insolite. Piatti che sorprendono senza esagerare.',
 'Il menu degustazione "Esperimento" da 5 portate è il percorso consigliato per la prima visita.',
 '🧪', NULL, 'navigli'),

('Sine by Di Pinto',
 'Via Lambro 11',
 'ristorante', 'high',
 ARRAY['elegante','foodie','romantico','creativo'],
 'Fine dining dello chef Giuseppe Di Pinto: cucina pugliese rivisitata con tecnica contemporanea. Pochi coperti, ogni piatto è un racconto.',
 'Il risotto al nero di seppia con burrata è un capolavoro — ordinalo se c''è.',
 '🦑', NULL, 'porta_venezia'),

('Motelombroso',
 'Via Lombroso 16',
 'ristorante', 'mid',
 ARRAY['foodie','social','alternativo','godereccio'],
 'Ristorante-spazio culturale con cucina market-driven e eventi serali. Pranzo tranquillo, cena vivace, always interesting.',
 'Il pranzo è più tranquillo e i prezzi più bassi — perfetto per una pausa lunga.',
 '🍽️', NULL, 'porta_romana'),

('Trattoria dalla Cecilia',
 'Via Pordenone 4',
 'trattoria', 'mid',
 ARRAY['foodie','godereccio','vintage','rilassato'],
 'Trattoria familiare nel cuore di NoLo: piatti della nonna, pasta fatta in casa, atmosfera da pranzo domenicale. Genuino fino al midollo.',
 'I ravioli di magro con burro e salvia sono il piatto che ti fa sentire a casa.',
 '👵', NULL, 'altro'),

('Ristorante Torre',
 'Piazza XXV Aprile 10',
 'ristorante', 'high',
 ARRAY['elegante','foodie','social','romantico'],
 'Ristorante con vista dalla terrazza di Porta Nuova: cucina italiana contemporanea, carta dei vini ambiziosa, servizio impeccabile.',
 'Chiedi il tavolo vicino alla vetrata per la vista migliore — e ordina il risotto.',
 '🏙️', NULL, 'porta_nuova'),

-- ══════════════════════════════════════════════════════════════
-- PIZZERIE & FORNI (8)
-- ══════════════════════════════════════════════════════════════

('Dry Milano Solferino',
 'Via Solferino 33',
 'pizzeria', 'mid',
 ARRAY['foodie','social','godereccio','aperitivo'],
 'Pizza gourmet con impasti speciali e topping creativi, più cocktail bar serio. Il connubio pizza + mixology che funziona davvero.',
 'La pizza con burrata e ''nduja è la più amata — abbinala a un cocktail a base di mezcal.',
 '🍕', NULL, 'brera'),

('Lievito Madre al Duomo',
 'Largo Corsia dei Servi 11',
 'pizzeria', 'mid',
 ARRAY['foodie','godereccio','social'],
 'Pizza napoletana con lievitazione 72 ore nel cuore del centro: cornicione soffice, ingredienti campani, forno a legna sempre acceso.',
 'La Margherita con mozzarella di bufala è il test — se è buona qui, il resto è tutto in discesa.',
 '🔥', NULL, 'centro'),

('Pizza Am',
 'Via Lambrate 15',
 'pizzeria', 'mid',
 ARRAY['foodie','godereccio','social','creativo'],
 'Pizza contemporanea con impasti sperimentali: farine integrali, toppings stagionali, abbinamenti inaspettati. La nuova onda della pizza milanese.',
 'La pizza con zucca, gorgonzola e noci è la sleeper hit del menu autunnale.',
 '🍕', NULL, 'altro'),

('Lievità Porta Nuova',
 'Via Moscova 29',
 'pizzeria', 'mid',
 ARRAY['foodie','godereccio','social','elegante'],
 'Pizza fritta e al forno in versione gourmet: frittatine napoletane, montanare, pizze con impasti lunghi. La pizza come esperienza.',
 'Le frittatine ripiene sono il piatto da non perdere — croccanti fuori, filanti dentro.',
 '🫓', 'https://lievita.it', 'porta_nuova'),

('Starita',
 'Via Ampère 49',
 'pizzeria', 'mid',
 ARRAY['foodie','godereccio','social','vintage'],
 'La storica pizzeria napoletana di Don Antonio Starita sbarca a Milano: pizza fritta, montanara, margherita perfetta. Tradizione pura.',
 'La montanara (fritta e poi passata al forno) è il piatto iconico — ordinala sempre.',
 '🇮🇹', NULL, 'altro'),

('Crosta',
 'Via Pascoli 4',
 'pizzeria', 'mid',
 ARRAY['foodie','creativo','social','godereccio'],
 'Pizzeria con panificazione artigianale: impasti con farine macinate a pietra, toppings di stagione, pane fatto in house. Pizza e pane d''autore.',
 'Il pane con burro e alici è l''antipasto perfetto prima della pizza.',
 '🌾', NULL, 'porta_venezia'),

('Forno Collettivo',
 'Via Borsieri 6',
 'altro', 'low',
 ARRAY['foodie','godereccio','rilassato','coffee_lover'],
 'Forno di quartiere a Isola: pane a lievitazione naturale, focacce, dolci da colazione. Tutto fatto con farine selezionate e lievito madre.',
 'La focaccia con mortadella delle 12 è il pranzo perfetto — spesso finisce, arriva in tempo.',
 '🍞', NULL, 'isola'),

('Marghe',
 'Via Cadore 26',
 'pizzeria', 'low',
 ARRAY['godereccio','social','rilassato'],
 'Pizza al trancio alla milanese: alta, soffice, con topping generosi. Il comfort food da asporto per eccellenza, amato da generazioni.',
 'La trancio con wurstel e patatine è il guilty pleasure — non giudicare, assaggia.',
 '🍕', NULL, 'porta_romana'),

-- ══════════════════════════════════════════════════════════════
-- SPORT & ATTIVITA ALL''APERTO (10)
-- ══════════════════════════════════════════════════════════════

('Milano Climbing Lambrate',
 'Via Conte Rosso 20',
 'attivita', 'mid',
 ARRAY['sportivo','social','avventuroso','zen'],
 'Palestra di arrampicata con pareti boulder e lead: percorsi per tutti i livelli, corsi per principianti, community attiva.',
 'Il martedì sera c''è l''open boulder session — perfetta per socializzare e provare nuovi problemi.',
 '🧗', NULL, 'altro'),

('Bike Tour Milano',
 'Via Dante 14',
 'attivita', 'low',
 ARRAY['avventuroso','social','rilassato','culturale'],
 'Tour guidati in bicicletta per Milano: Navigli, street art, architettura, food tour. 2-3 ore pedalando e scoprendo angoli nascosti.',
 'Il tour dei Navigli al tramonto è il più scenografico — prenota quello se puoi.',
 '🚲', NULL, 'centro'),

('Campo Sportivo XXV Aprile',
 'Via Melchiorre Gioia 59',
 'attivita', 'low',
 ARRAY['sportivo','social','rilassato'],
 'Centro sportivo pubblico con campi da calcetto, basket, tennis e pista di atletica. Prezzi accessibili, prenotazione online.',
 'I campetti da calcetto si prenotano su app — il mercoledì sera è il giorno meno affollato.',
 '⚽', NULL, 'porta_nuova'),

('Parco Forlanini',
 'Via Corelli',
 'parco', 'low',
 ARRAY['rilassato','zen','sportivo','social'],
 'Parco enorme vicino a Linate con laghetti, percorsi running, aree picnic. Meno famoso di Sempione ma più spazioso e tranquillo.',
 'Il percorso running lungo il lago è di circa 5 km — perfetto per la corsa mattutina.',
 '🏞️', NULL, 'altro'),

('SUP Naviglio',
 'Alzaia Naviglio Grande 44',
 'attivita', 'mid',
 ARRAY['avventuroso','sportivo','social','rilassato','zen'],
 'Stand Up Paddle sul Naviglio Grande: lezioni per principianti e noleggio tavole. Vedere Milano dall''acqua è un''esperienza unica.',
 'La lezione al tramonto è la più bella — l''acqua è calma e la luce è perfetta.',
 '🏄', NULL, 'navigli'),

('Tennis Club Bonacossa',
 'Via G. Arimondi 15',
 'attivita', 'mid',
 ARRAY['sportivo','social','elegante'],
 'Storico tennis club milanese: campi in terra rossa, lezioni private, tornei sociali. L''atmosfera del tennis classico a due passi da CityLife.',
 'Prenota la lezione di prova — è il modo migliore per valutare il club e conoscere gente.',
 '🎾', NULL, 'sempione'),

('Skateboard Park Lampugnano',
 'Via Lampugnano 76',
 'attivita', 'low',
 ARRAY['sportivo','alternativo','social','creativo'],
 'Skatepark coperto e scoperto con bowl, rampe, rail e area street. Frequentato da skater di tutti i livelli, vibe rilassata.',
 'Il sabato pomeriggio c''è più gente — perfetto per conoscere altri skater e imparare trick.',
 '🛹', NULL, 'altro'),

('Piscina Argelati',
 'Via Segantini 6',
 'attivita', 'low',
 ARRAY['sportivo','rilassato','zen'],
 'Piscina pubblica scoperta in zona Navigli: vasca da 50 metri, area solarium, prezzi comunali. D''estate è la spiaggia dei milanesi.',
 'D''estate arriva presto la mattina — dopo le 11 è pieno e rischiano di chiudere gli ingressi.',
 '🏊', NULL, 'navigli'),

('Parco Ravizza',
 'Via Tito Livio',
 'parco', 'low',
 ARRAY['rilassato','zen','social','sportivo'],
 'Parco verde in zona universitaria: alberi secolari, area cani, percorsi per jogging. Il polmone verde di Città Studi.',
 'La panchina sotto il cedro del Libano è il posto più bello per leggere un libro.',
 '📖', NULL, 'altro'),

('Canottieri San Cristoforo',
 'Alzaia Naviglio Grande 162',
 'attivita', 'mid',
 ARRAY['sportivo','social','rilassato','vintage'],
 'Storica società di canottaggio sul Naviglio: corsi di canoa e kayak, piscina estiva, ristorante. Sport e socialità in un contesto unico.',
 'Il corso di kayak per principianti è il modo più divertente per scoprire i Navigli dall''acqua.',
 '🛶', NULL, 'navigli'),

-- ══════════════════════════════════════════════════════════════
-- MUSEI & CULTURA (8)
-- ══════════════════════════════════════════════════════════════

('Museo del Design Italiano',
 'Piazza Castello (Triennale)',
 'museo', 'mid',
 ARRAY['culturale','creativo','elegante'],
 'Collezione permanente del design italiano alla Triennale: mobili, lampade, oggetti iconici da Castiglioni a Sottsass. La storia del Made in Italy.',
 'Combina la visita con la mostra temporanea della Triennale — un biglietto copre entrambi.',
 '💡', NULL, 'sempione'),

('Memoriale della Shoah',
 'Piazza Edmond J. Safra 1',
 'museo', 'low',
 ARRAY['culturale','zen'],
 'Memoriale sotto la Stazione Centrale: il binario 21 da cui partivano i treni per i campi. Un luogo di memoria potente e necessario.',
 'La visita guidata aggiunge molto — i volontari raccontano storie che non trovi nei pannelli.',
 '🕯️', 'https://memfranceoriale.it', 'altro'),

('Museo Poldi Pezzoli',
 'Via Manzoni 12',
 'museo', 'mid',
 ARRAY['culturale','elegante','vintage','zen'],
 'Casa-museo con collezione d''arte dal Rinascimento al XVIII secolo: Botticelli, Mantegna, orologi, armi antiche. Un gioiello nascosto del centro.',
 'Il Ritratto di Giovane Donna di Pollaiolo vale da solo la visita — è il simbolo del museo.',
 '🖼️', 'https://museopoldipezzoli.it', 'centro'),

('Museo Bagatti Valsecchi',
 'Via Gesù 5',
 'museo', 'mid',
 ARRAY['culturale','elegante','vintage','misterioso'],
 'Dimora rinascimentale dei fratelli Bagatti Valsecchi: arredi originali, arazzi, armature. Come entrare in un palazzo del Quattrocento.',
 'Il venerdì sera il museo è aperto con aperitivo incluso — cultura + drink in un palazzo storico.',
 '🏰', 'https://museobagattivalsecchi.org', 'centro'),

('GAM — Galleria d''Arte Moderna',
 'Via Palestro 16',
 'museo', 'mid',
 ARRAY['culturale','creativo','zen','rilassato'],
 'Arte moderna italiana in una villa neoclassica con giardini: da Canova a Boccioni. La collezione permanente è gratuita il primo martedì del mese.',
 'Dopo la visita, passeggia nei Giardini di Villa Reale — uno dei parchi più belli e meno conosciuti.',
 '🎨', NULL, 'porta_venezia'),

('ADI Design Museum',
 'Piazza Compasso d''Oro 1',
 'museo', 'mid',
 ARRAY['culturale','creativo','elegante'],
 'Museo del Compasso d''Oro: tutti i premi del design italiano dal 1954 a oggi. Un viaggio nella creatività che ha cambiato il quotidiano.',
 'Il bookshop è eccellente — perfetto per regali di design a prezzi ragionevoli.',
 '📐', 'https://adidesignmuseum.org', 'porta_nuova'),

('Museo Nazionale della Scienza — Sottomarino',
 'Via San Vittore 21',
 'museo', 'mid',
 ARRAY['culturale','avventuroso','social'],
 'Il sottomarino Enrico Toti nel cortile del Museo della Scienza: visita guidata dentro un vero sommergibile della Marina Militare.',
 'Prenota la visita al sottomarino online — i posti sono limitati e finiscono subito.',
 '🚢', NULL, 'navigli'),

('Armani/Silos Exhibition',
 'Via Bergognone 40',
 'museo', 'mid',
 ARRAY['culturale','elegante','creativo','esclusivo'],
 'Lo spazio espositivo di Giorgio Armani: 40 anni di moda italiana raccontati attraverso abiti, accessori e visioni. Gratuito e sorprendente.',
 'L''ultimo piano con i vestiti da red carpet è il più spettacolare — non perderlo.',
 '👔', 'https://armanisilos.com', 'navigli'),

-- ══════════════════════════════════════════════════════════════
-- RISTORANTI ETNICI — ASIA & AMERICAS (10)
-- ══════════════════════════════════════════════════════════════

('Chic Noodle Bar',
 'Via Solferino 12',
 'ristorante', 'mid',
 ARRAY['foodie','social','avventuroso'],
 'Noodle bar con ramen, udon e pho preparati al momento: brodi cotti 12 ore, noodles freschi, topping abbondanti. L''Asia in una ciotola.',
 'Il tonkotsu ramen con uovo marinato 24 ore è il piatto da ordinare — ricco e profondo.',
 '🍜', NULL, 'brera'),

('Casa Ramen',
 'Via Lazzaro Papi 28',
 'ristorante', 'mid',
 ARRAY['foodie','social','avventuroso','rilassato'],
 'Ramen bar intimo con menu corto e focalizzato: 4 tipi di ramen, gyoza, edamame. Qualità altissima, porzioni generose, zero fronzoli.',
 'Il miso ramen con chashu è il comfort food perfetto per le serate fredde — ricco e avvolgente.',
 '🍜', NULL, 'porta_romana'),

('Ceviche Bar Lima',
 'Via Tortona 12',
 'ristorante', 'mid',
 ARRAY['foodie','social','avventuroso','festivo'],
 'Cucina peruviana autentica: ceviche, tiradito, anticuchos, pisco sour. Sapori freschi e vibranti, atmosfera latina allegra.',
 'Il ceviche classico con leche de tigre è il piatto da cui partire — fresco e piccante al punto giusto.',
 '🐟', NULL, 'navigli'),

('Tacos Locos',
 'Via Lecco 15',
 'ristorante', 'low',
 ARRAY['foodie','social','festivo','godereccio'],
 'Taqueria autentica con tortillas fatte a mano, salse homemade e margarita ghiacciati. Il Messico a Porta Venezia, colorato e rumoroso.',
 'I tacos al pastor con ananas sono i migliori — aggiungi la salsa verde piccante.',
 '🌮', NULL, 'porta_venezia'),

('Gong Lambrate',
 'Via Oslavia 2',
 'ristorante', 'mid',
 ARRAY['foodie','social','elegante'],
 'Cucina cinese contemporanea in zona Lambrate: dim sum d''autore, anatra laccata, wok di verdure. La versione moderna della tradizione.',
 'Il dim sum del weekend è il brunch perfetto — prenota perché i tavoli vanno subito.',
 '🥢', NULL, 'altro'),

('Viet Mood',
 'Via Vigevano 44',
 'ristorante', 'mid',
 ARRAY['foodie','social','avventuroso','rilassato'],
 'Cucina vietnamita casalinga: pho, banh mi, involtini, caffè vietnamita. Sapori autentici, porzioni generose, prezzi onesti.',
 'Il pho bo (zuppa di manzo) è il piatto da provare — perfetto in inverno, sorprendente in estate.',
 '🥖', NULL, 'navigli'),

('Korean BBQ Koreatown',
 'Via Paolo Sarpi 50',
 'ristorante', 'mid',
 ARRAY['foodie','social','avventuroso','godereccio','festivo'],
 'BBQ coreano con griglia al tavolo: ordini la carne, la cuoci tu, la mangi con banchan e ssamjang. Esperienza interattiva e conviviale.',
 'Il set misto per 2 è il modo migliore per provare tutto — bulgogi, samgyeopsal e galbi.',
 '🥩', NULL, 'altro'),

('Chiccheria Sushi',
 'Via Casale 11',
 'ristorante', 'mid',
 ARRAY['foodie','elegante','zen','romantico'],
 'Sushi omakase con solo 12 posti al bancone: lo chef prepara davanti a te, pesce del giorno, tecnica giapponese pura.',
 'L''omakase da 15 pezzi è l''esperienza completa — lascia fare allo chef e goditi lo spettacolo.',
 '🍣', NULL, 'porta_venezia'),

('Acapulco Cucina Mexicana',
 'Via Borsieri 16',
 'ristorante', 'low',
 ARRAY['social','festivo','godereccio','foodie'],
 'Ristorante messicano colorato a Isola: enchiladas, quesadillas, churros. Porzioni enormi, prezzi bassi, margarita a fiumi.',
 'Il martedì è taco night — tacos a prezzo fisso e margarita scontati.',
 '🇲🇽', NULL, 'isola'),

('Thai Gallery',
 'Via Vigevano 35',
 'ristorante', 'mid',
 ARRAY['foodie','avventuroso','social','elegante'],
 'Cucina thailandese raffinata: pad thai, curry verde, tom yum, papaya salad. Sapori autentici in un ambiente curato con dettagli thai.',
 'Il curry verde con pollo e riso jasmine è il piatto più richiesto — piccante al punto giusto.',
 '🍛', NULL, 'navigli'),

-- ══════════════════════════════════════════════════════════════
-- LOCALI SERALI & MUSIC VENUE (10)
-- ══════════════════════════════════════════════════════════════

('Biko Milano',
 'Viale d''Annunzio 7',
 'bar', 'mid',
 ARRAY['musicale','social','alternativo','festivo'],
 'Club con giardino dedicato a musica indie, elettronica e concerti emergenti. Piccolo palco, buon impianto, atmosfera da festival intimo.',
 'Le serate del venerdì sono le più curate — segui la programmazione su Instagram.',
 '🎸', NULL, 'navigli'),

('Arci Bellezza',
 'Via Bellezza 16a',
 'bar', 'low',
 ARRAY['musicale','alternativo','social','culturale'],
 'Circolo ARCI storico con concerti, cinema all''aperto, dibattiti e dj set. Cultura popolare, prezzi accessibili, community vera.',
 'La tessera ARCI costa pochi euro e dà accesso a tutti gli eventi — falla subito.',
 '🎪', NULL, 'porta_romana'),

('Apollo Zero',
 'Via Borsi 9',
 'club', 'mid',
 ARRAY['nottambulo','musicale','alternativo','social'],
 'Club underground per elettronica e techno: lineup di qualità, sound system potente, pista piccola ma sempre piena.',
 'Le serate del sabato sono le più interessanti — controlla Resident Advisor per i lineup.',
 '🔊', NULL, 'navigli'),

('Tempio del Futuro Perduto',
 'Via Luigi Nono 7',
 'bar', 'low',
 ARRAY['alternativo','creativo','musicale','social','culturale'],
 'Spazio autogestito con bar, concerti, cinema, mostre, teatro. La Milano underground che resiste: cultura dal basso, prezzi popolari.',
 'Ogni sera c''è qualcosa di diverso — consulta il programma settimanale online.',
 '🏚️', NULL, 'altro'),

('Blue Note Lounge',
 'Via Borsieri 37',
 'bar', 'mid',
 ARRAY['musicale','rilassato','elegante','social','vintage'],
 'Jazz bar intimo con concerti live quasi ogni sera: jazz, blues, soul, bossa nova. Atmosfera calda, cocktail curati, pochi tavoli.',
 'Prenota il tavolo vicino al palco — l''esperienza cambia completamente da così vicino.',
 '🎷', NULL, 'isola'),

('Santeria Social Club',
 'Via Ettore Ponti 3',
 'bar', 'mid',
 ARRAY['social','musicale','alternativo','festivo','creativo'],
 'Spazio polifunzionale con bar, cucina, palco e coworking: concerti indie, dj set, eventi culturali. Il cuore pulsante della zona sud.',
 'Il brunch della domenica con musica live è il modo migliore per iniziare la settimana.',
 '🎶', NULL, 'altro'),

('Alcatraz Live',
 'Via Valtellina 25',
 'club', 'mid',
 ARRAY['musicale','social','festivo','nottambulo'],
 'La sala concerti più grande di Milano: 3000 posti, lineup internazionali, serate a tema. Da band indie a artisti mainstream.',
 'Compra i biglietti in prevendita — i concerti importanti vanno sold out in poche ore.',
 '🎤', 'https://alcatrazmilano.it', 'isola'),

('Jazz Café',
 'Corso Sempione 8',
 'bar', 'mid',
 ARRAY['musicale','rilassato','social','elegante','vintage'],
 'Café-bar con piano a coda e jam session serali: jazz standards, improvvisazione, open mic per musicisti. L''atmosfera da club newyorkese.',
 'Il mercoledì è open jam session — porta il tuo strumento e suona con gli altri.',
 '🎹', NULL, 'sempione'),

('Leoncavallo',
 'Via Watteau 7',
 'bar', 'low',
 ARRAY['alternativo','musicale','social','culturale','festivo'],
 'Centro sociale storico di Milano dal 1975: concerti punk/hardcore/reggae, serate techno, dibattiti, cinema. Autogestione e controcultura.',
 'Le serate reggae del sabato sono iconiche — arriva dopo le 23 per il peak.',
 '✊', NULL, 'altro'),

-- ══════════════════════════════════════════════════════════════
-- WELLNESS & RELAX (7)
-- ══════════════════════════════════════════════════════════════

('Ceresio 7 Gym & Spa',
 'Via Ceresio 7',
 'attivita', 'high',
 ARRAY['zen','elegante','rilassato','esclusivo'],
 'Spa con piscina riscaldata sul rooftop, palestra, sauna, hammam. Il lusso del wellness con vista sullo skyline di Milano.',
 'La piscina al tramonto è un''esperienza — prenota il lettino e goditi la vista.',
 '🧖', NULL, 'porta_nuova'),

('Float Hub Milano',
 'Via Thaon di Revel 1',
 'attivita', 'mid',
 ARRAY['zen','rilassato','misterioso','creativo'],
 'Centro di floating: vasche di deprivazione sensoriale con acqua salata a 37°C. Galleggi nel buio, zero gravità, reset totale.',
 'La sessione da 60 minuti è la più efficace — i primi 20 minuti servono per rilassarsi.',
 '🫧', NULL, 'isola'),

('Manforte Studio Yoga',
 'Via Manfredo Camperio 14',
 'attivita', 'mid',
 ARRAY['zen','rilassato','sportivo','creativo'],
 'Studio yoga con classi di vinyasa, hatha, yin e meditazione. Insegnanti certificati, sala luminosa, community accogliente.',
 'La classe di yin yoga del venerdì sera è perfetta per chiudere la settimana — rilascio totale.',
 '🧘', NULL, 'centro'),

('Hammam Milano',
 'Via Fiamma 54',
 'attivita', 'mid',
 ARRAY['zen','rilassato','romantico','esclusivo'],
 'Bagno turco autentico con percorso completo: hammam, scrub, massaggio, sala relax con tè. Un viaggio sensoriale senza prendere un aereo.',
 'Il percorso completo con scrub al sapone nero è il trattamento da fare — non saltarlo.',
 '🛁', NULL, 'porta_venezia'),

('Parco Sempione — Zona Yoga',
 'Viale Gadio (Parco Sempione)',
 'parco', 'low',
 ARRAY['zen','rilassato','sportivo','social'],
 'L''area del parco Sempione dove la mattina si pratica yoga all''aperto: gruppi gratuiti, tai chi, meditazione. Benessere a costo zero.',
 'I gruppi di yoga gratuito si trovano su Meetup — portati il tappetino e presentati.',
 '🌅', NULL, 'sempione'),

('SPA Suite Milano',
 'Via Savona 52',
 'attivita', 'high',
 ARRAY['zen','romantico','rilassato','esclusivo'],
 'Spa privata prenotabile a ore: jacuzzi, sauna, cromoterapia, champagne. L''esperienza wellness intima per coppie o piccoli gruppi.',
 'La suite con jacuzzi e sauna per 2 ore è il pacchetto più richiesto — prenota con anticipo.',
 '💆', NULL, 'navigli'),

('Giardini Indro Montanelli — Percorso Mindfulness',
 'Bastioni di Porta Venezia',
 'parco', 'low',
 ARRAY['zen','rilassato','culturale'],
 'Il parco più antico di Milano con percorsi ombreggiati, laghetto, panchine nascoste. Perfetto per passeggiate meditative e pause dal caos urbano.',
 'Il vialetto lungo il laghetto è il percorso più tranquillo — portati un libro e siediti sulla panchina di pietra.',
 '🦢', NULL, 'porta_venezia'),

-- ══════════════════════════════════════════════════════════════
-- GELATERIE, PASTICCERIE & DOLCI (7)
-- ══════════════════════════════════════════════════════════════

('Gelato Giusto',
 'Via San Gregorio 1',
 'altro', 'low',
 ARRAY['godereccio','rilassato','social'],
 'Gelateria artigianale con gusti che cambiano con le stagioni: pistacchio di Bronte, nocciola Piemonte, sorbetti di frutta fresca.',
 'Il pistacchio è il benchmark — se ti piace qui, hai trovato la tua gelateria.',
 '🍦', NULL, 'porta_venezia'),

('Venchi Duomo',
 'Via Hugo 1',
 'altro', 'mid',
 ARRAY['godereccio','elegante','romantico'],
 'La cioccolateria piemontese nel cuore di Milano: cioccolato artigianale, gelato, cremini. Il tempio del cacao per palati esigenti.',
 'Il gelato al cioccolato fondente con granella di nocciola è pura estasi — provalo in cono.',
 '🍫', 'https://venchi.com', 'centro'),

('Pasticceria Cucchi',
 'Corso Genova 1',
 'altro', 'mid',
 ARRAY['coffee_lover','vintage','godereccio','elegante'],
 'Pasticceria storica dal 1936: panettone, torte classiche, mignon, caffè al bancone. Milano old school, quella vera, con le vetrine di una volta.',
 'Il panettone (da settembre a gennaio) è il migliore della zona — compralo intero come regalo.',
 '🎂', NULL, 'navigli'),

('Cioccolatitaliani',
 'Via Boccaccio 9',
 'altro', 'low',
 ARRAY['godereccio','social','rilassato'],
 'Gelato e cioccolato con cono ripieno di crema, fontana di cioccolato, crepes. Il gelato come spettacolo, goloso e instagrammabile.',
 'Il cono con granella e cuore di crema al pistacchio è il più venduto — worth the hype.',
 '🫠', NULL, 'sempione'),

('Davide Longoni Pane',
 'Via Tiraboschi 19',
 'altro', 'mid',
 ARRAY['foodie','godereccio','coffee_lover','rilassato'],
 'Il pane d''autore di Davide Longoni: lievito madre, farine bio, cottura perfetta. Anche dolci, focacce e caffè. La panificazione come arte.',
 'Il pane di segale e il filone integrale sono i must — portane a casa uno da tagliare a cena.',
 '🍞', NULL, 'porta_romana'),

('Peck — Il Bar',
 'Via Spadari 9',
 'bar', 'high',
 ARRAY['foodie','elegante','godereccio','vintage','esclusivo'],
 'Il bar della storica gastronomia Peck: aperitivo con stuzzichini gourmet, vini pregiati, cocktail classici. L''aperitivo milanese nella sua forma più nobile.',
 'Il tagliere con i salumi di Peck e un calice di Franciacorta è l''aperitivo perfetto.',
 '🥂', 'https://peck.it', 'centro'),

('Martesana',
 'Via Cagliero 14',
 'altro', 'mid',
 ARRAY['godereccio','coffee_lover','creativo','elegante'],
 'Pasticceria contemporanea dello chef Vincenzo Santoro: dolci architettonici, monoporzioni scultoree, colazioni da urlo. La pasticceria come design.',
 'La monoporzione al cioccolato e passion fruit è un''opera d''arte — bella e buona.',
 '🍰', 'https://martfranceesana.it', 'isola'),

-- ══════════════════════════════════════════════════════════════
-- TEATRI & SPETTACOLO (5)
-- ══════════════════════════════════════════════════════════════

('Teatro Menotti',
 'Via Ciro Menotti 11',
 'teatro', 'mid',
 ARRAY['culturale','creativo','social','alternativo'],
 'Teatro di prosa con stagione ricca: drammaturgia contemporanea, monologhi, commedie brillanti. Sala intima, acustica perfetta, palco vicino.',
 'I monologhi del giovedì sera sono spesso i più intensi — controlla la stagione.',
 '🎭', 'https://teatromenotti.org', 'porta_romana'),

('Teatro Parenti — Sala Grande',
 'Via Pier Lombardo 14',
 'teatro', 'mid',
 ARRAY['culturale','elegante','social','creativo'],
 'Sala principale del Franco Parenti: spettacoli di prosa, danza, musica, eventi speciali. Programmazione ambiziosa e sempre stimolante.',
 'Il bar del teatro è un ottimo aperitivo pre-spettacolo — arriva 30 minuti prima.',
 '🎪', 'https://teatrofrancoparenti.it', 'porta_romana'),

('Teatro Gerolamo',
 'Piazza Beccaria 8',
 'teatro', 'mid',
 ARRAY['culturale','elegante','vintage','romantico'],
 'Il teatro più piccolo di Milano, restaurato nel 2017: marionette, musica da camera, recital. Un gioiello con 200 posti e affreschi originali.',
 'Gli spettacoli di marionette non sono solo per bambini — la tradizione milanese è raffinata.',
 '🎎', 'https://teatrogerolamo.it', 'centro'),

('Teatro della Cooperativa',
 'Via Hermada 8',
 'teatro', 'low',
 ARRAY['culturale','alternativo','social','creativo'],
 'Teatro di quartiere con drammaturgia impegnata: testi contemporanei, nuovi autori, temi sociali. Cultura accessibile, prezzi popolari.',
 'Il biglietto ridotto under 30 è un affare — controlla la programmazione settimanale.',
 '🎭', NULL, 'altro'),

('Blue Rose Cabaret',
 'Via Lombroso 24',
 'bar', 'mid',
 ARRAY['musicale','festivo','creativo','social','misterioso'],
 'Cabaret e burlesque nel cuore di Porta Romana: show dal vivo, cocktail a tema, atmosfera anni ''20. Intrattenimento d''altri tempi.',
 'Prenota il tavolo davanti al palco e ordina il cocktail del giorno — è parte dello show.',
 '🌹', NULL, 'porta_romana'),

-- ══════════════════════════════════════════════════════════════
-- RISTORANTI — CARNE & GRILL (5)
-- ══════════════════════════════════════════════════════════════

('Barbacoa',
 'Via Savona 43',
 'ristorante', 'mid',
 ARRAY['foodie','godereccio','social','festivo'],
 'Steakhouse con griglia a carbone e tagli selezionati: fiorentina, tomahawk, costata. Per carnivori seri, cotture perfette, porzioni generose.',
 'La fiorentina da 1 kg per due con contorni è l''esperienza completa — accompagna con un Brunello.',
 '🥩', NULL, 'navigli'),

('Burnout Grill',
 'Via Borsieri 28',
 'ristorante', 'mid',
 ARRAY['foodie','social','godereccio'],
 'Grill house con carni da tutto il mondo: wagyu, angus, chianina. Affumicatura lenta, salse homemade, atmosfera da steakhouse americana.',
 'Il brisket affumicato 12 ore è il piatto da non perdere — tender e succoso come deve essere.',
 '🔥', NULL, 'isola'),

('Osteria della Bistecca',
 'Via Solferino 42',
 'trattoria', 'mid',
 ARRAY['foodie','godereccio','social','vintage'],
 'Osteria toscana dedicata alla bistecca: fiorentina di chianina, fagioli all''uccelletto, crostini, Chianti. La Toscana a Brera.',
 'La fiorentina si ordina al kg — chiedi al cameriere la pezzatura migliore per il tavolo.',
 '🐄', NULL, 'brera'),

('Muu Muuzzarella',
 'Via Vigevano 9',
 'ristorante', 'mid',
 ARRAY['foodie','godereccio','social','rilassato'],
 'Mozzarella bar con prodotti campani che arrivano ogni mattina: burrata, mozzarella di bufala, stracciatella. Il latte trasformato in paradiso.',
 'La burrata con pomodorini datterini e pane croccante è il piatto perfetto — semplicità pura.',
 '🧀', NULL, 'navigli'),

('Polpo Brace & Griglia',
 'Via Casale 4',
 'ristorante', 'mid',
 ARRAY['foodie','social','godereccio','elegante'],
 'Griglieria di pesce: polpo alla brace, gamberi, calamari, spiedini misti. Il pesce cotto sul fuoco come al mare, nel cuore di Milano.',
 'Il polpo alla brace con patate schiacciate è il piatto che vale il viaggio.',
 '🐙', NULL, 'porta_venezia'),

-- ══════════════════════════════════════════════════════════════
-- SHOPPING & MERCATI SPECIALI (4)
-- ══════════════════════════════════════════════════════════════

('Mercato Isola',
 'Via Borsieri 12',
 'altro', 'low',
 ARRAY['foodie','social','alternativo','godereccio'],
 'Mercato rionale coperto con banchi di frutta, formaggi, gastronomia, pesce. L''anima popolare di Isola, perfetto per fare la spesa come una volta.',
 'Il banco dei formaggi lombardi è il migliore — chiedi di assaggiare il Taleggio stagionato.',
 '🧺', NULL, 'isola'),

('Fiera di Sinigaglia',
 'Ripa di Porta Ticinese (Darsena)',
 'altro', 'low',
 ARRAY['vintage','alternativo','social','creativo'],
 'Mercato delle pulci storico di Milano, ogni ultimo sabato del mese: vinili, vestiti vintage, antiquariato, curiosità. Il paradiso del vintage.',
 'Arriva presto la mattina per i pezzi migliori — i venditori più interessanti sono quelli in fondo.',
 '🕰️', NULL, 'navigli'),

('Mercato del Suffragio',
 'Piazza Santa Maria del Suffragio',
 'altro', 'low',
 ARRAY['foodie','godereccio','social','rilassato'],
 'Mercato coperto di quartiere con produttori locali: verdure bio, pane artigianale, salumi, miele. La filiera corta nel cuore della città.',
 'Il sabato mattina c''è il mercato contadino — produttori diretti con prezzi equi.',
 '🥬', NULL, 'porta_venezia'),

('East Market Shop',
 'Via Privata Giovanni Ventura 6',
 'altro', 'low',
 ARRAY['vintage','creativo','alternativo','social'],
 'Negozio permanente del mercatino East Market: abbigliamento vintage selezionato, sneakers rare, dischi, oggettistica. Il vintage curato.',
 'La sezione sneakers vintage ha pezzi unici — chiedi allo staff cosa è arrivato di nuovo.',
 '👟', NULL, 'altro'),

-- ══════════════════════════════════════════════════════════════
-- PUB & BIRRERIE — ZONA SUD (4)
-- ══════════════════════════════════════════════════════════════

('The Drunken Ship',
 'Ripa di Porta Ticinese 9',
 'bar', 'low',
 ARRAY['social','festivo','godereccio','rilassato'],
 'Pub irlandese sui Navigli: birre alla spina, fish & chips, partite in TV. L''atmosfera da pub britannico per serate senza pretese.',
 'Durante le partite di Champions il pub è pieno — arriva presto per prendere il tavolo con vista TV.',
 '🍺', NULL, 'navigli'),

('Porterhouse Milano',
 'Via De Amicis 1',
 'bar', 'mid',
 ARRAY['social','godereccio','rilassato','festivo'],
 'Pub con birre artigianali e cucina pub-gourmet: hamburger, fish tacos, ali di pollo. Atmosfera internazionale, clientela mista, sport live.',
 'L''hamburger con cheddar stagionato e bacon croccante è il piatto da ordinare.',
 '🍔', NULL, 'navigli'),

('Backdoor Speakeasy',
 'Via Solferino 36',
 'cocktail_bar', 'mid',
 ARRAY['misterioso','elegante','social','romantico'],
 'Speakeasy nascosto dietro una porta senza insegna: solo 24 posti, cocktail su misura, prenotazione obbligatoria. L''esclusività fatta drink.',
 'Prenota online con almeno una settimana di anticipo — i posti sono pochissimi.',
 '🚪', NULL, 'brera'),

('Birra & Blues',
 'Via Ascanio Sforza 9',
 'bar', 'low',
 ARRAY['musicale','social','rilassato','alternativo'],
 'Pub con musica blues e rock dal vivo: concerti quasi ogni sera, birre artigianali, atmosfera da juke joint americano. Il blues a Milano.',
 'Il venerdì sera blues jam è aperta a tutti i musicisti — porta lo strumento e sali sul palco.',
 '🎸', NULL, 'navigli'),

-- ══════════════════════════════════════════════════════════════
-- LIBRERIE & SPAZI CULTURALI (3)
-- ══════════════════════════════════════════════════════════════

('Libreria Verso',
 'Corso di Porta Ticinese 40',
 'altro', 'low',
 ARRAY['culturale','creativo','rilassato','alternativo'],
 'Libreria indipendente con selezione curata: narrativa, saggistica, fumetti, riviste indie. Presentazioni e reading quasi ogni settimana.',
 'Chiedi consiglio ai librai — conoscono ogni libro sullo scaffale e sanno cosa ti piacerà.',
 '📚', NULL, 'navigli'),

('Libreria Open',
 'Via Volta 14',
 'altro', 'low',
 ARRAY['culturale','rilassato','zen','creativo'],
 'Libreria-caffè a Isola con angolo lettura, eventi letterari e caffè specialty. Il posto perfetto per comprare un libro e iniziarlo subito.',
 'Il tavolino vicino alla finestra con il caffè filtro è il rituale perfetto del sabato mattina.',
 '📖', NULL, 'isola'),

('Spazio Avanzi',
 'Via Ampère 61',
 'altro', 'low',
 ARRAY['culturale','alternativo','creativo','social'],
 'Spazio culturale indipendente in zona universitaria: mostre, workshop, proiezioni, presentazioni di libri. Cultura dal basso, community attiva.',
 'Gli workshop creativi del weekend sono aperti a tutti — controlla il programma su Instagram.',
 '🎨', NULL, 'altro');
